<?php
/**
 * Add/redeem Gift Voucher template
 */
?>



<div id="monogram-page-account-mobile-header" class="visible-sm visible-xs">
  <h4>membership services</h4>
  <h2>gift card</h2>
</div>

<div id="monogram-page-account-mobile-page-title" class="visible-sm visible-xs">
  <h1><?php echo $this->__('Add Gift Card') ?></h1>
</div>

<div id="monogram-page-account-giftcard-detail-container">


    <div class="page-title">
        <h1><?php echo $this->__('Add Gift Card') ?></h1>
        <hr class="small">
    </div>

    <div class="row">
        <div class="col-md-6">
            <form id="addredeem-giftvoucher-code" method="post" action="<?php echo $this->getFormActionUrl() ?>">
                <div class="fieldset">
                    <!-- <h2 class="legend"><?php echo $this->__('Add/Redeem a Gift Card') ?></h2> -->
                    <ul class="form-list">
                        <li class="fields">
                            <div class="giftvoucher-code">
                                <div class="field">

                                    <div class="each-input">
                                        <label for="giftvouchercode" class="required"><?php echo $this->__('Enter Gift Card Code') ?><em>*</em></label>
                                        <div class="input-box">
                                            <input style="width: 200%;"id="gift-voucher-code" name="giftvouchercode" value="" title="<?php echo $this->__('Enter Gift Card Code') ?>" class="input-text required-entry" type="text">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <p class="required visible-md visible-lg"><em> * </em><?php echo $this->__('Required Fields') ?></p>
                </div>
                

                <div class="edit-button-container">
                    <?php if (Mage::helper('giftvoucher')->getGeneralConfig('enablecredit')) { ?>
                        <!-- <button type="button" onclick="redeemgiftcard()" title="<?php echo $this->__('Redeem Gift Card') ?>" class="cta button square-cta"><?php echo $this->__('Redeem Gift Card') ?></button> -->
                    <?php } ?>
                    <button type="submit" title="<?php echo $this->__('Add To Your List') ?>" class="cta button square-cta"><?php echo $this->__('Add To Your List') ?></button>
                </div>

                <div class="buttons-set" style="display:none;">
                    <!--edit by  Sally-->
                    <div class="button-add-list">
                        <?php if (Mage::helper('giftvoucher')->getGeneralConfig('enablecredit')) { ?>
                            <button type="button" onclick="redeemgiftcard()" title="<?php echo $this->__('Redeem Gift Card') ?>" class="cta button"><span><span><?php echo $this->__('Redeem Gift Card') ?></span></span></button>
                            
                        <?php } ?>
                        <button type="submit" title="<?php echo $this->__('Add To Your List') ?>" class="cta button"><span><span><?php echo $this->__('Add To Your List') ?></span></span></button>
                    </div>
                    
                    <!--end by Sally-->
                </div>
                <p class="back-link t1"><a href="<?php echo $this->getUrl('giftvoucher/index/index') ?>"><small>« </small><?php echo $this->__('Back') ?></a></p>
            </form>

            <script type="text/javascript">
                //<![CDATA[
                var dataForm = new VarienForm('addredeem-giftvoucher-code', true);
                function redeemgiftcard() {
                    var clForm = new VarienForm('addredeem-giftvoucher-code', true);
                    if (clForm.validator.validate() == false) {
                        return false;
                    }
                    setLocation('<?php echo $this->getUrl("giftvoucher/index/redeem") ?>' + 'giftvouchercode/' + $('gift-voucher-code').value);
                }
                //]]>
            </script>
            <script>
                $j(".messages").addClass("redeem-message");

                
            </script>
        </div>
    </div>


</div> <!-- #monogram-page-account-giftcard-detail-container -->

<div class="space100"></div>
<div class="space100"></div>
<div class="space100"></div>
<div class="space100"></div>