<?php
/**
 * Grid template
 */
?>

<?php $collection = $this->getCollection() ?>
<?php $columns = $this->getColumns() ?>
<?php $timezone = Mage::app()->getStore()->getConfig('general/locale/timezone'); ?>

  <!--
     ____ _____ ___  ____  _____ ____
    / ___|_   _/ _ \|  _ \| ____|  _ \
    \___ \ | || | | | |_) |  _| | | | |
     ___) || || |_| |  _ <| |___| |_| |
    |____/ |_| \___/|_| \_\_____|____/

  -->


  <div id="page-account-gift-card-stored-table" class="page-account-table">

    <div class="page-account-table-header hidden-xs">
      <div class="row">
        <?php 
        $column_counter = 0; 
        $column_counter_max = count($columns); 
        ?>
        <?php foreach ($columns as $id => $column): ?>
            <?php $column_counter++; ?>
            
            <?php if($column_counter==$column_counter_max): ?>
            <div class="col-md-2"></div>
            <div class="col-md-2">
            <?php else: ?>
            <div class="col-md-4">
            <?php endif; ?>
              <div class="<?php if($column_counter==1): ?>table-column-first<?php elseif($column_counter==$column_counter_max): ?>table-column-last<?php else: ?>table-column<?php endif; ?>">
                <h4><?php echo $column['header'] ?></h4>
              </div>
            </div>            
        <?php endforeach; ?>
      </div>
    </div> <!-- page-account-table-header -->

    <div class="page-account-table-item-container">
    <?php if ($collection->count()): ?>
        <?php foreach ($collection as $row): ?>
            <?php if ($row->getIsContinueNextRow()) continue; ?>
              <div class="page-account-table-item">
                <div class="row">
                    <?php                                 
                        $column_counter = 0;      
                        $column_counter_max = count($columns);                            
                    ?>
                    <?php foreach ($columns as $id => $column): ?>
                      <?php $column_counter++; ?>

                      <?php if($column_counter==$column_counter_max): ?>
                        <div class="col-md-2 col-sm-0 col-xs-0"></div>
                        <div class="col-md-2 col-sm-4 col-xs-12">
                      <?php else: ?>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                      <?php endif; ?>
                            <div <?php if($column_counter==1): ?>class="table-column-first" data-column="Gift card code: "<?php elseif($column_counter==$column_counter_max): ?>class="table-column-last" data-column="Expiry date: "<?php else: ?>class="table-column" data-column="Amount: "<?php endif; ?>">
                                
                                    <!--end by Sally-->
                                    <?php if (isset($column['render']) && $column['render']): ?>
                                        <p><?php echo $this->fetchRender($column['render'], $row) ?></p>
                                    <?php else: ?>
                                        <?php $type = isset($column['type']) ? $column['type'] : '' ?>
                                        <?php switch ($type): 
                                            case 'action': ?>
                                                <?php $action = $column['action'] ?>
                                                <a href="<?php echo $this->getUrl($action['url'], array($action['name'] => $row->getData($action['field']))) ?>" title="<?php echo $action['label'] ?>"><?php echo $action['label'] ?></a>
                                                <?php
                                                break;
                                            case 'options':
                                                ?>
                                                <p>
                                                <?php echo $column['options'][$row->getData($column['index'])] ?></p>
                                                <?php
                                                break;
                                            case 'date':
                                                ?>
                                                <!--Hai.Tran-->
                                                <p>
                                                <?php
                                                if ($row->getData($column['index']))
                                                    //echo $this->formatDate($row->getData($column['index']), $column['format'], false);
                                                    echo $this->formatDate($row->getData($column['index']), 'short', false);
                                                else
                                                    echo $this->__('Permanent');
                                                ?>
                                                </p>
                                                <?php
                                                break;
                                            case 'datetime':
                                                ?>
                                                <p>
                                                <?php echo $this->formatDate($row->getData($column['index']), $column['format'], true) ?></p>
                                                <?php
                                                break;
                                            case 'price':
                                                ?>
                                                <p><?php echo Mage::app()->getStore()->formatPrice($row->getData($column['index'])) ?></p>
                                                <?php
                                                break;
                                            case 'baseprice':
                                                ?>
                                                <p>
                                                <?php echo Mage::helper('core')->currency($row->getData($column['index'])) ?>
                                                </p>
                                                <?php
                                                break;
                                            default:
                                                ?>
                                                <p><?php echo $row->getData($column['index']) ?></p>
                                        <?php endswitch ?>
                                    <?php endif ?>
                                
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
              </div> <!-- page-account-table-item -->
        <?php endforeach; ?>
    <?php else: ?>
        <div class="page-account-table-item">
            <div class="row">
                <div class="col-md-12">
                    <p><?php echo $this->__('There are no items matching this selection.') ?></p>
                </div>
            </div>
        </div>
    <?php endif; ?>

    </div> <!-- page-account-table-item-container -->

    <?php echo $this->getPagerHtml() ?>    

  </div> <!-- page-account-gift-card-stored-table -->