<?php
/**
 * Grid template
 */
?>
<?php if ($this->getData('add_calendar_js_to_grid')): ?>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>calendar/calendar.js"></script>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>calendar/calendar-setup.js"></script>
    <?php echo $this->getLayout()->createBlock('core/html_calendar')->setTemplate('page/js/calendar.phtml')->toHtml() ?>
    <link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js') ?>calendar/calendar-win2k-1.css"  />
<?php endif ?>

<?php $collection = $this->getCollection() ?>
<?php $columns = $this->getColumns() ?>
<?php $timezone = Mage::app()->getStore()->getConfig('general/locale/timezone'); ?>

<?php if ($this->getData('add_searchable_row')): ?>
    <!-- <div class="giftvoucher-search-button">
        <span style="float: left;font-weight: bold;color: #3399cc;font-size: 11px;font-style: italic;padding-top: 58px;">
            <?php echo $this->__('"Date is set in timezone ' . $timezone . '"') ?>
        </span>
        <button class="form-button button" type="button" onclick="setLocation('<?php echo $this->getFilterUrl() ?>');">
            <span>
                <span><?php echo $this->__('Reset Filter') ?></span>
            </span>
        </button>
        <button class="form-button button" type="button" onclick="searchGrid<?php echo $this->getNameInLayout() ?>();">
            <span>
                <span><?php echo $this->__('Search') ?></span>
            </span>
        </button>
    </div> -->
    <script type="text/javascript">
        function searchGrid<?php echo $this->getNameInLayout() ?>() {
            var inputEl = $$('#<?php echo $this->getNameInLayout() ?> thead input');
            $$('#<?php echo $this->getNameInLayout() ?> thead select').each(function(el) {
                inputEl.push(el);
            });
            var filter = Form.serializeElements(inputEl);
            filter = aff_base64_encode(filter);
            var url = '<?php echo $this->getFilterUrl() ?>';
            if (url.search('[?]') == -1) {
                url += '?filter=' + filter;
            } else {
                url += '&filter=' + filter;
            }
            setLocation(url);
        }
        function inputPressEnter<?php echo $this->getNameInLayout() ?>(event) {
            if (event.which == 13) {
                searchGrid<?php echo $this->getNameInLayout() ?>();
            } else if (event.keyCode == 13) {
                searchGrid<?php echo $this->getNameInLayout() ?>();
            }
        }
        Event.observe(window, 'load', function() {
            $$('#<?php echo $this->getNameInLayout() ?> thead input').each(function(el) {
                Event.observe(el, 'keypress', inputPressEnter<?php echo $this->getNameInLayout() ?>);
            });
            $$('#<?php echo $this->getNameInLayout() ?> thead select').each(function(el) {
                Event.observe(el, 'keypress', inputPressEnter<?php echo $this->getNameInLayout() ?>);
            });
        });
        function aff_utf8_encode(string) {
            string = string.replace(/\r\n/g, "\n");
            var result = "";
            for (var i = 0; i < string.length; i++) {
                var c = string.charCodeAt(i);
                if (c < 128) {
                    result += String.fromCharCode(c);
                } else if ((c > 127) && (c < 2048)) {
                    result += String.fromCharCode((c >> 6) | 192, (c & 63) | 128);
                } else {
                    result += String.fromCharCode((c >> 12) | 224, ((c >> 6) & 63) | 128, (c & 63) | 128);
                }
            }
            return result;
        }
        function aff_base64_encode(string) {
            var result = '';
            var keyMap = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_,";
            var c1, c2, c3;
            string = aff_utf8_encode(string);
            for (var i = 0; i < string.length; i++) {
                c1 = string.charCodeAt(i++);
                c2 = string.charCodeAt(i++);
                result += keyMap.charAt(c1 >> 2);
                result += keyMap.charAt(((c1 & 3) << 4) | (c2 >> 4));
                if (isNaN(c2)) {
                    result += ',,';
                    continue;
                }
                c3 = string.charCodeAt(i);
                result += keyMap.charAt(((c2 & 15) << 2) | (c3 >> 6));
                if (isNaN(c3)) {
                    result += ',';
                    continue;
                }
                result += keyMap.charAt(c3 & 63);
            }
            return result;
        }
    </script>
<?php endif ?>

<!-- <span class="pager-header"><?php echo $this->getPagerHtml() ?></span> -->

<!-- <div class="table-responsive">
    <table id="gift-cards-tbl" class="table">
        <thead>
            <tr>
                <th>CODE NO.</th>
                <th>EXPIRE DATE</th>
                <th>ORDER NO.</th>
                <th>DESCRIPTION</th>
                <th>AMOUNT</th>
                <th>STATUS</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><p class="code_no">A22P25342M</p></td>
                <td><p class="expire_date">03 Jan 2015</p></td>
                <td><p class="order_no"></p></td>
                <td><p class="description">Purchased by Smantha</p></td>
                <td><p class="amount">S$ 100.00</p></td>
                <td><p class="status">Available</p></td>
            </tr>
            <tr>
                <td><p class="code_no">M374ls923S</p></td>
                <td><p class="expire_date">17 Nov 2014</p></td>
                <td><p class="order_no"></p></td>
                <td><p class="description">Purchased by Joanne Photobiz</p></td>
                <td><p class="amount">S$ 100.00</p></td>
                <td><p class="status">Available</p></td>
            </tr>
            <tr>
                <td><p class="code_no">g6d7s6234l</p></td>
                <td><p class="expire_date">28 Sep 2014</p></td>
                <td><p class="order_no">28092014</p></td>
                <td><p class="description">Welcoming gift for registering as member</p></td>
                <td><p class="amount">S$ 50.00</p></td>
                <td><p class="status redeemed">Redeemed</p></td>
            </tr>
        </tbody>
    </table>
</div> -->


<div class="visible-md-block visible-lg-block">
    <div class="table-responsive">
        <table id="gift-cards-tbl" cellspacing="0" class="data-table linearize-table">
            <!-- <colgroup>
                <?php foreach ($columns as $id => $column): ?>
                    <col class="<?php echo $id ?>" style="<?php if (isset($column['align'])): ?>align:<?php echo $column['align'] ?>;<?php endif ?><?php if (isset($column['width'])): ?>width:<?php echo $column['width'] ?><?php endif ?>" />
                <?php endforeach ?>
            </colgroup> -->
            <thead>
                <tr <?php if ($this->getData('add_searchable_row')): ?>class="giftvoucher-grid-title test"<?php endif ?>>

                    <?php 
                        $column_counter = 0; 
                        $column_counter_max = count($columns);                        
                    ?>
                    <?php foreach ($columns as $id => $column): ?>

                        <?php $column_counter++; ?>
                        
                        <?php if($column_counter == 4): ?>
                            <th>Order No.</th>
                            <?php if($column_counter != $column_counter_max): ?>
                                <th><?php echo (strtolower($column['header'])=='balance') ? 'amount' : $column['header']; ?></th>                            
                            <?php endif; ?>
                        <?php elseif($column_counter == 5): ?>
                            <th>Expiry Date</th>
                        <?php else: ?>
                            <?php if($column_counter != $column_counter_max): ?>
                                <th><?php echo (strtolower($column['header'])=='balance') ? 'amount' : $column['header']; ?></th>
                            <?php else: ?>
                                <!-- <th colspan="2"><?php echo $column['header'] ?></th> -->
                            <?php endif; ?>
                        <?php endif; ?>
                        
                    <?php endforeach ?>                    
                </tr>
                <?php if ($this->getData('add_searchable_row')): ?>
                    <!-- <tr class="giftvoucher-grid-search">
                        <?php foreach ($columns as $id => $column): ?>
                            <th>
                                
                                <span class="giftvoucher-grid-title-hidden"><?php echo $column['header'] ?></span>
                                <span class="giftvoucher-grid-detail">
                                    
                                    <?php if (isset($column['searchable'])): ?>
                                        <div class="giftvoucher-grid-search-item"<?php if (isset($column['width']) && $column['width']): ?> style="width:<?php echo $column['width'] ?>;"<?php endif ?>>
                                            <?php $type = isset($column['type']) ? $column['type'] : '' ?>
                                            <?php if ($type == 'date' || $type == 'datetime'): ?>
                                                <div class="range-container">
                                                    <div class="data-range from-date">
                                                        <span class="label"><?php echo $this->__('From') ?>:</span>
                                                        <input type="text" name="<?php echo $id ?>-from" id="<?php echo $this->getNameInLayout() . '-' . $id ?>-from" class="search-item input-text range-text" value="<?php echo $this->getFilterValue($id, '-from') ?>" />
                                                        <img src="<?php echo Mage::getBaseUrl('skin') ?>/adminhtml/default/default/images/grid-cal.gif" alt="<?php echo $this->__('dateinput') ?>" class="v-middle" id="calendar-<?php echo $id ?>-from" />
                                                    </div>
                                                    <div class="data-range to-date">
                                                        <span class="label"><?php echo $this->__('To') ?>:</span>
                                                        <input type="text" name="<?php echo $id ?>-to" id="<?php echo $this->getNameInLayout() . '-' . $id ?>-to" class="search-item input-text range-text" value="<?php echo $this->getFilterValue($id, '-to') ?>" />
                                                        <img src="<?php echo Mage::getBaseUrl('skin') ?>/adminhtml/default/default/images/grid-cal.gif" alt="<?php echo $this->__('dateinput') ?>" class="v-middle" id="calendar-<?php echo $id ?>-to" />
                                                    </div>
                                                    <script type="text/javascript">
                                                        Calendar.setup({
                                                            inputField: "<?php echo $this->getNameInLayout() . '-' . $id ?>-from",
                                                            ifFormat: "%m/%e/%y",
                                                            showsTime: false,
                                                            button: "calendar-<?php echo $id ?>-from",
                                                            align: "Bl",
                                                            singleClick: true
                                                        });
                                                        Calendar.setup({
                                                            inputField: "<?php echo $this->getNameInLayout() . '-' . $id ?>-to",
                                                            ifFormat: "%m/%e/%y",
                                                            showsTime: false,
                                                            button: "calendar-<?php echo $id ?>-to",
                                                            align: "Bl",
                                                            singleClick: true
                                                        });
                                                    </script>
                                                </div>
                                            <?php elseif ($type == 'options'): ?>
                                                <select name="<?php echo $id ?>" id="<?php echo $this->getNameInLayout() . '-' . $id ?>" class="search-item input-select">
                                                    <option value=""></option>
                                                    <?php foreach ($column['options'] as $value => $label): ?>
                                                        <option value="<?php echo $value ?>"<?php if ($value == $this->getFilterValue($id)): ?> selected="selected"<?php endif ?>><?php echo $label ?></option>
                                                    <?php endforeach ?>
                                                </select>
                                            <?php elseif ($type == 'price' || $type == 'baseprice'): ?>
                                                <div class="range-container">
                                                    <div class="data-range from-price">
                                                        <span class="label"><?php echo $this->__('From') ?>:</span>
                                                        <input type="text" name="<?php echo $id ?>-from" id="<?php echo $this->getNameInLayout() . '-' . $id ?>-from" class="search-item input-text range-text" value="<?php echo $this->getFilterValue($id, '-from') ?>" />
                                                    </div>
                                                    <div class="data-range to-price">
                                                        <span class="label"><?php echo $this->__('To') ?>:</span>
                                                        <input type="text" name="<?php echo $id ?>-to" id="<?php echo $this->getNameInLayout() . '-' . $id ?>-to" class="search-item input-text range-text" value="<?php echo $this->getFilterValue($id, '-to') ?>" />
                                                    </div>
                                                </div>
                                            <?php else: ?>
                                                <input type="text" name="<?php echo $id ?>" id="<?php echo $this->getNameInLayout() . '-' . $id ?>" class="search-item input-text search-text" value="<?php echo $this->getFilterValue($id) ?>" />
                                            <?php endif ?>
                                        </div>				
                                    <?php endif ?>
                                </span>
                            </th>
                        <?php endforeach ?>
                    </tr> -->
                <?php endif ?>
            </thead>
            <tbody>
                <?php if ($collection->count()): ?>
                    <?php foreach ($collection as $row): ?>
                        <?php if ($row->getIsContinueNextRow()) continue; ?>
                        <?php
                        $customer = Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getCustomerId());
                        ?>
                        <tr <?php if (($row->getCustomerCheckId() == $customer->getId() || $row->getCustomerEmail() == $customer->getEmail() ) && $row->getRecipientName()) { ?> class="gift-voucher-sent-friend" <?php } ?>>
                            <?php                                 
                                $column_counter = 0;                                 
                            ?>
                            <?php foreach ($columns as $id => $column): ?>
                                <?php $column_counter++; ?>
                                <?php if($column_counter == 4): ?>
                                    <td>
                                        <?php 
                                        $voucher_id = $row->getCustomerVoucherId();
                                        $giftCard = Mage::getBlockSingleton('giftvoucher/view')->getGiftVoucher($voucher_id);
                                        $_history = Mage::getBlockSingleton('giftvoucher/view')->getGiftCardHistory($giftCard);
                                        ?>
                                        <?php if(count($_history) > 0): ?>
                                        <p class="giftvoucher-grid-detail">
                                            <?php foreach ($_history as $_item): ?>         
                                                <?php if ($_item->getOrderIncrementId()): ?>                                
                                                    <?php echo $_item->getOrderIncrementId() ?>
                                                <?php else: ?>
                                                    <?php echo $this->__('N/A') ?>
                                                <?php endif ?>
                                            <?php endforeach; ?>
                                        </p>
                                        <?php endif; ?>
                                    </td>
                                <?php endif; ?>

                                <?php if($id !== 'action'): ?>
                                    <td class="<?php echo $id; ?>">
                                
                             
                                
                                

                                    <!--add by Sally-->
                                    <span class="giftvoucher-grid-title-hidden"><?php echo $column['header'] ?></span>
                                    <p class="giftvoucher-grid-detail">
                                        <!--end by Sally-->
                                        <?php if (isset($column['render']) && $column['render']): ?>
                                            <?php echo $this->fetchRender($column['render'], $row) ?>
                                        <?php else: ?>
                                            <?php $type = isset($column['type']) ? $column['type'] : '' ?>
                                            <?php switch ($type): 
                                                case 'action': ?>
                                                    <?php $action = $column['action'] ?>
                                                    <a href="<?php echo $this->getUrl($action['url'], array($action['name'] => $row->getData($action['field']))) ?>" title="<?php echo $action['label'] ?>"><?php echo $action['label'] ?></a>
                                                    <?php
                                                    break;
                                                case 'options':
                                                    ?>
                                                    <?php echo $column['options'][$row->getData($column['index'])] ?>
                                                    <?php
                                                    break;
                                                case 'date':
                                                    ?>
                                                    <!--Hai.Tran-->
                                                    <?php
                                                    if ($row->getData($column['index']))
                                                        //echo $this->formatDate($row->getData($column['index']), $column['format'], false);
                                                        echo $this->formatDate($row->getData($column['index']), 'short', false);
                                                    else
                                                        echo $this->__('Permanent');
                                                    ?>
                                                    <?php
                                                    break;
                                                case 'datetime':
                                                    ?>
                                                    <?php echo $this->formatDate($row->getData($column['index']), $column['format'], true) ?>
                                                    <?php
                                                    break;
                                                case 'price':
                                                    ?>
                                                    <?php echo Mage::app()->getStore()->formatPrice($row->getData($column['index'])) ?>
                                                    <?php
                                                    break;
                                                case 'baseprice':
                                                    ?>
                                                    <?php echo Mage::helper('core')->currency($row->getData($column['index'])) ?>
                                                    <?php
                                                    break;
                                                default:
                                                    ?>
                                                    <?php echo $row->getData($column['index']) ?>
                                            <?php endswitch ?>
                                        <?php endif ?>
                                    </p><!--edit by Sally-->
                                </td>
                                <?php else: ?>
                                    <!-- <td class="<?php echo $id; ?>"></td> -->
                                <?php endif; ?>
                            <?php endforeach ?>                            
                        </tr>
                    <?php endforeach ?>
                <?php else: ?>
                    <tr>
                        <td colspan="<?php echo count($columns) ?>">
                            <p>
                                <?php echo $this->__('There are no items matching this selection.') ?>
                            </p>
                        </td>
                    </tr>
                <?php endif ?>
            </tbody>
        </table>
    </div>
</div>





<!-- 
     __  __  ___  ____ ___ _     _____    ____ ___ _____ _____    ____    _    ____  ____    _____  _    ____  _     _____ 
    |  \/  |/ _ \| __ )_ _| |   | ____|  / ___|_ _|  ___|_   _|  / ___|  / \  |  _ \|  _ \  |_   _|/ \  | __ )| |   | ____|
    | |\/| | | | |  _ \| || |   |  _|   | |  _ | || |_    | |   | |     / _ \ | |_) | | | |   | | / _ \ |  _ \| |   |  _|  
    | |  | | |_| | |_) | || |___| |___  | |_| || ||  _|   | |   | |___ / ___ \|  _ <| |_| |   | |/ ___ \| |_) | |___| |___ 
    |_|  |_|\___/|____/___|_____|_____|  \____|___|_|     |_|    \____/_/   \_\_| \_\____/    |_/_/   \_\____/|_____|_____|
                                                                                                                           
 -->


<div class="visible-xs-block visible-sm-block">
    <div class="table-responsive">
        <table id="gift-cards-tbl" cellspacing="0" class="data-table linearize-table">
            <thead>
                <tr class="giftvoucher-grid-title">
                    <th>Gift Card Code</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($collection->count()): ?>
                    <?php foreach ($collection as $row): ?>
                        <?php if ($row->getIsContinueNextRow()) continue; ?>
                        <?php
                        $customer = Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getCustomerId());
                        ?>
                        <tr <?php if (($row->getCustomerCheckId() == $customer->getId() || $row->getCustomerEmail() == $customer->getEmail() ) && $row->getRecipientName()) { ?> class="gift-voucher-sent-friend" <?php } ?>>
                            <?php foreach ($columns as $id => $column): ?>

                                <?php //echo $column['header']; ?>

                                <?php if( $column['header'] == 'Action' || $column['header'] == 'Gift Card Code' || $column['header'] == 'Balance' || $column['header'] == 'Status'): ?>
                                    
                                    <td>
                                        <span class="giftvoucher-grid-title-hidden"><?php echo $column['header'] ?></span>
                                        <p class="giftvoucher-grid-detail">
                                            <?php if (isset($column['render']) && $column['render']): ?>
                                                <?php echo $this->fetchRender($column['render'], $row) ?>
                                            <?php else: ?>
                                                <?php $type = isset($column['type']) ? $column['type'] : '' ?>
                                                <?php switch ($type): case 'action': ?>
                                                        <?php $action = $column['action'] ?>
                                                        <a href="<?php echo $this->getUrl($action['url'], array($action['name'] => $row->getData($action['field']))) ?>" title="<?php echo $action['label'] ?>" class="square-cta"><?php echo $action['label'] ?></a>
                                                        <?php
                                                        break;
                                                    case 'options':
                                                        ?>
                                                        <?php echo $column['options'][$row->getData($column['index'])] ?>
                                                        <?php
                                                        break;
                                                    case 'date':
                                                        ?>

                                                        <?php
                                                        if ($row->getData($column['index']))
                                                            echo $this->formatDate($row->getData($column['index']), $column['format'], false);
                                                        else
                                                            echo $this->__('Permanent');
                                                        ?>
                                                        <?php
                                                        break;
                                                    case 'datetime':
                                                        ?>
                                                        <?php echo $this->formatDate($row->getData($column['index']), $column['format'], true) ?>
                                                        <?php
                                                        break;
                                                    case 'price':
                                                        ?>
                                                        <?php echo Mage::app()->getStore()->formatPrice($row->getData($column['index'])) ?>
                                                        <?php
                                                        break;
                                                    case 'baseprice':
                                                        ?>
                                                        <?php echo Mage::helper('core')->currency($row->getData($column['index'])) ?>
                                                        <?php
                                                        break;
                                                    default:
                                                        ?>
                                                        <?php echo $row->getData($column['index']) ?>
                                                <?php endswitch ?>
                                            <?php endif ?>
                                        </p>
                                    </td>
                                <?php endif; ?>

                            <?php endforeach ?>                            
                        </tr>
                    <?php endforeach ?>
                <?php else: ?>
                    <tr>
                        <td colspan="<?php echo count($columns) ?>">
                            <p>
                                <?php echo $this->__('There are no items matching this selection.') ?>
                            </p>
                        </td>
                    </tr>
                <?php endif ?>
            </tbody>
        </table>
    </div>
</div>








<?php echo $this->getPagerHtml() ?>

<div class="space100"></div>
