<?php
/**
 * Miragedesign Web Development
 *
 * @category    Miragedesign
 * @package     Miragedesign_Importcustomiser
 * @copyright   Copyright (c) 2011 Miragedesign (http://miragedesign.net)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $width = ($this->getWidth())? $this->getWidth():'300px';?>
<div class="f-right">
    <a class="link-store-scope" style="margin:2px;cursor:pointer" onclick="Dialog.alert('<?php echo $this->jsQuoteEscape($this->htmlEscape($this->getMessage()))?>', {className:'magento',height:'auto',width:'<?php echo $width?>',okLabel: '<?php echo Mage::helper('importcustomiser')->__('OK! Got it.')?>', buttonClass: 'scalable',id: '<?php echo md5($this->getMessage())?>', title: '<?php echo $this->jsQuoteEscape($this->htmlEscape($this->getTitle()))?>'});return false;">
    </a>
</div>