<div class="form-group">
    <div class="row">
        <div class="col-md-4">
            <label for="<?php echo $this->getFieldId('firstname')?>" class="required"><?php echo $this->getStoreLabel('firstname') ?><em>*</em></label>
        </div>
        <div class="col-md-8">
            <input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" value="<?php echo $this->escapeHtml($this->getObject()->getFirstname()) ?>" title="<?php echo $this->getStoreLabel('firstname') ?>" maxlength="255" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('firstname') ?>" <?php echo $this->getFieldParams() ?> />        
        </div>
    </div>
</div>