<div class="form-group">
    <div class="row">
        <div class="col-md-4">
            <label for="<?php echo $this->getFieldId('lastname')?>" class="required"><?php echo $this->getStoreLabel('lastname') ?><em>*</em></label>        
        </div>
        <div class="col-md-8">
            <input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" value="<?php echo $this->escapeHtml($this->getObject()->getLastname()) ?>" title="<?php echo $this->getStoreLabel('lastname') ?>" maxlength="255" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('lastname') ?>" <?php echo $this->getFieldParams() ?> />        
        </div>
    </div>
</div>