<?php
$_product = $this->getProduct();
if ($_product->getTypeId() == 'giftvoucher'):
    ?>
    <?php
    /**
     * Gift Voucher View Product template
     */
    $templates = $this->getAvailableTemplate();
    $_formData = Mage::getBlockSingleton('giftvoucher/product_view')->getFormConfigData();
    $enableCustomDesign = Mage::helper('giftvoucher')->getInterfaceConfig('custom_image');
    $tick_img = $this->getskinUrl('images/content/design_01_ticked.png');
    if (count($templates)):
        ?>
        <div class="each-input">
            <script>
                var image_old;
                var image_count;
                var template_show_id;
                var template_id;
                var urlUploadImage = '';
                var giftcard_prev = 0;
                var giftcard_next = 4;
            </script>
            
            <?php if (count($templates) == 1): ?>
                <label for="giftcard_template_select" ><?php echo $this->__('DESIGN OPTIONS ') ?></label>
            <?php else: ?>
                <label for="giftcard_template_select" ><?php echo $this->__('Select a template ') ?></label>
            <?php endif; ?>
            <select <?php if (count($templates) == 1) echo 'hidden'; ?> id="giftcard_template_select" name="giftcard_template_id" class="select" style="width: 165px;" onchange="changeTemplate(this);">

                <?php foreach ($templates as $template): ?>
                    <option value="<?php echo $template['giftcard_template_id'] ?>" <?php if ($_formData->getGiftcardTemplateId() == $template['giftcard_template_id']) echo 'selected' ?>><?php echo $template['template_name'] ?></option>
                <?php endforeach; ?>
            </select>
            <input type="hidden" name="giftcard_template_image" id="giftcard-template-images" value="<?php echo $_formData->getGiftcardTemplateImage() ? $_formData->getGiftcardTemplateImage() : '0' ?>" />
            <div id="giftcard-template-show-images" style="display: inline-block; width: auto!important;">
                <div id="giftcard-template-prev" style="filter:alpha(opacity=30);opacity: 0.3;z-index: 10;position: absolute;cursor: pointer; left: 0; top: 7px; width: 20px; height: 62px;" onclick="giftcardPrevImage();"></div>
                <?php foreach ($templates as $template): ?>
                    <div id="image-for-<?php echo $template['giftcard_template_id'] ?>" style="/*display:none*/">
                        <?php
                        $count = 0;
                        if (!$template['images'])
                            $template['images'] = 'default.png'; //07.01
                        if ($template['images']) {
                            $images = explode(',', $template['images']);
                            $maxCount = count($images) - 1;
                            if ($template['design_pattern'] == Magestore_Giftvoucher_Model_Designpattern::PATTERN_TOP) {
                                $image_url_position = 'top/';
                                $image_type_show_width = '68';
                                $image_type_show_height = '18';
                                $image_type_show_padding = '16px';
                            } elseif ($template['design_pattern'] == Magestore_Giftvoucher_Model_Designpattern::PATTERN_CENTER) {
                                $image_url_position = '';
                                $image_type_show_width = '68';
                                $image_type_show_height = '50';
                                $image_type_show_padding = '0';
                            } else {
                                $image_url_position = 'left/';
                                $image_type_show_width = 'auto';
                                $image_type_show_height = '50';
                                $image_type_show_padding = '0';
                            }
                            foreach ($images as $image) {
                                if ($count % 4 == 0) {
                                    echo '<div id="div-bound-' . $template['giftcard_template_id'] . '-' . $count . '" style="display:none">';
                                }
                                // $url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/' . $image_url_position . $image;
                                $no = $count;
                                $no += 1;
                                $url = $this->getskinUrl('images/giftcard-designs/design_0'.$no.'.png');                                
                                echo '<div id="div-image-for-' . $template['giftcard_template_id'] . '-' . $count . '" class="design-radio" style="" onclick="changeSelectImages(' . $count . ')">';
                                    echo '<div class="radio-image">';
                                        echo '<img id="image-for-' . $template['giftcard_template_id'] . '-' . $count . '" src="' . $url . '" width=' . $image_type_show_width . ' height=' . $image_type_show_height . ' alt="image giftcard" style="display:inline; border: 1px solid white; margin-top: ' . $image_type_show_padding . '">';
                                        echo '<img src="'.$tick_img.'" class="selected egcSwatch-arrow" style="display:none">';
                                    echo '</div>';
                                echo '</div>';
                                if ($image == $_formData->getGiftcardTemplateImage() && $_formData->getGiftcardTemplateId() == $template['giftcard_template_id']) {
                                    echo '<script type="text/javascript">$("div-bound-' . $template['giftcard_template_id'] . '-' . ($count - $count % 4) . '").show(); giftcard_prev = ' . ($count - $count % 4) . '; giftcard_next = ' . ($count - $count % 4 + 4) . '; image_form_data = ' . $count . ';</script>';
                                }
                                $count+=1;
                                if ($count % 4 == 0 || $count > $maxCount)
                                    echo '</div>';
                            }
                        }
                        ?>
                    </div>
                <?php endforeach; ?>
                <div id="giftcard-template-next" style="filter:alpha(opacity=30);opacity: 0.3;z-index: 10;cursor: pointer;position: absolute; right: 0; top: 7px; padding-right: 13px; width: 20px; height: 62px;" onclick="giftcardNextImage();"></div>
            </div>

            <div id="giftcard-template-upload-images" style="margin-top: 10px; display:none;">
                <?php echo $this->getChildHtml('giftcard.uploadimage') ?>
            </div>

            <script>
                var url_image_position;
                var templates = <?php echo Mage::helper('core')->jsonEncode($templates) ?>;
                var design_top = '<?php echo Magestore_Giftvoucher_Model_Designpattern::PATTERN_TOP ?>';
                var design_left = '<?php echo Magestore_Giftvoucher_Model_Designpattern::PATTERN_LEFT ?>';
                var design_back = '<?php echo Magestore_Giftvoucher_Model_Designpattern::PATTERN_CENTER ?>';
            <?php if ($_formData->getGiftcardUseCustomImage()): ?>
                    image_form_data_name = '<?php echo $_formData->getGiftcardTemplateImage() ?>';
            <?php endif; ?>

                /**
                 * change select template
                 */
                function changeTemplate(el) {
                    template_id = getTemplateById(el.value);
                    if (typeof template_show_id != 'undefined')
                        $(template_show_id).hide();
                    if (templates[template_id].design_pattern == design_top)
                        template_show_id = 'giftcard-template-top';
                    else if (templates[template_id].design_pattern == design_left)
                        template_show_id = 'giftcard-template-left';
                    else
                        template_show_id = 'giftcard-template-back';
                    $(template_show_id).show();

                    templateShow = templates[template_id];
                    $(template_show_id).down('.giftcard-title').innerHTML = templateShow.caption;

                    if ($('giftcard-notes-top'))
                        $('giftcard-notes-top').hide();
                    if ($('giftcard-notes-left'))
                        $('giftcard-notes-left').hide();
                    if ($('giftcard-notes-center'))
                        $('giftcard-notes-center').hide();
                    if (templateShow.design_pattern == design_top) {
                        url_image_position = 'top/';
                        if ($('giftcard-notes-top'))
                            $('giftcard-notes-top').show();
                    }
                    else if (templateShow.design_pattern == design_back) {
                        url_image_position = '';
                        if ($('giftcard-notes-center'))
                            $('giftcard-notes-center').show();
                    }
                    else {
                        url_image_position = 'left/';
                        if ($('giftcard-notes-left'))
                            $('giftcard-notes-left').show();
                    }

                    if (templateShow.background_img)
                        background_img = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/background/'; ?>' + url_image_position + templateShow.background_img;
                    else
                        background_img = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/background/'; ?>' + url_image_position + 'default.png';
                    if (templateShow.style_color)
                        style_color = templateShow.style_color;
                    else
                        style_color = 'orange';
                    if (templateShow.text_color)
                        text_color = templateShow.text_color;
                    else
                        text_color = '#2f2f2f';

                    $(template_show_id).down('.giftcard-template-content').style.backgroundImage = 'url(' + background_img + ')';
                    if (templates[template_id].notes != null)
                        $(template_show_id).down('p.giftcard-text-color').innerHTML = templates[template_id].notes;

                    $$('#' + template_show_id + ' .giftcard-style-color').each(function(el) {
                        el.style.color = style_color;
                    });
                    $$('#' + template_show_id + ' .giftcard-text-color').each(function(el) {
                        el.style.color = text_color;
                    });

                    if (typeof image_for_old != 'undefined')
                        $(image_for_old).hide();
                    //image_for_old = 'image-for-'+templates[template_id].giftcard_template_id;
                    if (typeof image_form_data === 'undefined')
                        image_for_old = 'div-bound-' + templates[template_id].giftcard_template_id + '-0';
                    else
                        image_for_old = 'div-bound-' + templates[template_id].giftcard_template_id + '-' + (image_form_data - image_form_data % 4);
                    if (typeof image_form_data === 'undefined') {
                        giftcard_prev = 0;
                        giftcard_next = 4;
                    }

                    if (templates[template_id].images)
                        count_next_fix = templates[template_id].images.split(',').length;
                    else
                        count_next_fix = 0;

                    if (giftcard_next >= count_next_fix)
                        $('giftcard-template-next').hide();
                    else
                        $('giftcard-template-next').show();
                    if (giftcard_prev <= 0)
                        $('giftcard-template-prev').hide();
                    else
                        $('giftcard-template-prev').show();

                    if (typeof image_form_data === 'undefined') {
                        if ($(image_for_old))
                            $(image_for_old).show();
                        else
                            delete image_for_old;
                    }
                    if (urlUploadImage === '') {
                        if (typeof image_form_data !== 'undefined') {
                            changeSelectImages(image_form_data);
                            delete image_form_data;
                        } else {
                            if (typeof image_form_data_name !== 'undefined') {
                                urlUploadImage = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "tmp/giftvoucher/images/"; ?>' + image_form_data_name;
                                image_upload_name = image_form_data_name;
                                $('image-for-custom').src = urlUploadImage;
                                changeImageDesignAgain($('image-for-custom'));
                                delete image_form_data_name;
                            } else {
                                changeSelectImages(0);
                            }
                        }
                    }
                }
                function getTemplateById(id) {
                    for (i = 0; i < templates.length; i++) {
                        if (templates[i].giftcard_template_id == id)
                            return i;
                    }
                    return 0;
                }
                Event.observe(window, 'load', function() {
                    changeTemplate($('giftcard_template_select'));
                });

                /**
                 * Change select picture
                 */
                function changeSelectImages(image_id) {
                    if (typeof image_old != 'undefined') {
                        $('div-' + image_old).removeClassName('gift-active');
                        $('div-' + image_old).down('.egcSwatch-arrow').hide();
                    }
                    if (typeof urlUploadImage != 'undefined') {
                        $('div-image-for-custom').down('.egcSwatch-arrow').hide();
                        $('div-image-for-custom').removeClassName('gift-active');
                    }
                    if ($('image-for-' + templates[template_id].giftcard_template_id + '-' + image_id)) {
                        image_old = 'image-for-' + templates[template_id].giftcard_template_id + '-' + image_id;
                        $('div-' + image_old).addClassName('gift-active');

                        
                        var first = "<?php echo $this->getskinUrl('images/giftcard-designs/design_01_ticked.png'); ?>";                        
                        var second = "<?php echo $this->getskinUrl('images/giftcard-designs/design_02_ticked.png'); ?>";                        
                        var third = "<?php echo $this->getskinUrl('images/giftcard-designs/design_03_ticked.png'); ?>";                        


                        $('div-image-for-' + templates[template_id].giftcard_template_id + '-' + image_id).down('.egcSwatch-arrow').show();                        

                        if(image_id==0) {                            
                            $('div-image-for-' + templates[template_id].giftcard_template_id + '-' + image_id).down('.egcSwatch-arrow').src = first; 
                            $('gifttext').removeClassName('white');  
                        }else if(image_id==1) {                            
                            $('div-image-for-' + templates[template_id].giftcard_template_id + '-' + image_id).down('.egcSwatch-arrow').src = second; 
                            $('gifttext').addClassName('white');  
                        }else {                            
                            $('div-image-for-' + templates[template_id].giftcard_template_id + '-' + image_id).down('.egcSwatch-arrow').src = third; 
                            $('gifttext').addClassName('white');  
                        }                    
                                        
                        image = $(image_old).src;
                        var url = [];
                        <?php foreach ($images as $i => $image): ?>
                        url[<?php echo $i; ?>] = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/' . $image; ?>";
                        <?php endforeach; ?>

                        image = url[image_id];

                        
                        // console.log(image_id);
                        // console.log(image);

                        $(template_show_id).down('.giftcard-change-image').style.backgroundImage = 'url(' + image + ')';

                        images_tmp = templates[template_id].images;
                        if (images_tmp != null) {
                            images_tmp = images_tmp.split(',');
                            $('giftcard-template-images').value = images_tmp[image_id];
                        }
                        urlUploadImage = '';
                    }
                    $('giftcard-use-custom-image').value = '0';
                }
                /**
                 * Apply template
                 */
                function chooseTemplate() {
                    changeSelectImages(image_count);
                    winPopupPreview.hide()

                }
                function giftcardPrevImage() {
                    if (giftcard_prev == 0)
                        return;
                    if (typeof image_for_old != 'undefined')
                        $(image_for_old).hide();
                    giftcard_prev = giftcard_prev - 4;
                    giftcard_next = giftcard_next - 4;
                    image_for_old = 'div-bound-' + templates[template_id].giftcard_template_id + '-' + giftcard_prev;
                    $(image_for_old).show();
                    if (giftcard_prev == 0)
                        $('giftcard-template-prev').hide();
                    if (giftcard_next < templates[template_id].images.split(',').length)
                        $('giftcard-template-next').show();
                }
                function giftcardNextImage() {
                    if (giftcard_next >= templates[template_id].images.split(',').length)
                        return;
                    if (typeof image_for_old != 'undefined')
                        $(image_for_old).hide();
                    giftcard_next = giftcard_next + 4;
                    giftcard_prev = giftcard_prev + 4;
                    image_for_old = 'div-bound-' + templates[template_id].giftcard_template_id + '-' + giftcard_prev;
                    $(image_for_old).show();
                    if (giftcard_next >= templates[template_id].images.split(',').length)
                        $('giftcard-template-next').hide();
                    if (giftcard_prev > 0)
                        $('giftcard-template-prev').show();
                }
            </script>
            <!--End our designs-->
            <div class="divider"></div>
            <!--<div style="clear: both"></div>-->
        </div>
    <?php endif; ?>
<?php endif; ?>