call compile_page_libraries.bat
call compile_page_default.bat
call compile_page_home.bat
call compile_page_product_detail.bat
call compile_page_checkout.bat
call compile_page_account.bat
call compile_page_our_teas.bat