<?php 
$posts = Mage::getResourceModel('wordpress/post_collection')->addPostTypeFilter('post');
$posts->addPostParentIdFilter(0);
$posts = $posts->addIsViewableFilter()->load();
$post_data = $posts->getData();
$i = 1;
?>
<?php foreach ($posts as $key => $post): ?>	
	<?php if($i<=2): ?>
	<?php $post->setExcerptSize(200) ?>
	<div class="post">
		<span class="date"><?php echo $post->getPostDate() ?></span>
		<h2><?php echo $post->getPostTitle(); ?></h2>
		<p><?php $content = $post->getPostExcerpt(); $content = strip_tags($content); echo substr($content, 0, 150); ?> ...</p>
		<a href="<?php echo Mage::getBaseUrl(); ?>blog/?p=<?php echo $post->getId() ?>" class="cta read-more"><i class="my-arrow-right"></i> Read more</a>
	</div>
	<?php $i++; ?>
	<?php endif; ?>
<?php endforeach; ?>