<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div id="content-wrapper" class="blog">
	<div class="blog-banner">
		<div class="image-text-content container">
			<div class="row">
				<div class="col-md-12 caption-container">
					<div class="caption">
						<h1>How to start a day with <br> Gryphon tea</h1>
						<a href="store.html" class="read-more cta">Visit Tea Store</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="main-content">
		<div class="image-text-content container">
			<div class="row">
				<div class="col-md-9">					
					<?php echo $this->getPostListHtml() ?>					
				</div>
				<div class="col-md-3">	
									
				</div>
			</div>
		</div>
	</div>
</div>