<?php
/**
 * View Gift Card
 */
?>

<?php $_giftCard = $this->getGiftVoucher() ?>
<?php $_history = $this->getGiftCardHistory($_giftCard) ?>

<div class="page-title">
    <h1><?php echo $this->__('Gift Card Code Details') ?></h1>
</div>

<?php echo $this->getChildHtml('giftvoucher.basic') ?>

<?php if (count($_history)): ?>
    <div class="page-title">
        <h3><?php echo $this->__('History') ?></h3>
    </div>

    <table class="data-table" id="giftcard_history_table">
        <thead>
            <tr>
                <th><?php echo $this->__('Action') ?></th>
                <th><?php echo $this->__('Balance') ?></th>
                <th><?php echo $this->__('Date') ?></th>
                <th><?php echo $this->__('Balance Change') ?></th>
                <th><?php echo $this->__('Order') ?></th>
                <th><?php echo $this->__('Comments') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_history as $_item): ?>
                <tr>

                    <td>
                        <span class="item-hidden"><?php echo $this->__('Action') ?></span>
                        <span class="item-detail"><?php echo $this->getActionName($_item) ?></span>
                    </td>
                    <td>
                        <span class="item-hidden"><?php echo $this->__('Balance') ?></span>
                        <span class="item-detail">
                            <?php if (is_null($_item->getBalance())): ?>
                                <?php echo $this->__('N/A') ?>
                            <?php else: ?>
                                <?php echo $this->getBalanceFormat($_item) ?>
                            <?php endif ?>
                        </span>
                    </td>
                    <td>
                        <span class="item-hidden"><?php echo $this->__('Date') ?></span>
                        <span class="item-detail"><?php echo $this->formatDate($_item->getCreatedAt(), 'medium') ?></span>
                    </td>
                    <td>
                        <span class="item-hidden"><?php echo $this->__('Balance Change') ?></span>
                        <span class="item-detail"><?php echo $this->getAmountFormat($_item) ?></span>
                    </td>
                    <td>
                        <span class="item-hidden"><?php echo $this->__('Order') ?></span>
                        <span class="item-detail">
                            <?php if ($_item->getOrderIncrementId()): ?>
                                <a href="<?php echo $this->getUrl('sales/order/view', array('order_id' => $_item->getOrderId())) ?>" title="<?php echo $this->__('View Order') ?>"><?php echo $_item->getOrderIncrementId() ?></a>
                            <?php else: ?>
                                <?php echo $this->__('N/A') ?>
                            <?php endif ?>
                        </span>
                    </td>
                    <td>
                        <span class="item-hidden"><?php echo $this->__('Comments') ?></span>
                        <span class="item-detail">
                            <?php
                            //Hai.Tran
                            if ($_item->getCustomerId() == Mage::getSingleton('customer/session')->getCustomerId()) {
                                echo $_item->getComments();
                            } else {
                                $email_history = $_item->getCustomerEmail();
                                if ($email_history)
                                    echo $_item->getExtraContent() . ' (' . $email_history . ')';
                                else
                                    echo $_item->getExtraContent() != null ? $_item->getExtraContent() : $_item->getComments();
                            }
                            ?>
                        </span>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <script type="text/javascript">
        decorateTable('giftcard_history_table');
    </script>
<?php endif ?>

<div class="buttons-set">
    <p class="back-link">
        <a href="#" onclick="setLocation('<?php echo $this->getUrl('*/*/index') ?>');
                return false;">
            <small>« </small>
            <?php echo $this->__('Back') ?>
        </a>
    </p>
    <?php if ($this->checkSendFriendGiftCard($_giftCard)): ?>
        <button type="button" class="button" onclick="setLocation('<?php echo $this->getUrl('*/*/email', array('id' => $this->getCustomerGift()->getId())) ?>')">
            <span>
                <span><?php echo $this->__('Email to Friend') ?></span>
            </span>
        </button>
    <?php endif ?>
    <?php
    if ($_giftCard->getStatus() == Magestore_Giftvoucher_Model_Status::STATUS_ACTIVE && Mage::helper('giftvoucher')->getGeneralConfig('enablecredit')
    ):
        ?>
        <button type="button" class="button" onclick="redeemGiftCard()">
            <span>
                <span><?php echo $this->__('Redeem') ?></span>
            </span>
        </button>
        <script type="text/javascript">
            function redeemGiftCard() {
                if (confirm('<?php echo $this->__('Are you sure?') ?>')) {
                    setLocation('<?php echo $this->getUrl('*/*/redeem', array('giftvouchercode' => $_giftCard->getGiftCode())) ?>');
                }
            }
        </script>
    <?php endif ?>
</div>