<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
<div id="monogram-page-account-mobile-header" class="visible-sm visible-xs">
  <h4>membership services</h4>
  <h2>Rebate History</h2>
</div>

<div id="monogram-page-account-reward-points-container">

  <div class="my-account reward-page">
      <div class="page-title">
          <h1><?php echo $this->__('Rebate History') ?></h1>
          <hr class="small">
      </div>

      <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
      <?php echo $this->getChildHtml('points') ?>
      
      <!--
      <div class="page-title">
          <h1><?php echo $this->__('History') ?></h1>
          <hr class="small">
      </div>
      -->

      <?php $_points = $this->getPoints();?>
      <?php if($_points->getSize()): ?>
          <?php //echo $this->getPagerHtml() ?>

          <div class="visible-md-block visible-lg-block">
              <div class="table-responsive">
                  <table cellspacing="0" class="data-table linearize-table" id="reward-points-table">
                      <thead>
                          <tr>
                              <?php ?><th><?php echo $this->__('Description') ?></th><?php ?>
                              <th><?php echo $this->__('Rebates added') ?></th>
                              <th><?php echo $this->__('Rebates used') ?></th>
                              <th><?php echo $this->__('Added Date') ?></th>
                              <th><?php echo $this->__('Valid until') ?></th>
                          </tr>
                      </thead>
                      <tbody>
                          <?php $_odd = ''; ?>
                          <?php foreach ($_points as $_point): ?>
                              <?php $pointData = $_point->getData(); ?>
                              <tr class="<?php print_r($pointData); ?>">
                                  <td data-theme-label="<?php echo $this->__('Type of point') ?>">
                                      <?php echo $this->getTypeOfPoint($_point);?>
                                  </td>
                                  <td data-theme-label="<?php echo $this->__('Rebates added') ?>"><?php echo $_point->getPoints_current() ?></td>
                                  <?php /*?><?php echo $_point->getPoints_spent() ? $this->__('yes') : $this->__('no') ?><?php */?>
                                  <td data-theme-label="<?php echo $this->__('Rebates used') ?>"><?php echo $_point->getPoints_spent() ?></td>
                                  <?php /*?><td><?php if ($_point->getDate_start() != ""): echo $this->formatDate($_point->getDate_start(), 'short'); endif; ?></td>
                                  <td><?php if ($_point->getDate_end() != ""): echo $this->formatDate($_point->getDate_end(), 'short'); endif; ?></td>
                                  <?php */?>
                                      
                                  <td data-theme-label="<?php echo $this->__('Allocation date') ?>"><?php if ($_point->getDate_start() != ""): echo $this->formatDate($_point->getDate_start(), 'short'); else: echo $this->formatDate($_point->getDate_insertion(), 'short'); endif; ?></td>
                                  <td data-theme-label="<?php echo $this->__('Valid until') ?>"><?php if ($_point->getDate_end() != ""): echo $this->formatDate($_point->getDate_end(), 'short'); endif; ?></td>
                              </tr>
                          <?php endforeach; ?>
                      </tbody>
                  </table>
              </div>
              
          </div>
          <div class="visible-xs-block visible-sm-block">
              <div class="table-responsive">
                  <table cellspacing="0" class="data-table linearize-table" id="reward-points-table">
                      <thead>
                          <tr>
                              <?php ?><th><?php echo $this->__('Description') ?></th><?php ?>
                              <th><?php echo $this->__('Rebates added') ?></th>
                              <th><?php echo $this->__('Valid Until') ?></th>
                          </tr>
                      </thead>
                      <tbody>
                          <?php $_odd = ''; ?>
                          <?php foreach ($_points as $_point): ?>
                              <?php $pointData = $_point->getData(); ?>
                              <tr>
                                  <td data-theme-label="<?php echo $this->__('Type of point') ?>">
                                      <?php echo $this->getTypeOfPoint($_point);?>
                                  </td>
                                  <td data-theme-label="<?php echo $this->__('Rebate added') ?>"><?php echo $_point->getPoints_current() ?></td>
                                  <td data-theme-label="<?php echo $this->__('Valid until') ?>"><?php if ($_point->getDate_end() != ""): echo $this->formatDate($_point->getDate_end(), 'short'); endif; ?></td>
                              </tr>
                          <?php endforeach; ?>
                      </tbody>
                  </table>
              </div>
          </div>
          <?php echo $this->getPagerHtml() ?>
      <?php else: ?>
          <p><?php echo $this->__('You don\'t have any recorded points.'); ?></p>
      <?php endif ?>
  </div>



</div> <!-- #monogram-page-account-reward-points-container -->