<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>

 <script>
   $j("body").addClass("account-rebate-history-page");
 </script>

<!--
   _____ ___ _____ _     _____
  |_   _|_ _|_   _| |   | ____|
    | |  | |  | | | |   |  _|
    | |  | |  | | | |___| |___
    |_| |___| |_| |_____|_____|

-->

<article id="page-account-title-section">
  <div class="container-fluid has-breakpoint">
    <div class="row">
      <div class="col-md-3 col-sm-1 col-xs-0"></div>
      <div class="col-md-9 col-sm-10 col-xs-12">
        <div id="page-account-title">
          <h1><?php echo $this->__('My Rebate History.') ?></h1>
        </div> <!-- page-account-title -->
      </div>
    </div>
  </div>
</article> <!-- page-account-title-section -->

<!--
    ____ ___  _   _ _____ _____ _   _ _____
   / ___/ _ \| \ | |_   _| ____| \ | |_   _|
  | |  | | | |  \| | | | |  _| |  \| | | |
  | |__| |_| | |\  | | | | |___| |\  | | |
   \____\___/|_| \_| |_| |_____|_| \_| |_|

-->

<article id="page-account-rebate-history-header-nav-mobile-section" class="visible-xs">
  <div id="page-account-rebate-history-header-nav-mobile">
    <ul>
      <li data-value="earned" class="selected"><a href="#earned">Earned</a></li>
      <li data-value="redeemed"><a href="#redeemed">Redeemed</a></li>
      <li data-value="expired"><a href="#expired">Expired</a></li>
    </ul>
  </div>
</article>

<article id="page-account-content-section">
  <div id="page-account-content-section-bg" class="">
    <div class="sidebar-bg visible-md visible-lg"></div>
    <div class="content-bg"></div>
  </div>

  <div class="container-fluid has-breakpoint">
    <div class="row">

      <div class="col-md-2 col-tablet-landscape-2 hidden-sm hidden-xs">

        <!--
           ____ ___ ____  _____ ____    _    ____
          / ___|_ _|  _ \| ____| __ )  / \  |  _ \
          \___ \| || | | |  _| |  _ \ / _ \ | |_) |
           ___) | || |_| | |___| |_) / ___ \|  _ <
          |____/___|____/|_____|____/_/   \_\_| \_\

        -->

        <div id="page-account-sidebar-width"></div>
        <div id="page-account-sidebar">
          
          <?php echo $this->getChildHtml('navigation') ?>

        </div> <!-- page-account-sidebar -->

      </div> <!-- col-md-2 -->
      <div class="col-md-0 col-tablet-landscape-0 col-sm-1 col-xs-0"></div>
      <div class="col-md-10 col-tablet-landscape-10 col-sm-10 col-xs-12">

        <!--
            ____ ___  _   _ _____ _____ _   _ _____
           / ___/ _ \| \ | |_   _| ____| \ | |_   _|
          | |  | | | |  \| | | | |  _| |  \| | | |
          | |__| |_| | |\  | | | | |___| |\  | | |
           \____\___/|_| \_| |_| |_____|_| \_| |_|

        -->

        <div id="page-account-content-width"></div>
        <div id="page-account-content">

          <!--
             ____  _____ ____    _  _____ _____   _   _ ___ ____ _____ ___  ______   __
            |  _ \| ____| __ )  / \|_   _| ____| | | | |_ _/ ___|_   _/ _ \|  _ \ \ / /
            | |_) |  _| |  _ \ / _ \ | | |  _|   | |_| || |\___ \ | || | | | |_) \ V /
            |  _ <| |___| |_) / ___ \| | | |___  |  _  || | ___) || || |_| |  _ < | |
            |_| \_\_____|____/_/   \_\_| |_____| |_| |_|___|____/ |_| \___/|_| \_\|_|

          -->

          
          <div id="page-account-rebate-history-header">
            <div class="row">
              <div class="col-md-6">

                <div class="history-header-title hidden-xs">
                  <h2><?php echo $this->__('Rebate History') ?></h2>
                </div>

                <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                <?php echo $this->getChildHtml('points') ?>

              </div>
              <div class="col-md-6 hidden-xs">

                <div class="history-header-nav">
                  <ul>
                    <li data-value="earned" class="selected"><a href="#earned"><?php echo $this->__('Earned') ?></a></li>
                    <li data-value="redeemed"><a href="#redeemed"><?php echo $this->__('Redeemed') ?></a></li>
                    <li data-value="expired"><a href="#expired"><?php echo $this->__('Expired') ?></a></li>
                  </ul>
                </div>

              </div>
            </div>

          </div> <!-- page-account-rebate-history-header -->

          <div id="page-account-rebate-history-content">            

            <?php $_earnedPoints = $this->getEarnedPoints(); ?>
            <?php $_points = $this->getPoints(); ?>
            

              <!--
                 _____    _    ____  _   _ _____ ____
                | ____|  / \  |  _ \| \ | | ____|  _ \
                |  _|   / _ \ | |_) |  \| |  _| | | | |
                | |___ / ___ \|  _ <| |\  | |___| |_| |
                |_____/_/   \_\_| \_\_| \_|_____|____/

              -->

              <div id="page-account-rebate-history-earned-table" class="page-account-table">

                <div class="page-account-table-header">
                  <div class="row">
                    <div class="col-sm-4 col-xs-5">
                      <div class="table-column-first">
                        <h4><?php echo $this->__('Description') ?></h4>
                      </div>
                    </div>
                    <!-- <div class="col-sm-3">
                      <div class="table-column">
                        <h4><?php echo $this->__('Status') ?></h4>
                      </div>
                    </div> -->
                    <div class="col-sm-4 col-xs-3">
                      <div class="table-column">
                        <h4><?php echo $this->__('Rebates earned') ?></h4>
                      </div>
                    </div>
                    <div class="col-sm-4 col-xs-4">
                      <div class="table-column-last">
                        <h4><?php echo $this->__('Expiry date') ?></h4>
                      </div>
                    </div>
                  </div>
                </div> <!-- page-account-table-header -->
                
                <div class="page-account-table-item-container">
                  <?php if($_earnedPoints->getSize()): ?>
                    <?php foreach ($_earnedPoints as $_point): ?>
                      <div class="page-account-table-item">
                        <div class="row">
                          <div class="col-sm-4 col-xs-5">
                            <div class="table-column-first"><!-- data-column="Description" -->
                              <?php echo $this->getTypeOfPoint($_point);?>
                            </div>
                          </div>
                          <!-- <div class="col-sm-3 col-xs-6">
                            <div class="table-column" data-column="Status">
                              <?php 
                              $status_field = Mage::getStoreConfig('rewardpoints/default/status_used', Mage::app()->getStore()->getId());
                              $order_id = $_point->getOrderId();
                              $order = Mage::getModel('sales/order')->loadByIncrementId($order_id);
                              $order_status = $order->getData($status_field);
                              ?>
                              
                              <p><?php echo (!empty($order_status)) ? $order_status : "-" ?></p>
                            </div>
                          </div> -->
                          <div class="col-sm-4 col-xs-3">
                            <div class="table-column"> <!-- data-column="Rebates earned" -->
                              <p><?php echo $_point->getPoints_current() ?></p>
                            </div>
                          </div>
                          <div class="col-sm-4 col-xs-4">
                            <div class="table-column-last mobile-last-version"><!-- data-column="Expiry date" -->
                              <h4><?php if ($_point->getDate_end() != ""): echo $this->formatDate($_point->getDate_end(), 'short'); endif; ?></h4>
                            </div>
                          </div>
                        </div>
                      </div>
                    <?php endforeach; ?>
                  <?php else: ?>
                    <div class="page-account-table-item">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="table-column-first">
                              <p><?php echo $this->__('You don\'t have any recorded rebates.'); ?></p>
                            </div>
                          </div>
                        </div>
                    </div>
                  <?php endif; ?>                 

                </div> <!-- page-account-table-item-container -->

                <?php echo $this->getEarnedPagerHtml() ?>

              </div>

              <!--
                 ____  _____ ____  _____ _____ __  __ _____ ____
                |  _ \| ____|  _ \| ____| ____|  \/  | ____|  _ \
                | |_) |  _| | | | |  _| |  _| | |\/| |  _| | | | |
                |  _ <| |___| |_| | |___| |___| |  | | |___| |_| |
                |_| \_\_____|____/|_____|_____|_|  |_|_____|____/

              -->

              <div id="page-account-rebate-history-redeemed-table" class="page-account-table">

                <div class="page-account-table-header">
                  <div class="row">
                    <div class="col-sm-4 col-xs-5">
                      <div class="table-column-first">
                        <h4><?php echo $this->__('Description') ?></h4>
                      </div>
                    </div>
                    <!-- <div class="col-sm-3">
                      <div class="table-column">
                        <h4><?php echo $this->__('Status') ?></h4>
                      </div>
                    </div> -->
                    <div class="col-sm-4 col-xs-3">
                      <div class="table-column">
                        <h4><?php echo $this->__('Rebates used') ?></h4>
                      </div>
                    </div>
                    <div class="col-sm-4 col-xs-4">
                      <div class="table-column-last">
                        <h4><?php echo $this->__('Redemption date') ?></h4>
                      </div>
                    </div>
                  </div>
                </div> <!-- page-account-table-header -->

                <div class="page-account-table-item-container">
                  
                  <?php $_spentPoints = $this->getSpentPoints(); ?>
                  <?php if($_spentPoints->getSize()): ?>
                    <?php foreach ($_spentPoints as $_point): ?>
                      <div class="page-account-table-item">
                        <div class="row">
                          <div class="col-sm-4 col-xs-5">
                            <div class="table-column-first"><!-- data-column="Description:" -->
                              <?php echo $this->getTypeOfPoint($_point);?>
                            </div>
                          </div>
                          <!-- <div class="col-sm-3 col-xs-4">
                            <div class="table-column" data-column="Status:">
                              <?php 
                              $status_field = Mage::getStoreConfig('rewardpoints/default/status_used', Mage::app()->getStore()->getId());
                              $order_id = $_point->getOrderId();
                              $order = Mage::getModel('sales/order')->loadByIncrementId($order_id);
                              $order_status = $order->getData($status_field);
                              ?>
                              
                              <p><?php echo (!empty($order_status)) ? $order_status : "-" ?></p>
                            </div>
                          </div> -->
                          <div class="col-sm-4 col-xs-3">
                            <div class="table-column"><!-- data-column="Rebates used:" -->
                              <p><?php echo $_point->getPoints_spent() ?></p>
                            </div>
                          </div>
                          <div class="col-sm-4 col-xs-4">
                            <div class="table-column-last mobile-last-version"> <!-- data-column="Redemption date:" -->
                              <h4><?php if ($_point->getDate_start() != ""): echo $this->formatDate($_point->getDate_start(), 'short'); else: echo $this->formatDate($_point->getDate_insertion(), 'short'); endif; ?></h4>
                            </div>
                          </div>
                        </div>
                      </div>
                    <?php endforeach; ?>
                  <?php else: ?>
                    <div class="page-account-table-item">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="table-column-first">
                              <p><?php echo $this->__('You don\'t have any recorded rebates.'); ?></p>
                            </div>
                          </div>
                        </div>
                    </div>
                  <?php endif; ?>      

                </div> <!-- page-account-table-item-container -->

                <?php echo $this->getSpentPagerHtml() ?>

              </div>

              <!--
                 _______  ______ ___ ____  _____ ____
                | ____\ \/ /  _ \_ _|  _ \| ____|  _ \
                |  _|  \  /| |_) | || |_) |  _| | | | |
                | |___ /  \|  __/| ||  _ <| |___| |_| |
                |_____/_/\_\_|  |___|_| \_\_____|____/

              -->

              <div id="page-account-rebate-history-expired-table" class="page-account-table">

                <div class="page-account-table-header">
                  <div class="row">
                    <div class="col-sm-4 col-xs-5">
                      <div class="table-column-first">
                        <h4><?php echo $this->__('Description') ?></h4>
                      </div>
                    </div>
                    <!-- <div class="col-sm-3">
                      <div class="table-column">
                        <h4><?php echo $this->__('Status') ?></h4>
                      </div>
                    </div> -->
                    <div class="col-sm-4 col-xs-3">
                      <div class="table-column">
                        <h4><?php echo $this->__('Rebates') ?></h4>
                      </div>
                    </div>
                    <div class="col-sm-4 col-xs-4">
                      <div class="table-column-last">
                        <h4><?php echo $this->__('Expiry date') ?></h4>
                      </div>
                    </div>
                  </div>
                </div> <!-- page-account-table-header -->

                <div class="page-account-table-item-container">
                  
                  <?php $_expiredPoints = $this->getExpiredPoints(); ?>
                  <?php if($_expiredPoints->getSize()): ?>
                    <?php foreach ($_expiredPoints as $_point): ?>
                      <div class="page-account-table-item">
                        <div class="row">
                          <div class="col-sm-4 col-xs-5">
                            <div class="table-column-first"><!--  data-column="Description:" -->
                              <?php echo $this->getTypeOfPoint($_point);?>
                            </div>
                          </div>
                          <!-- <div class="col-sm-3 col-xs-4">
                            <div class="table-column" data-column="Status:">
                              <?php 
                              $status_field = Mage::getStoreConfig('rewardpoints/default/status_used', Mage::app()->getStore()->getId());
                              $order_id = $_point->getOrderId();
                              $order = Mage::getModel('sales/order')->loadByIncrementId($order_id);
                              $order_status = $order->getData($status_field);
                              ?>
                              
                              <p><?php echo (!empty($order_status)) ? $order_status : "-" ?></p>
                            </div>
                          </div> -->
                          <div class="col-sm-4 col-xs-3">
                            <div class="table-column"> <!-- data-column="Rebates:" -->
                              <p><?php echo $_point->getPoints_current() ?></p>
                            </div>
                          </div>
                          <div class="col-sm-4 col-xs-4">
                            <div class="table-column-last mobile-last-version"> <!-- data-column="Expired date:" -->
                              <h4><?php if ($_point->getDate_end() != ""): echo $this->formatDate($_point->getDate_end(), 'short'); endif; ?></h4>
                            </div>
                          </div>
                        </div>
                      </div>
                    <?php endforeach; ?>  
                  <?php else: ?>
                    <div class="page-account-table-item">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="table-column-first">
                              <p><?php echo $this->__('You don\'t have any recorded rebates.'); ?></p>
                            </div>
                          </div>
                        </div>
                    </div>
                  <?php endif; ?>

                </div> <!-- page-account-table-item-container -->

                <?php echo $this->getExpiredPagerHtml() ?>

              </div> <!-- page-account-rebate-history-expired-table -->            

          </div> <!-- page-account-rebate-history-content -->

        </div> <!-- page-account-content -->


      </div> <!-- col-md-10 -->



    </div> <!-- row -->
  </div> <!-- container-fluid -->

</article> <!-- page-account-content-section -->