<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>



<div id="monogram-page-account-mobile-header" class="visible-sm visible-xs">
  <h4>membership services</h4>
  <h2>Friend Referral</h2>
</div>

<!-- 
<div id="monogram-page-account-mobile-page-title" class="visible-sm visible-xs">
  <h1><?php echo $this->__('REFERRAL') ?></h1>
</div>
-->



<div id="monogram-page-account-details-refer-friends-container">

  <div class="my-account">
      <div class="referral-container">
          <div class="page-title">
              <h1><?php echo $this->__('FRIEND REFERRAL') ?></h1>
              <hr class="small">
          </div>
          <div class="referral-steps">
            <div class="row">
              <div class="col-md-4">
                <h6>Step 1</h6>
                <h3>refer a friend</h3>
                <p>Get your friends to enjoy Monogram Tea with you at www.monogramtea.com</p>
              </div>
              <div class="col-md-4">
                <h6>Step 2</h6>
                <h3>earn $5 rebates together</h3>
                <p>When your friends make their first purchase, you and your friends will earn $5 in rebates</p>
              </div>
              <div class="col-md-4">
                <h6>Step 3</h6>
                <h3>redeem your rebates</h3>
                <p>Make your next purchase within 30 days to reward yourself</p>
              </div>
            </div>
          </div>
          <?php if($this->getReferrerRegistrationPoints()):?>
              <div class="points">
                  <div class="left">
                      <div class="pts"><span class="no"><?php echo $this->getReferrerRegistrationPoints(); ?></span><span class="text">points</span></div>
                  </div>
                  <div class="right">
                      <span class="pts-text">For any referred friend's registration</span>
                  </div>
              </div>
              <p><?php echo $this->__('For any referred friend\'s registration, you earn: <strong>%s points</strong>', $this->getReferrerRegistrationPoints());?></p> 
          <?php endif;?>
          <?php if($this->getFriendRegistrationPoints()):?>
              <p><?php echo $this->__('For any referred friend\'s registration, you friend earn: <strong>%s points</strong>', $this->getFriendRegistrationPoints());?></p>
          <?php endif;?>
          <?php if($this->getReferrerPoints() && $this->getReferrerCalculationType() == Rewardpoints_Model_Calculationtype::STATIC_VALUE):?>
              <div class="points">
                  <div class="left">
                      <div class="pts"><span class="no"><?php echo $this->getReferrerPoints(); ?></span><span class="text">points</span></div>
                  </div>
                  <div class="right">
                      <span class="pts-text">For any first valid order placed by referred friend</span>
                  </div>
              </div>
              <?php 
              $rewardPoints = $this->getReferrerPoints();
              ?>              
              <!-- <p><?php echo $this->__('For every valid first order by a referred friend, you earn a <strong>%s</strong> rebate.', Mage::helper('core')->currency($rewardPoints, true, false));?></p> -->
              <?php elseif ($this->getReferrerPoints() && $this->getReferrerCalculationType() == Rewardpoints_Model_Calculationtype::RATIO_POINTS):?>
              <p><?php echo $this->__('For any first valid order placed by referred friend, you earn: <strong>%s points x product price values</strong>', $this->getReferrerPoints());?></p>
              <?php elseif ($this->getReferrerPoints() && $this->getReferrerCalculationType() == Rewardpoints_Model_Calculationtype::CART_SUMMARY):?>
              <p><?php echo $this->__('For any first valid order placed by referred friend, you earn: <strong>%s points x cart summary</strong>', $this->getReferrerPoints());?></p>
          <?php endif;?>
          <?php if($this->getFriendPoints() && $this->getFriendCalculationType() == Rewardpoints_Model_Calculationtype::STATIC_VALUE):?>
              <!-- <p><?php echo $this->__('For any first valid order placed by referred friend, your friend gets: <strong>%s extra points</strong>', $this->getFriendPoints());?></p> -->
              <?php elseif ($this->getFriendPoints() && $this->getFriendCalculationType() == Rewardpoints_Model_Calculationtype::RATIO_POINTS):?>
              <p><?php echo $this->__('For any first valid order placed by referred friend, you friend gets: <strong>%s points x product price values</strong>', $this->getFriendPoints());?></p>        
              <?php elseif ($this->getFriendPoints() && $this->getFriendCalculationType() == Rewardpoints_Model_Calculationtype::CART_SUMMARY):?>
              <p><?php echo $this->__('For any first valid order placed by referred friend, you friend gets: <strong>%s points x cart summary</strong>', $this->getFriendPoints());?>
              </p>
          <?php endif;?>
          <?php if ($this->getMinOrderAmount()):?>
              <div class="min-order-referral-j2t">
              <p><?php echo $this->__("Minimum order for referral program to be processed is: <strong>%s</strong>", Mage::helper('core')->currency($this->getMinOrderAmount(),true,false));?></p>
              </div>
          <?php endif;?>

          <?php if($this->isAddthis() || $this->isPermanentLink() || Mage::getStoreConfig('rewardpoints/registration/referral_custom_code')):?>
          <div class="account-box ad-account-info box">
              <?php if($this->isPermanentLink()):?>
              <div class="group-select fieldset">
                  <h2 class="legend"><?php echo $this->__('Permanent Link') ?></h2>
                  <?php echo $this->__('Share the following link with your friends: <br /><strong>%s</strong>', $this->getReferringUrl()) ?>
              </div>
              <?php endif;?>
              
              <?php if ($custom_code = Mage::getStoreConfig('rewardpoints/registration/referral_custom_code')):?>
                  <div class="group-select fieldset" style="min-height: 40px;">
                      <h2 class="legend"><?php echo $this->__('Share with the following') ?></h2>
                      <?php echo str_replace("{{referral_url}}", $this->getReferringUrl(), $custom_code);?>
                  </div>
              <?php endif;?>


              <?php if($this->isAddthis()):?>
              
                  <div class="group-select fieldset">
                      <h2 class="legend"><?php echo $this->__('Share referring link') ?></h2>
                      <ul>
                          <li>
                              <div class="input-box">
                                  <label for="j2t-share-title"><?php echo $this->__('Sharing title (may not be used)') ?></label><br />
                                  <input onkeyup="j2tReinitializeAddThis();" type="text" name="j2t-share-title" id="j2t-share-title" value="<?php echo $this->__('Great deals here!');?>" class="input-text" />
                              </div>
                              <div class="input-box">
                                  <label for="j2t-share-text"><?php echo $this->__('Sharing text (may not be used)') ?></label><br />
                                  <textarea onkeyup="j2tReinitializeAddThis();" id="j2t-share-text" name="j2t-share-text" cols="100" rows="5" class="input-text"><?php echo $this->__('Visit this for great deals!');?></textarea>
                              </div>
                          </li>
                      </ul>
                      <br />
                      <!-- AddThis Button BEGIN -->
                      <?php echo Mage::getStoreConfig('rewardpoints/registration/referral_addthis_code', Mage::app()->getStore()->getId());?>
                      <script type="text/javascript">
                          var addthis_share =
                          {
                              url: "<?php echo $this->getReferringUrl();?>",
                              title: $('j2t-share-title').value,
                              description: $('j2t-share-text').value
                          }
                      </script>
                  </div>

                  
      	    <?php $http = (Mage::app()->getStore()->isCurrentlySecure()) ? 'https' : 'http';?>
                  <script type="text/javascript" src="<?php echo $http;?>://s7.addthis.com/js/250/addthis_widget.js#pubid=<?php echo Mage::getStoreConfig('rewardpoints/registration/referral_addthis_account', Mage::app()->getStore()->getId());?>"></script>
                  <!-- AddThis Button END -->


                  <?php /*?>
                  <a class="addthis_button" id="j2t-post-share" addthis:url="<?php echo $this->getReferringUrl();?>" addthis:title="<?php echo $this->__('Great deals here!');?>" addthis:description="<?php echo $this->__('Visit this for great deals!');?>"></a>
                  <script type="text/javascript">
                      function j2tReinitializeAddThis(){
                        if (window.addthis){
                           $('j2t-post-share').writeAttribute('addthis:title', $('j2t-share-title').value);
                           $('j2t-post-share').writeAttribute('addthis:description', $('j2t-share-text').value);
                           window.addthis.ost = 0;
                           window.addthis.ready();
                        }
                     }
                      //addthis.button('#j2t-post-share', {}, {url: "<?php echo $this->getReferringUrl();?>", title: $('j2t-share-title').value, description: $('j2t-share-text').value});
                      addthis.button('#j2t-post-share');
                  </script>
                  <?php */?>
              
              <?php endif;?>
              
          </div>
          <?php endif;?>
      </div>
      <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
      <form action="<?php echo $this->getUrl('rewardpoints/index/referral/') ?>" method="post" class="refer-friend-form" id="form-validate">
          <div class="group-select fieldset" id="j2t-referral-lines">
              <?php /*?><input type="hidden" value="Il1NwrpfsCuSmp03" name="form_key"/><?php */?>
              <?php echo $this->getBlockHtml('formkey')?>
              <h1 class="legend"><?php echo $this->__('Refer a friend') ?></h1>
              <hr class="small">      
                  <div id="clone-form" class="each-form">
                    <ul class="form-list">
                        <li class="fields">
                            <div class="j2t-rewardpoints-referral">
                                <div class="field j2t-rewardpoints-name">
                                    <label for="name" class="required" id="label-name"><?php echo $this->__('Friend\'s name') ?><em>*</em></label>
                                    <input type="text" name="name[]" value="" title="<?php echo $this->__('Friend\' name') ?>" class="required-entry input-text" id="name" />
                                </div>
                                <div class="field j2t-rewardpoints-email">
                                    <label for="email" class="required validate-email" id="label-email"><?php echo $this->__('Friend\'s email address') ?><em>*</em></label>
                                    <input type="text" name="email[]" value="" title="<?php echo $this->__('Friend\'s email address') ?>" class="required-entry input-text" id="email" />
                                </div>
                            </div>
                        </li>
                    </ul>
                    <div class="button-set">
                        <!-- <p class="required"><?php echo $this->__('* Required Fields') ?></p> -->
                        <!--<a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>-->
                        <button class="form-button button cta send" type="submit"><span><span><?php echo $this->__('Send') ?></span></span></button>
                        <span id='ajax_loader_referral'><img src='<?php echo $this->getSkinUrl('images/icons/spin.svg')?>'/></span>
                        <span class="ajax_msg_referral italic"></span>

                        <br class="visible-sm visible-xs">

                        <!-- <a id="j2t-add-line" href="javascript:j2t_add_line();" title="<?php echo $this->__('Add new line') ?>">Add More</a>             -->
                    </div>
                  </div>            
          
              <script type="text/javascript">
                  var elmt_id_j2t = 0;
                  function j2t_add_line(){
                      var form_list_ul = $('j2t-add-line').up().up().down("ul");
                      //var form_list_ul_clone = Element.clone(form_list_ul, true);
                      var form_list_ul_clone = form_list_ul.cloneNode(true);

                      form_list_ul_clone.down("#label-name").id = "label-name-"+elmt_id_j2t;
                      form_list_ul_clone.down("#name").id = "name-"+elmt_id_j2t;
                      form_list_ul_clone.down("#label-email").id = "label-email-"+elmt_id_j2t;
                      form_list_ul_clone.down("#email").id = "email-"+elmt_id_j2t;

                      form_list_ul_clone.down("#name-"+elmt_id_j2t).value = "";
                      form_list_ul_clone.down("#email-"+elmt_id_j2t).value = "";

                      var del_img = new Element('a', {class: 'square-cta', style: 'margin-top: 10px;'})
                      form_list_ul_clone.down(".j2t-rewardpoints-email").insert({
                          bottom: del_img
                      });
                      $j(del_img).html('Cancel');
                      del_img.observe('click', function(event) {
                          Event.element(event).up("ul").remove();
                      });

                      $('clone-form').insert({ after: form_list_ul_clone });
                      elmt_id_j2t++;
                  }

                  $j('.refer-friend-form').find('.send').on("click", function(e){
                    
                    if (dataForm.validator && dataForm.validator.validate()) {
                      e.preventDefault();

                      var $form =  $j('.refer-friend-form'),
                          action_url =  $form.attr('action'),
                          data = $form.serialize();                     

                      $j('#ajax_loader_referral').show();                

                      $j.ajax({
                        method: "POST",
                        url: action_url,
                        data: data
                      }).done(function( msg ) {

                          var messages = $j('.messages', $j.parseHTML(msg));
                          
                          $j('span.ajax_msg_referral').html('<p>'+$(messages).find('span').html()+'</p>').show().delay(5000).fadeOut();
                          $j('#ajax_loader_referral').hide();
                      });
                    }

                  });
              </script>            
          </div>
      </form>

      <script type="text/javascript">
          var dataForm = new VarienForm('form-validate', true);
      </script>
      
      <div class="page-title invite-friends">
          <h1><?php echo $this->__('friend referral history') ?></h1>
          <hr class="small">
      </div>
      <?php $_referred = $this->getReferred();?>
      <?php if($_referred->getSize()): ?>
      <div class="referral-table">
          <?php //echo $this->getPagerHtml() ?>
          <div class="table-responsive">
              <table cellspacing="0" class="data-table" id="referred-friends-table">
                  <thead>
                      <tr>
                          <?php ?><th><?php echo $this->__('Full Name') ?></th><?php ?>
                          <th><?php echo $this->__('Email') ?></th>
                          <!--<th><?php echo $this->__('Registered?') ?></th>-->
                          <!--<th><?php echo $this->__('First order?') ?></th>-->
                          <!-- <th class="custom-first-order-title-container"><span class="custom-first-order-title-01">First</span><span class="custom-first-order-title-02">order?</span></th> -->
                          <th class="custom-first-order-title-container">First order?</th>

                      </tr>
                  </thead>
                  <tbody>
                      <?php $_odd = ''; ?>
                      <?php foreach ($_referred as $_friend): ?>
                          <tr>
                              <?php ?><td><?php echo $_friend->getRewardpoints_referral_name() ?></td><?php ?>
                              <td><?php echo $_friend->getRewardpoints_referral_email() ?></td>
                              <!--<td><?php echo $_friend->getRewardpoints_referral_child_id() ? $this->__('yes') : $this->__('no') ?></td>-->
                              <td class="a-right"><?php echo $_friend->getRewardpoints_referral_status() ? $this->__('yes') : $this->__('no') ?></td>
                          </tr>
                      <?php endforeach; ?>
                  </tbody>
              </table>
          </div>
          <?php echo $this->getPagerHtml() ?>
      </div>
      <?php else: ?>
          <p><?php echo $this->__('You have not invited any friends.'); ?></p>
      <?php endif ?>
  </div>


</div>
<script>
  $j(".messages").addClass("referral-message");
</script>
<style>
  .back-link {
    display: none;
  }
</style>