<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>

 <script>
   $j("body").addClass("account-friend-referral-page");
 </script>

  <!--
     _____ ___ _____ _     _____
    |_   _|_ _|_   _| |   | ____|
      | |  | |  | | | |   |  _|
      | |  | |  | | | |___| |___
      |_| |___| |_| |_____|_____|

  -->

  <article id="page-account-title-section">
    <div class="container-fluid has-breakpoint">
      <div class="row">
        <div class="col-md-3 col-sm-1 col-xs-0"></div>
        <div class="col-md-9 col-sm-10 col-xs-12">
          <div id="page-account-title">
            <h1><?php echo $this->__('Get your friends to enjoy Roji Cha with you.') ?></h1>
          </div> <!-- page-account-title -->
        </div>
      </div>
    </div>
  </article> <!-- page-account-title-section -->

  <!--
      ____ ___  _   _ _____ _____ _   _ _____
     / ___/ _ \| \ | |_   _| ____| \ | |_   _|
    | |  | | | |  \| | | | |  _| |  \| | | |
    | |__| |_| | |\  | | | | |___| |\  | | |
     \____\___/|_| \_| |_| |_____|_| \_| |_|

  -->

  <article id="page-account-content-section">
    <div id="page-account-content-section-bg" class="">
      <div class="sidebar-bg visible-md visible-lg"></div>
      <div class="content-bg"></div>
    </div>

    <div class="container-fluid has-breakpoint">
      <div class="row">

        <div class="col-md-2 col-tablet-landscape-2 hidden-sm hidden-xs">

          <!--
             ____ ___ ____  _____ ____    _    ____
            / ___|_ _|  _ \| ____| __ )  / \  |  _ \
            \___ \| || | | |  _| |  _ \ / _ \ | |_) |
             ___) | || |_| | |___| |_) / ___ \|  _ <
            |____/___|____/|_____|____/_/   \_\_| \_\

          -->

          <div id="page-account-sidebar-width"></div>
          <div id="page-account-sidebar">

            <?php echo $this->getChildHtml('navigation') ?>

          </div> <!-- page-account-sidebar -->

      </div> <!-- col-md-2 -->
      <div class="col-md-0 col-tablet-landscape-0 col-sm-1 col-xs-0"></div>
      <div class="col-md-10 col-tablet-landscape-10 col-sm-10 col-xs-12">

        <!--
            ____ ___  _   _ _____ _____ _   _ _____
           / ___/ _ \| \ | |_   _| ____| \ | |_   _|
          | |  | | | |  \| | | | |  _| |  \| | | |
          | |__| |_| | |\  | | | | |___| |\  | | |
           \____\___/|_| \_| |_| |_____|_| \_| |_|

        -->

        <div id="page-account-content-width"></div>
        <div id="page-account-content">

          <!--
             _____ ____  ___ _____ _   _ ____    ____  _____ _____ _____ ____  ____      _    _
            |  ___|  _ \|_ _| ____| \ | |  _ \  |  _ \| ____|  ___| ____|  _ \|  _ \    / \  | |
            | |_  | |_) || ||  _| |  \| | | | | | |_) |  _| | |_  |  _| | |_) | |_) |  / _ \ | |
            |  _| |  _ < | || |___| |\  | |_| | |  _ <| |___|  _| | |___|  _ <|  _ <  / ___ \| |___
            |_|   |_| \_\___|_____|_| \_|____/  |_| \_\_____|_|   |_____|_| \_\_| \_\/_/   \_\_____|

          -->

            
          <div id="page-account-friend-referral-title" class="hidden-xs">
            <h2><?php echo $this->__('Friend referral') ?></h2>
          </div> <!-- page-account-friend-referral-title -->

          <div id="page-account-friend-referral-header-container" class="sans-container-fluid-mobile">
              
              <div id="page-account-friend-referral-header">

                <div class="row">
                  <div class="col-sm-4">

                    <div class="referral-header-item first-version">
                      <h6><?php echo $this->__('Step 1') ?></h6>
                      <div class="detail-item">
                        <h4><?php echo $this->__('Refer a friend') ?></h4>
                        <p><?php echo $this->__('Get your friends to enjoy Roji Cha with you at www.rojicha.com') ?></p>
                      </div>
                    </div>

                  </div>
                  <div class="col-sm-4">

                    <div class="referral-header-item">
                      <h6><?php echo $this->__('Step 2') ?></h6>
                      <div class="detail-item">
                        <h4><?php echo $this->__('Earn $5 rebates together') ?></h4>
                        <p><?php echo $this->__('When your friends make their first purchase, you and your friends will earn $5 in rebates') ?></p>
                      </div>
                    </div>

                  </div>
                  <div class="col-sm-4">

                    <div class="referral-header-item last-version">
                      <h6><?php echo $this->__('Step 3') ?></h6>
                      <div class="detail-item">
                        <h4><?php echo $this->__('Redeem your rebates') ?></h4>
                        <p><?php echo $this->__('Make your next purchase within 30 days to reward yourself') ?></p>
                      </div>
                    </div>

                  </div>
                </div>

              </div> <!-- page-account-friend-referral-header -->
              
              <div id="page-account-friend-referral-no-use" class="no-display">
                <?php if($this->getReferrerRegistrationPoints()):?>
                    <div class="points">
                        <div class="left">
                            <div class="pts"><span class="no"><?php echo $this->getReferrerRegistrationPoints(); ?></span><span class="text">points</span></div>
                        </div>
                        <div class="right">
                            <span class="pts-text">For any referred friend's registration</span>
                        </div>
                    </div>
                    <p><?php echo $this->__('For any referred friend\'s registration, you earn: <strong>%s points</strong>', $this->getReferrerRegistrationPoints());?></p> 
                <?php endif;?>
                <?php if($this->getFriendRegistrationPoints()):?>
                    <p><?php echo $this->__('For any referred friend\'s registration, you friend earn: <strong>%s points</strong>', $this->getFriendRegistrationPoints());?></p>
                <?php endif;?>
                <?php if($this->getReferrerPoints() && $this->getReferrerCalculationType() == Rewardpoints_Model_Calculationtype::STATIC_VALUE):?>
                    <div class="points">
                        <div class="left">
                            <div class="pts"><span class="no"><?php echo $this->getReferrerPoints(); ?></span><span class="text">points</span></div>
                        </div>
                        <div class="right">
                            <span class="pts-text">For any first valid order placed by referred friend</span>
                        </div>
                    </div>
                    <?php 
                    $rewardPoints = $this->getReferrerPoints();
                    ?>              
                    <!-- <p><?php echo $this->__('For every valid first order by a referred friend, you earn a <strong>%s</strong> rebate.', Mage::helper('core')->currency($rewardPoints, true, false));?></p> -->
                    <?php elseif ($this->getReferrerPoints() && $this->getReferrerCalculationType() == Rewardpoints_Model_Calculationtype::RATIO_POINTS):?>
                    <p><?php echo $this->__('For any first valid order placed by referred friend, you earn: <strong>%s points x product price values</strong>', $this->getReferrerPoints());?></p>
                    <?php elseif ($this->getReferrerPoints() && $this->getReferrerCalculationType() == Rewardpoints_Model_Calculationtype::CART_SUMMARY):?>
                    <p><?php echo $this->__('For any first valid order placed by referred friend, you earn: <strong>%s points x cart summary</strong>', $this->getReferrerPoints());?></p>
                <?php endif;?>
                <?php if($this->getFriendPoints() && $this->getFriendCalculationType() == Rewardpoints_Model_Calculationtype::STATIC_VALUE):?>
                    <!-- <p><?php echo $this->__('For any first valid order placed by referred friend, your friend gets: <strong>%s extra points</strong>', $this->getFriendPoints());?></p> -->
                    <?php elseif ($this->getFriendPoints() && $this->getFriendCalculationType() == Rewardpoints_Model_Calculationtype::RATIO_POINTS):?>
                    <p><?php echo $this->__('For any first valid order placed by referred friend, you friend gets: <strong>%s points x product price values</strong>', $this->getFriendPoints());?></p>        
                    <?php elseif ($this->getFriendPoints() && $this->getFriendCalculationType() == Rewardpoints_Model_Calculationtype::CART_SUMMARY):?>
                    <p><?php echo $this->__('For any first valid order placed by referred friend, you friend gets: <strong>%s points x cart summary</strong>', $this->getFriendPoints());?>
                    </p>
                <?php endif;?>
                <?php if ($this->getMinOrderAmount()):?>
                    <div class="min-order-referral-j2t">
                    <p><?php echo $this->__("Minimum order for referral program to be processed is: <strong>%s</strong>", Mage::helper('core')->currency($this->getMinOrderAmount(),true,false));?></p>
                    </div>
                <?php endif;?>

                <?php if($this->isAddthis() || $this->isPermanentLink() || Mage::getStoreConfig('rewardpoints/registration/referral_custom_code')):?>
                  <div class="account-box ad-account-info box">
                      <?php if($this->isPermanentLink()):?>
                      <div class="group-select fieldset">
                          <h2 class="legend"><?php echo $this->__('Permanent Link') ?></h2>
                          <?php echo $this->__('Share the following link with your friends: <br /><strong>%s</strong>', $this->getReferringUrl()) ?>
                      </div>
                      <?php endif;?>
                      
                      <?php if ($custom_code = Mage::getStoreConfig('rewardpoints/registration/referral_custom_code')):?>
                          <div class="group-select fieldset" style="min-height: 40px;">
                              <h2 class="legend"><?php echo $this->__('Share with the following') ?></h2>
                              <?php echo str_replace("{{referral_url}}", $this->getReferringUrl(), $custom_code);?>
                          </div>
                      <?php endif;?>


                      <?php if($this->isAddthis()):?>
                      
                          <div class="group-select fieldset">
                              <h2 class="legend"><?php echo $this->__('Share referring link') ?></h2>
                              <ul>
                                  <li>
                                      <div class="input-box">
                                          <label for="j2t-share-title"><?php echo $this->__('Sharing title (may not be used)') ?></label><br />
                                          <input onkeyup="j2tReinitializeAddThis();" type="text" name="j2t-share-title" id="j2t-share-title" value="<?php echo $this->__('Great deals here!');?>" class="input-text" />
                                      </div>
                                      <div class="input-box">
                                          <label for="j2t-share-text"><?php echo $this->__('Sharing text (may not be used)') ?></label><br />
                                          <textarea onkeyup="j2tReinitializeAddThis();" id="j2t-share-text" name="j2t-share-text" cols="100" rows="5" class="input-text"><?php echo $this->__('Visit this for great deals!');?></textarea>
                                      </div>
                                  </li>
                              </ul>
                              <br />
                              <!-- AddThis Button BEGIN -->
                              <?php echo Mage::getStoreConfig('rewardpoints/registration/referral_addthis_code', Mage::app()->getStore()->getId());?>
                              <script type="text/javascript">
                                  var addthis_share =
                                  {
                                      url: "<?php echo $this->getReferringUrl();?>",
                                      title: $('j2t-share-title').value,
                                      description: $('j2t-share-text').value
                                  }
                              </script>
                          </div>

                          
                    <?php $http = (Mage::app()->getStore()->isCurrentlySecure()) ? 'https' : 'http';?>
                          <script type="text/javascript" src="<?php echo $http;?>://s7.addthis.com/js/250/addthis_widget.js#pubid=<?php echo Mage::getStoreConfig('rewardpoints/registration/referral_addthis_account', Mage::app()->getStore()->getId());?>"></script>
                          <!-- AddThis Button END -->


                          <?php /*?>
                          <a class="addthis_button" id="j2t-post-share" addthis:url="<?php echo $this->getReferringUrl();?>" addthis:title="<?php echo $this->__('Great deals here!');?>" addthis:description="<?php echo $this->__('Visit this for great deals!');?>"></a>
                          <script type="text/javascript">
                              function j2tReinitializeAddThis(){
                                if (window.addthis){
                                   $('j2t-post-share').writeAttribute('addthis:title', $('j2t-share-title').value);
                                   $('j2t-post-share').writeAttribute('addthis:description', $('j2t-share-text').value);
                                   window.addthis.ost = 0;
                                   window.addthis.ready();
                                }
                             }
                              //addthis.button('#j2t-post-share', {}, {url: "<?php echo $this->getReferringUrl();?>", title: $('j2t-share-title').value, description: $('j2t-share-text').value});
                              addthis.button('#j2t-post-share');
                          </script>
                          <?php */?>
                      
                      <?php endif;?>

                      
                  </div>
                <?php endif;?>

              </div> <!-- page-account-friend-referral-no-use -->

          </div> <!-- page-account-friend-referral-header-container -->
          
          <div id="page-account-friend-referral-title" class="visible-xs">
            <h2><?php echo $this->__('Friend referral') ?></h2>
          </div> <!-- page-account-friend-referral-title -->

          <div id="page-account-friend-referral-form-container" class="sans-container-fluid-mobile">

              <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
              <form action="<?php echo $this->getUrl('rewardpoints/index/referral/') ?>" method="post" class="refer-friend-form checkout-form" id="page-account-friend-referral-form">
                <div class="row">
                  <div class="col-md-12">
                    <ul class="messages"><li><span class="ajax_msg_referral italic"></span></li></ul>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6 col-sm-8">

                    <div class="form-group">
                      <div class="row">
                        <div class="col-sm-4">
                          <label for="name" class="required" id="label-name"><?php echo $this->__('Friend\'s name') ?><em>*</em></label>
                        </div>
                        <div class="col-sm-8">
                          <input type="text" name="name[]" value="" title="<?php echo $this->__('Friend\' name') ?>" class="required-entry input-text" id="name" />
                        </div>
                      </div>
                    </div> <!-- form-group -->

                    <div class="form-group">
                      <div class="row">
                        <div class="col-sm-4">
                          <label for="email" class="required validate-email" id="label-email"><?php echo $this->__('Friend\'s email') ?><em>*</em></label>
                        </div>
                        <div class="col-sm-8">
                          <input type="text" name="email[]" value="" title="<?php echo $this->__('Friend\'s email') ?>" class="required-entry input-text" id="email" />
                        </div>
                      </div>
                    </div> <!-- form-group -->

                  </div>
                  <div class="col-md-6 col-sm-4 col-sm-push-0 col-xs-10 col-xs-push-1">

                    <div class="cta-container">
                      <button class="form-button button cta send square-cta" type="submit"><span><span><?php echo $this->__('Send') ?></span></span></button>                      
                    </div>

                  </div>
                </div>
              </form>

          </div>  <!-- page-account-friend-referral-form-container -->

          <div id="page-account-friend-referral-table-container" class="sans-container-fluid-mobile">

              <div id="page-account-friend-referral-table-title">
                <h2>Friend referral history</h2>
              </div> <!-- page-account-friend-referral-table-title -->

              <div id="page-account-friend-referral-table" class="page-account-table">

                <div class="page-account-table-header">
                  <div class="row">
                    <div class="col-sm-4 col-xs-4">
                      <div class="table-column-first">
                        <h4><?php echo $this->__('Full name') ?></h4>
                      </div>
                    </div>
                    <div class="col-sm-4 col-xs-5">
                      <div class="table-column">
                        <h4><?php echo $this->__('Email address') ?></h4>
                      </div>
                    </div>
                    <div class="col-sm-4 col-xs-3">
                      <div class="table-column-last">
                        <h4><?php echo $this->__('$5 Rebates') ?></h4>
                      </div>
                    </div>
                    
                  </div>
                </div> <!-- page-account-table-header -->

                <div class="page-account-table-item-container">

                  <?php $_referred = $this->getReferred();?>
                  <?php if($_referred->getSize()): ?>
                    
                    <?php $_odd = ''; ?>
                    <?php foreach ($_referred as $_friend): ?>

                        <div class="page-account-table-item">
                          <div class="row">
                            <div class="col-sm-4 col-xs-4">
                              <div class="table-column-first"> <!-- data-column="Full name:" -->
                                <p><?php echo $_friend->getRewardpoints_referral_name() ?></p>
                              </div>
                            </div>
                            <div class="col-sm-4 col-sm-push-4 col-xs-3 col-xs-push-5">
                              <div class="table-column-last"> <!-- data-column="$5 Rebates:" -->
                                <p><?php echo $_friend->getRewardpoints_referral_status() ? $this->__('Earned') : $this->__('Pending') ?></p>
                              </div>
                            </div>
                            <div class="col-sm-4 col-sm-pull-4 col-xs-5 col-xs-pull-3">
                              <div class="table-column mobile-last-version"> <!-- data-column="Email address:" -->
                                <p><?php echo $_friend->getRewardpoints_referral_email() ?></p>
                              </div>
                            </div>                            
                          </div>
                        </div>

                    <?php endforeach; ?>                    

                    <?php echo $this->getPagerHtml() ?>

                  <?php else: ?>

                    <div class="page-account-table-item">
                      <div class="row">
                        <div class="col-md-4">
                          <div class="table-column-first">
                            <p><?php echo $this->__('You have not invited any friends.'); ?></p>
                          </div>
                        </div>
                      </div>
                    </div>

                  <?php endif; ?>

                </div>

              </div> <!-- page-account-friend-referral-table -->

        </div> <!-- page-account-content -->


      </div> <!-- col-md-10 -->



    </div> <!-- row -->
  </div> <!-- container-fluid -->

</article> <!-- page-account-content-section -->

<script type="text/javascript">
  var elmt_id_j2t = 0;
  function j2t_add_line(){
      var form_list_ul = $('j2t-add-line').up().up().down("ul");
      //var form_list_ul_clone = Element.clone(form_list_ul, true);
      var form_list_ul_clone = form_list_ul.cloneNode(true);

      form_list_ul_clone.down("#label-name").id = "label-name-"+elmt_id_j2t;
      form_list_ul_clone.down("#name").id = "name-"+elmt_id_j2t;
      form_list_ul_clone.down("#label-email").id = "label-email-"+elmt_id_j2t;
      form_list_ul_clone.down("#email").id = "email-"+elmt_id_j2t;

      form_list_ul_clone.down("#name-"+elmt_id_j2t).value = "";
      form_list_ul_clone.down("#email-"+elmt_id_j2t).value = "";

      var del_img = new Element('a', {class: 'square-cta', style: 'margin-top: 10px;'})
      form_list_ul_clone.down(".j2t-rewardpoints-email").insert({
          bottom: del_img
      });
      $j(del_img).html('Cancel');
      del_img.observe('click', function(event) {
          Event.element(event).up("ul").remove();
      });

      $('clone-form').insert({ after: form_list_ul_clone });
      elmt_id_j2t++;
  }

  $j('.refer-friend-form').find('.send').on("click", function(e){
    
    if (dataForm.validator && dataForm.validator.validate()) {
      e.preventDefault();

      var $form =  $j('.refer-friend-form'),
          action_url =  $form.attr('action'),
          data = $form.serialize();                     

      // $j('#ajax_loader_referral').show();                

      $j.ajax({
        method: "POST",
        url: action_url,
        data: data
      }).done(function( msg ) {

          var messages = $j('.messages', $j.parseHTML(msg));

          var messages_message = $(messages).find('span').html();          
          
          $j('span.ajax_msg_referral').html('<p>'+$(messages).find('span').html()+'</p>').show();

          if(messages_message.includes("successfully invited")) {
            location.reload();
          }
          // $j('#ajax_loader_referral').hide();
      });
    }

  });
</script>
<script type="text/javascript">
    var dataForm = new VarienForm('page-account-friend-referral-form', true);
</script>
<script>
    $j(".messages").addClass("referral-message");
</script>
<style>
    .back-link {
      display: none;
    }
</style>