<?php
/**
 * Miragedesign Web Development
 *
 * @category    Miragedesign
 * @package     Miragedesign_Checkoutcustomiser
 * @copyright   Copyright (c) 2011 Miragedesign (http://miragedesign.net)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<style>
.selfcollect {
    font-family: 'BrandonGrotesqueWeb-Medium', "Arial Black", Gadget, sans-serif;
    font-style: normal;
    font-weight: 400;
    font-size: 10px;
    line-height: 15px;
    letter-spacing: 0.08em;
    color: #f1efee !important;
    text-transform: uppercase;
    white-space: nowrap;
    display: block;
    border-top: 1px solid #ffffff;
    border-bottom: 1px solid #ffffff;
    padding-top: 11px;
    padding-bottom: 13px;
    padding-left: 24px;
    padding-right: 24px;
    margin-top: 24px;
}
.selfcollect input {
vertical-align:bottom;
margin-left:10px;
}
</style>
<?php
function isMobile()  
{  
    $regex_match = "/(nokia|iphone|android|motorola|^mot\-|softbank|foma|docomo|kddi|up\.browser|up\.link|"  
                 . "htc|dopod|blazer|netfront|helio|hosin|huawei|novarra|CoolPad|webos|techfaith|palmsource|"  
                 . "blackberry|alcatel|amoi|ktouch|nexian|samsung|^sam\-|s[cg]h|^lge|ericsson|philips|sagem|wellcom|bunjalloo|maui|"  
                 . "symbian|smartphone|mmp|midp|wap|phone|windows ce|iemobile|^spice|^bird|^zte\-|longcos|pantech|gionee|^sie\-|portalmmm|"  
                 . "jig\s browser|hiptop|^ucweb|^benq|haier|^lct|opera\s*mobi|opera\*mini|320x320|240x320|176x220"  
                 . ")/i";  

    if (preg_match($regex_match, strtolower($_SERVER['HTTP_USER_AGENT']))) {  
        return TRUE;  
    }  

    if ((strpos(strtolower($_SERVER['HTTP_ACCEPT']),'application/vnd.wap.xhtml+xml') > 0) or ((isset($_SERVER['HTTP_X_WAP_PROFILE']) or isset($_SERVER['HTTP_PROFILE'])))) {  
        return TRUE;  
    }      

    $mobile_ua = strtolower(substr($_SERVER['HTTP_USER_AGENT'], 0, 4));  
    $mobile_agents = array(  
        'w3c ','acs-','alav','alca','amoi','audi','avan','benq','bird','blac',  
        'blaz','brew','cell','cldc','cmd-','dang','doco','eric','hipt','inno',  
        'ipaq','java','jigs','kddi','keji','leno','lg-c','lg-d','lg-g','lge-',  
        'maui','maxo','midp','mits','mmef','mobi','mot-','moto','mwbp','nec-',  
        'newt','noki','oper','palm','pana','pant','phil','play','port','prox',  
        'qwap','sage','sams','sany','sch-','sec-','send','seri','sgh-','shar',  
        'sie-','siem','smal','smar','sony','sph-','symb','t-mo','teli','tim-',  
        'tosh','tsm-','upg1','upsi','vk-v','voda','wap-','wapa','wapi','wapp',  
        'wapr','webc','winw','winw','xda ','xda-');  

    if (in_array($mobile_ua,$mobile_agents)) {  
        return TRUE;  
    }  

    if (isset($_SERVER['ALL_HTTP']) && strpos(strtolower($_SERVER['ALL_HTTP']),'OperaMini') > 0) {  
        return TRUE;  
    }  

    return FALSE;  
}
$isiPad = (bool) strpos($_SERVER['HTTP_USER_AGENT'],'iPad');
?>
<div id="page-shopping-cart-content">
    <div id="page-shopping-cart-billing-shipping-container">
        <form id="co-billing-form" action="" autocomplete="off">
            <div class="row">
                <div class="col-md-6">
                    <div id="page-shopping-cart-billing-container">
                        <div class="billing_address">
                            <h1><?php echo $this->__('Billing Address')?></h1>
                            <hr class="small" />

                                <ul class="form-list">
                                <?php if ($this->customerHasAddresses()): ?>
                                    <li class="wide each-input dropdown-address">
                                        <label for="billing-address-select"><?php echo $this->__('Select your billing address') ?></label>
                                        <div class="input-box dropdown">
                                            <?php //echo $this->getAddressesHtmlSelect('billing') ?>                            
                                            <div id="custAddress">
                                            <?php $customerId = Mage::getSingleton('customer/session')->getCustomer();?>    
                                            <?php $customer = Mage::getModel('customer/customer')->load($customerId->getId()); ?>
                                            <?php $data = array();?>
                                                <select name="billing_address_id" id="billing-address-select" class="address-select" title="">                                
                                                    <option value="">New Address</option>                                                                                       
                                                    <?php $i=0; foreach ($customer->getAddresses() as $address):?>                                
                                                        <?php $data = $address->toArray();?>
                                                        <?php $country_name = Mage::app()->getLocale()->getCountryTranslation($data['country_id']);?>                                    
                                                        <option <?php if($i==0): ?>selected="selected"<?php endif; ?> value="<?php echo $data['entity_id']; ?>"><?php echo $data['firstname'] . ' ' . $data['firstname'] . ', ' . $data['street'] . ', ' . $data['city'] . ', ' . $data['postcode']. ', ' . $country_name;  ?></option>
                                                    <?php $i++; endforeach; ?>  
                                                </select>
                                             </div>                        
                                        </div>
                                    </li>
                                <?php endif; ?>
                                <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
                                    <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
                                    <ul>
                                        <li class="fields">
                                            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')
                                                ->setTemplate('miragedesign/customer/widget/name.phtml')
                                                ->toHtml()
                                            ?>
                                        </li>
                                        <li class="fields">
                                            <!-- <div class="field each-input">
                                                <label for="billing:company"><?php echo $this->__('Company') ?></label>
                                                <div class="input-box">
                                                    <input type="text" id="billing:company" name="billing[company]" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                                                </div>
                                            </div> -->
                                <?php if(!$this->isCustomerLoggedIn()): ?>
                                            <div class="field each-input">
                                                <label for="billing:email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                                                <div class="input-box">
                                                    <input type="text" name="billing[email]" id="billing:email" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                                                </div>
                                            </div>
                                <?php endif; ?>
                                        </li>
                                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                                        <li class="fields each-input">
                                            <label for="billing:street1" class="required"><?php echo $this->__('Address') ?>*</label>
                                            <div class="input-box">
                                                <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                                            </div>
                                        </li>
                                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                        <li class="fields each-input">
                                            <label></label>
                                            <div class="input-box">
                                                <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                                            </div>
                                        </li>
                                <?php endfor; ?>
                                        <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                                        <li class="fields each-input">
                                            <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
                                            <div class="input-box">
                                                <input type="text" id="billing:vat_id" name="billing[vat_id]" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                                            </div>
                                        </li>
                                        <?php endif; ?>
                                        <li class="fields">
                                            <div class="field each-input">
                                                <label for="billing:city" class="required"><?php echo $this->__('City') ?><em>*</em></label>
                                                <div class="input-box">
                                                    <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" />
                                                </div>
                                            </div>
                                            <div class="field each-input">
                                                <label for="billing:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?><em>*</em></label>
                                                <div class="input-box">
                                                    <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                                                </div>
                                            </div>
                                        </li>
                                        <li class="fields">
                                            <div class="field each-input">
                                                <label for="billing:country_id" class="required"><?php echo $this->__('Country') ?><em>*</em></label>
                                                <div class="dropdown">
                                                    <?php echo $this->getCountryHtmlSelect('billing') ?>
                                                </div>
                                            </div>
                                            <div class="field each-input">
                                                <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                                                <div class="input-box dropdown">
                                                    <select id="billing:region_id" name="billing[region_id]" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                                        <option value=""><?php echo $this->__('Please select') ?></option>
                                                    </select>
                                                    <script type="text/javascript">
                                                    //<![CDATA[
                                                        $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                                    //]]>
                                                    </script>
                                                    <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" />
                                                </div>
                                            </div>
                                        </li>
                                        <li class="fields">
                                            <div class="field each-input">
                                                <label for="billing:telephone" class="required"><?php echo $this->__('Telephone') ?><em>*</em></label>
                                                <div class="input-box tel-input-box">
                                                    
                                                    <!-- <input type="text" id="billing_phone_no" class="phone_no_input" onchange="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);">                                 -->
                                                    <!-- <input type="text" id="billing_phone_no_2" onchange="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);">                                 -->

                                                    <!-- <div class="hide-input"> -->
                                                        <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) . " " ?>" title="<?php echo $this->__('Telephone') ?>" class="remove-input-selection input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" />                                    
                                                    <!-- </div> -->
                                                    
                                                </div>
                                            </div>
                                            <div class="field each-input">
                                                <label for="billing:fax"><?php echo $this->__('Fax') ?></label>
                                                <div class="input-box tel-input-box">
                                                    <!-- <input type="text" id="billing_fax_no" class="phone_no_input" onchange="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);">                                 -->
                                                    <!-- <input type="text" id="billing_fax_no_2" onchange="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);">    -->
                                                    
                                                    <!-- <div class="hide-input"> -->
                                                        <input type="text" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) . " " ?>" title="<?php echo $this->__('Fax') ?>" class="remove-input-selection input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="billing:fax" onkeyup="if(document.getElementById('shipping:same_as_billing').checked) shipping.setSameAsBilling(true);" />
                                                    <!-- </div> -->
                                                </div>
                                            </div>
                                        </li>
                                        <?php if(!$this->isCustomerLoggedIn()): ?>

                                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                                    <?php if (false && ($_dob->isEnabled() || $_gender->isEnabled())): // we don't need these fields in checkout steps ?>
                                        <li class="fields">
                                        <?php if ($_dob->isEnabled()): ?>
                                            <div class="field each-input">
                                                <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($_gender->isEnabled()): ?>
                                            <div class="field each-input">
                                                <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                            </div>
                                        <?php endif ?>
                                        </li>
                                    <?php endif ?>

                                    <?php if ($this->isTaxvatEnabled()):?>
                                        <li><?php echo $this->getTaxvatHtml() ?></li>
                                    <?php endif; ?>

                                        <li class="fields" id="register-customer-password">
                                            <div class="field each-input">
                                                <!-- <label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label> -->
                                                <!-- <div class="input-box">
                                                    <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                                                </div> -->
                                            </div>
                                            <div class="field each-input">
                                                <!-- <label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label> -->
                                                <!-- <div class="input-box">
                                                    <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                                                </div> -->
                                            </div>
                                        </li>
                                        <?php //echo $this->getChildHtml('persistent.remember.me'); ?>
                                        <?php endif; ?>
                                        <hr class="billing-shipping-checkbox-separator">
                                        <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                                            <li class="control same-as-billing save-in-address-book">
                                                <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onkeyup="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                                                <label for="billing:save_in_address_book" class="checkbox-label">
                                                    <span></span><p class="label-text"><?php echo $this->__('Save in address book') ?></p>
                                                </label>                            
                                            </li>                        
                                        <?php else:?>
                                            <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                                        <?php endif; ?>
                                            <li class="same-as-billing">
                                                <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox same-as-billing-checkbox" />
                                                <label class="checkbox-label" for="shipping:same_as_billing">
                                                    <span></span><p class="label-text"><?php echo $this->__('If billing and shipping addresses are the same, tick here') ?></p>
                                                </label>   
                                            </li>
                                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                                    </ul>
                                    <?php //echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                                 </li>             
                                </ul>
                                <?php if (!$this->canShip()): ?>
                                    <input type="hidden" name="billing[use_for_shipping]" value="1" />
                                <?php endif; ?>
							<input type="hidden" name="billcurrentcountry" id="billcurrentcountry" value="" />
                            </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div id="page-shopping-cart-shipping-container">
                        <h1><?php echo $this->__('Shipping Address')?></h1>
                        <hr class="small" />

                        <ul class="form-list">
                        <?php if ($this->customerHasAddresses()): ?>
                           <li class="wide each-input dropdown-address">
                               <label for="shipping-address-select"><?php echo $this->__('Select your shipping address') ?></label>
                               <div class="input-box dropdown">
                                   <?php //echo $this->getAddressesHtmlSelect('shipping') ?>
                                   <div id="custAddress">
                                    <?php $customerId = Mage::getSingleton('customer/session')->getCustomer();?>    
                                    <?php $customer = Mage::getModel('customer/customer')->load($customerId->getId()); ?>
                                    <?php $data = array();?>
                                        <select name="shipping_address_id" id="shipping-address-select" class="address-select" title="">                                
                                            <option value="">New Address</option>                                                                                       
                                            <?php $i=0; foreach ($customer->getAddresses() as $address):?>                                
                                                <?php $data = $address->toArray();?>
                                                <?php $country_name = Mage::app()->getLocale()->getCountryTranslation($data['country_id']);?>                                    
                                                <option <?php if($i==0): ?>selected="selected"<?php endif; ?> value="<?php echo $data['entity_id']; ?>"><?php echo $data['firstname'] . ' ' . $data['firstname'] . ', ' . $data['street'] . ', ' . $data['city'] . ', ' . $data['postcode']. ', ' . $country_name;  ?></option>
                                            <?php $i++; endforeach; ?>  
                                        </select>
                                     </div>  
                               </div>
                           </li>
                        <?php endif ?>                
                            <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
                                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                                <ul>
                                    <li class="fields">
                                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')
                                            ->setTemplate('miragedesign/customer/widget/name.phtml')
                                            ->toHtml()
                                        ?>
                                    </li>
                                    <li class="fields">
                                        <!-- <div class="fields each-input">
                                            <label for="shipping:company"><?php echo $this->__('Company') ?></label>
                                            <div class="input-box">
                                                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
                                            </div>
                                        </div> -->
                                        <?php if(!$this->isCustomerLoggedIn()): ?>
                                        <div class="field each-input">
                                            <label for="shipping:email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                                            <div class="input-box">
                                                <input type="text" name="shipping[email]" id="shipping:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                                            </div>
                                        </div>
                                        <?php endif; ?>
                                    </li>
                            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                                    <li class="fields each-input">
                                        <label for="shipping:street1" class="required"><?php echo $this->__('Address') ?><em>*</em></label>
                                        <div class="input-box">
                                            <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                                        </div>
                                    </li>
                            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                    <li class="fields each-input">
                                        <label></label>
                                        <div class="input-box">
                                            <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                                        </div>
                                    </li>
                            <?php endfor; ?>
                                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                                    <li class="fields each-input">
                                        <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                                        <div class="input-box">
                                            <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                                        </div>
                                    </li>
                                    <?php endif; ?>
                                    <li class="fields">
                                        <div class="field each-input">
                                            <label for="shipping:city" class="required"><?php echo $this->__('City') ?><em>*</em></label>
                                            <div class="input-box">
                                                <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
                                            </div>
                                        </div>
                                        <div class="field each-input">
                                            <label for="shipping:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?><em>*</em></label>
                                            <div class="input-box">
                                                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="fields">
                                        <div class="field each-input">
                                            <label for="shipping:country_id" class="required"><?php echo $this->__('Country') ?><em>*</em></label>
                                            <div class="dropdown">
                                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                                            </div>
                                        </div>
                                        <div class="field each-input">
                                            <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                                            <div class="input-box dropdown">
                                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                                    <option value=""><?php echo $this->__('Please select') ?></option>
                                                </select>
                                                <script type="text/javascript">
                                                //<![CDATA[
                                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                                //]]>
                                                </script>
                                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" onchange="shipping.setSameAsBilling(false);" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="fields">
                                        <div class="field each-input">
                                            <label for="shipping:telephone" class="required"><?php echo $this->__('Telephone') ?><em>*</em></label>
                                            <div class="input-box tel-input-box">
                                                <!-- <input type="text" id="shipping_phone_no" class="phone_no_input">                                 -->
                                                <!-- <input type="text" id="shipping_phone_no_2"> -->
                                                <!-- <div class="hide-input"> -->
                                                    <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) . " " ?>" title="<?php echo $this->__('Telephone') ?>" class="remove-input-selection input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
                                                <!-- </div> -->
                                            </div>
                                        </div>
                                        <div class="field each-input">
                                            <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
                                            <div class="input-box tel-input-box">
                                                <!-- <input type="text" id="shipping_fax_no" class="phone_no_input">                                 -->
                                                <!-- <input type="text" id="shipping_fax_no_2">    -->
                                                
                                                <!-- <div class="hide-input"> -->
                                                    <input type="text" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) . " " ?>" title="<?php echo $this->__('Fax') ?>" class="remove-input-selection input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
                                                <!-- </div>                                     -->
                                            </div>
                                        </div>
                                    </li>
                                    <hr class="billing-shipping-checkbox-separator">
                                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                                    <li class="control same-as-billing save-in-address-book">
                                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                                        <label for="shipping:save_in_address_book" class="checkbox-label">
                                            <span></span><p class="label-text"><?php echo $this->__('Save in address book') ?></p>
                                        </label>
                                    </li>
                                <?php else:?>
                                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                                <?php endif;?>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <input type="hidden" name="md_shipping_method" id="md_shipping_method" value="" />
			<?php 
			$checkout = Mage::getSingleton('checkout/session')->getQuote();
			$billAddress = $checkout->getShippingAddress();
			$countryId = $billAddress->getData('country_id');
			$groupname = '';
			if(Mage::getSingleton('customer/session')->isLoggedIn()) {
				$customerData = Mage::getSingleton('customer/session')->getCustomer();
				$customerGroupId = $customerData->getGroupId();
				$groupname = Mage::getModel('customer/group')->load($customerGroupId)->getCustomerGroupCode();  
			} 
			
			$tradselfcollect = 0;
			//$sessiontemp = Mage::getSingleton('checkout/session');
			//$tradselfcollect = $sessiontemp->getData('traderselfcollect');
			
			/*$oCheckoutnew = Mage::getSingleton( 'checkout/session' );
			$oQuotenew = $oCheckoutnew->getQuote();
			$tradselfcollect = $oQuotenew->getTraderselfcollect();*/
			
			//$tradselfcollect = Mage::app()->getRequest()->getParam('tsc');
			
			$curlpath = basename($_SERVER['REQUEST_URI']);			
			$parts = parse_url($curlpath);
			parse_str($parts['query'], $query);	
			$tradselfcollect = $query['tsc']['tsc'];			
			?>
			<?php //if(($groupname=='Trader-Temp' || $groupname=='Trader-Regular' || $groupname=='Trader-Priority' || $groupname=='Trader-Premium')&&($countryId=='SG' || $countryId=='sg')): 
			if($groupname=='Trader-Temp' || $groupname=='Trader-Regular' || $groupname=='Trader-Priority' || $groupname=='Trader-Premium'):
			?>
				<div class="selfcollect">
                    <div class="row">
    					<div class="col-md-6">
                            <label for="billing:traderselfcollect"><?php echo $this->__('Self Collection:') ?></label>
                            <div class="selfcollect-option">        						
    							<input type="radio" onclick="traderselfcollectyesno('traderselfcollectyes','traderselfcollectno');" id="traderselfcollectno" name="traderselfcollect" value="0" <?php if($tradselfcollect != 1 && $tradselfcollect != '1'){echo 'checked';} ?> /><label for="traderselfcollectno"><span></span>No</label>
                            </div>
                            <div class="selfcollect-option">
							     <input type="radio" onclick="traderselfcollectyesno('traderselfcollectno','traderselfcollectyes');" id="traderselfcollectyes" name="traderselfcollect" value="1" <?php if($tradselfcollect ==1 || $tradselfcollect == '1'){echo 'checked';} ?> /><label for="traderselfcollectyes"><span></span>Yes</label>
                            </div>
							<input type="hidden" id="billing:selfcollecthidden" name="custom[selfcollecthidden]" value="0" />
    					</div>
                    </div>
				</div></br>
			 <?php endif; ?>
        </form>        
    </div><!-- #page-shopping-cart-billing-shipping-container -->
    <div id="page-shopping-cart-billing-shipping-delivery-information">
        <h2><?php echo $this->__('DELIVERY') ?></h2>
        
        <div id="billing_shipping">
             <div class="row">
                <div class="col-md-6">
                    <div id="page-shopping-cart-billing-shipping-delivery-information-01">
                        <div class="delivery-rates">
                              <div class="each-input">
                                <label>COUNTRY</label>
                                <div class="input-text">
                                  <p>Singapore</p>
                                </div>
                              </div>
                              <div class="each-input">
                                <label>ESTIMATED DELIVERY TIME</label>
                                <div class="input-text">
                                  <p>2 to 3 working days</p>
                                </div>
                              </div>
                              <div class="each-input">
                                <label>RATE</label>
                                <div class="input-text">
                                  <div style="display:none;">
                                    <span class="no-display"><input name="shipping_method" type="radio" value="customrate_customrate_free" id="s_method_customrate_customrate_free" checked="checked"></span>
                                    <label for="s_method_customrate_customrate_free">
                                        FREE SHIPPING <span class="price">S$ 6.00</span>
                                    </label>
                                  </div>
                                  <p class="flat_rate"><span class="price">S$ 6.00</span></p>
                                </div>
                              </div>                            
                        </div>                        
                    </div>
                </div>
                <div class="col-md-6">
                    <div id="page-shopping-cart-billing-shipping-delivery-information-02">
                        <p>All local orders are delivered via Singapore Post registered mail or Speedpost depending on size of order.</p>
                        <p>All products are shipped directly from Singapore. Please allow 3 to 5 working days on top of the estimated delivery time for us to process your order.</p>
                        <p>Please expect slight delays for orders shipped during peak seasons. <br />
                        <span>— Chinese New Year, Christmas etc.</span></p>
                    </div> 
                </div>
            </div>
        </div>
       
        <div id="page-shopping-cart-cta-container">
            <div class="buttons-set row action-container" id="billing-buttons-container">
                <!-- <p class="required"><?php echo $this->__('* Required Fields') ?></p> -->
                <div class="back-link col-md-4">
                    <a class="cta back-btn" href="<?php echo $this->getUrl('store.html'); ?>"><i class="fa fa-chevron-left"></i> <?php echo $this->__('go back to continue shopping') ?></a>
                </div>
                <div class="col-md-4 col-md-offset-4">
                    <button type="button" id="continue-to-checkout" title="<?php echo $this->__('Continue') ?>" class="button continue cta"><span><span><?php echo $this->__('Continue') ?></span></span></button>
                    <span class="please-wait" id="billing-please-wait" style="display:none;">
                        <img src='<?php echo $this->getSkinUrl('images/icons/spin.svg')?>'/>
                        <!-- <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> --> <?php //echo $this->__('Loading next step...') ?>
                    </span>
                </div>
            </div>    
        </div>
        <?php 
            $allskus = array("SGP-ART-1M", "SGP-ART-3M", "SGP-ART-6M", "SGP-ART-12M", "SGP-GUR-1M", "SGP-GUR-3M", "SGP-GUR-6M", "SGP-GUR-12M","INT-ART-1M", "INT-ART-3M", "INT-ART-6M", "INT-ART-12M", "INT-GUR-1M", "INT-GUR-3M", "INT-GUR-6M", "INT-GUR-12M"); 
            $cart = Mage::getModel('checkout/cart')->getQuote(); $subscription_in_cart = false;
            foreach ($cart->getAllItems() as $item):
                $added_sku = $item->getProduct()->getSku();
                if(in_array($added_sku, $allskus)) {
                    $subscription_in_cart = true;             
                }
            endforeach; 
        ?>
        <div id="question" style="display:none; cursor: default">            
            <h3>How would you like to check out?</h3>                       
            <?php if($subscription_in_cart): ?>
                <a class="square-cta" href="<?php echo Mage::helper('customer')->getRegisterUrl(); ?>" id="yes">Create New Account</a>
            <?php else: ?>
                <a class="square-cta" href="#" id="no">Continue As Guest</a>
            <?php endif; ?>
            <a class="square-cta" href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>" id="yes">Sign Into Your Account</a>            
        </div> 
		
    <script>
	function setCookie(cname, cvalue, exdays) {
		var d = new Date();
		d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
		var expires = "expires="+d.toUTCString();
		document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
	}

	function getCookie(cname) {
		var name = cname + "=";
		var ca = document.cookie.split(';');
		for(var i = 0; i < ca.length; i++) {
			var c = ca[i];
			while (c.charAt(0) == ' ') {
				c = c.substring(1);
			}
			if (c.indexOf(name) == 0) {
				return c.substring(name.length, c.length);
			}
		}
		return "";
	}
        jQuery(document).ready(function($){       

            <?php if(!$this->isCustomerLoggedIn()): ?>

                if(typeof(Storage) !== "undefined") {                    

                    if(localStorage.getItem("inputValue") === null) {                                

                        <?php if($isiPad): ?>
                            $.blockUI({ 
                                message: $('#question'),             
                                css: { 
                                    padding:        '10px', 
                                    margin:         0,
                                    width:          '50.02%',
                                    height:         '280px',
                                    top:            '35%',
                                    left:           '26%',                        
                                    textAlign:      'center', 
                                    color:          '#f1efee', 
                                    border:         '10px', 
                                    backgroundColor:'#7b706b',
                                    cursor:         'wait',                        
                                },
                            });
                        <?php elseif(isMobile()!==true): ?>
                            $.blockUI({ 
                                message: $('#question'),             
                                css: { 
                                    padding:        '10px', 
                                    margin:         0, 
                                    width:          '28%', 
                                    height:         '280px', 
                                    top:            '35%',
                                    left:           '39%',                
                                    textAlign:      'center', 
                                    color:          '#f1efee', 
                                    border:         '10px', 
                                    backgroundColor:'#7b706b',
                                    cursor:         'wait' 
                                },
                            });
                        <?php else: ?>
                            $.blockUI({ 
                                message: $('#question'),             
                                css: { 
                                    padding:        '10px', 
                                    margin:         0, 
                                    width:          '90%', 
                                    height:         '280px', 
                                    top:            '27%',
                                    left:           '5%',                
                                    textAlign:      'center', 
                                    color:          '#f1efee', 
                                    border:         '10px', 
                                    backgroundColor:'#7b706b',
                                    cursor:         'wait' 
                                },
                            });                    
                        <?php endif; ?>

                    } else {

                        var storedValue = JSON.parse(localStorage.getItem( 'inputValue' ));

                        console.log(storedValue);

                        $.each(storedValue, function(key, value){

                            if(key=="billing[country_id]" || key=="shipping[country_id]")
                                $("select[name='"+key+"']").val(value);     
                            else if(key=="shipping[same_as_billing]") {
                                $("input[name='"+key+"']").val(1);
                                if(value==1) {                   
                                    console.log(value);               
                                    console.log('heererer');               
                                    $(".same-as-billing-checkbox").attr('checked', true);
                                }                                
                            }
                            else 
                                $("input[name='"+key+"']").val(value);
                        });
                    }

                } else {

                    <?php if($isiPad): ?>
                        $.blockUI({ 
                            message: $('#question'),             
                            css: { 
                                padding:        '10px', 
                                margin:         0,
                                width:          '50.02%',
                                height:         '280px',
                                top:            '35%',
                                left:           '26%',                        
                                textAlign:      'center', 
                                color:          '#f1efee', 
                                border:         '10px', 
                                backgroundColor:'#7b706b',
                                cursor:         'wait',                        
                            },
                        });
                    <?php elseif(isMobile()!==true): ?>
                        $.blockUI({ 
                            message: $('#question'),             
                            css: { 
                                padding:        '10px', 
                                margin:         0, 
                                width:          '28%', 
                                height:         '280px', 
                                top:            '35%',
                                left:           '39%',                
                                textAlign:      'center', 
                                color:          '#f1efee', 
                                border:         '10px', 
                                backgroundColor:'#7b706b',
                                cursor:         'wait' 
                            },
                        });
                    <?php else: ?>
                        $.blockUI({ 
                            message: $('#question'),             
                            css: { 
                                padding:        '10px', 
                                margin:         0, 
                                width:          '90%', 
                                height:         '280px', 
                                top:            '27%',
                                left:           '5%',                
                                textAlign:      'center', 
                                color:          '#f1efee', 
                                border:         '10px', 
                                backgroundColor:'#7b706b',
                                cursor:         'wait' 
                            },
                        });                    
                    <?php endif; ?>

                }

                $('#no').click(function(e) {
                    e.preventDefault();
                    $.unblockUI(); 
                    return false; 
                });

            <?php endif; ?>        

            
            var $billing_telephone = $('input[name="billing[telephone]"]');
            $billing_telephone.intlTelInput({                
                initialCountry: 'sg',
                nationalMode: false,
                autoHideDialCode: false,
                autoPlaceholder: false,
                preferredCountries: []                
            });

            var currentCountryCode  = "";
            $(document).keydown(function(e) {
                var aEl = $(document.activeElement);

                if(aEl.attr('name') == "billing[telephone]" || aEl.attr('name') == "billing[fax]" || aEl.attr('name') == "shipping[telephone]" || aEl.attr('name') == "shipping[fax]") {
                    var currentInputLength = aEl.val().length;       
                    var dialCode = aEl.intlTelInput("getSelectedCountryData").dialCode;         
                    
                    if(typeof dialCode !== "undefined") {
                        currentCountryCode = aEl.intlTelInput("getSelectedCountryData").dialCode;
                    }                      

                    var currentCountryCodeCount = currentCountryCode.toString().length + 3;

                    if ((e.keyCode === 8 || e.keyCode ===46) && currentInputLength < currentCountryCodeCount) 
                        return false;
                }                
            });
            
            var $shipping_telephone = $('input[name="shipping[telephone]"]');
            $shipping_telephone.intlTelInput({                
                initialCountry: 'sg',
                nationalMode: false,
                autoHideDialCode: false,
                autoPlaceholder: false,
                preferredCountries: []                
            });

            var $billing_fax = $('input[name="billing[fax]"]');
            $billing_fax.intlTelInput({                
                initialCountry: 'sg',
                nationalMode: false,
                autoHideDialCode: false,
                autoPlaceholder: false,
                preferredCountries: []                
            });

            var $shipping_fax = $('input[name="shipping[fax]"]');
            $shipping_fax.intlTelInput({                
                initialCountry: 'sg',
                nationalMode: false,
                autoHideDialCode: false,
                autoPlaceholder: false,
                preferredCountries: []                
            });            

            $('select[name="billing[country_id]"]').on('change', function(e){
                e.preventDefault();

                if(document.getElementById('shipping:same_as_billing').checked)
                    shipping.setSameAsBilling(true);

                var country = $(this).val();

                $billing_telephone.intlTelInput("setCountry", country);
                $billing_fax.intlTelInput("setCountry", country);

            });

            $('select[name="shipping[country_id]"]').on('change', function(e){
                e.preventDefault();

                var country = $(this).val();

                $shipping_telephone.intlTelInput("setCountry", country);
                $shipping_fax.intlTelInput("setCountry", country);

            });

            $("#continue-to-checkout").on("click", function(e){
                e.preventDefault();

                if (typeof(Storage) !== "undefined") {
                    var $inputs = $("#billing-new-address-form").find("input, select");
                    var $shipping_inputs = $("#shipping-new-address-form").find("input, select");
                    var inputValue = {};

                    $inputs.each(function(){
                        var value = $(this).val();
                        var name = $(this).attr('name');

                        if(name=="shipping[same_as_billing]") {
                            console.log($(this).is(':checked'))
                            if($(this).is(':checked')===false) {
                                value = 'no';
                            }else value = 1;
                        }
                        
                        if(value!="") {
                            inputValue[name] = value;
                        }                                            
                    });

                    $shipping_inputs.each(function(){
                        var value = $(this).val();
                        var name = $(this).attr('name');
                        
                        if(value!="") {
                            inputValue[name] = value;
                        }                                            
                    });

                    console.log( inputValue );

                    localStorage.removeItem('inputValue');
                    localStorage.setItem( 'inputValue', JSON.stringify(inputValue) );
                    var storedValue = JSON.parse(localStorage.getItem( 'inputValue' ));

                    console.log(storedValue);
                }

                billing.save();                
            });
            
        });
    </script>               

    <script type="text/javascript">
    //<![CDATA[
        var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
        var billingForm = new VarienForm('co-billing-form');

        var GetBillingAddressUrl = '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/';

        //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
        $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

        var billingRegionUpdater = new CustomRegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
        if ($('onepage-guest-register-button')) {
            Event.observe($('onepage-guest-register-button'), 'click', function(event) {
                var billingRememberMe = $('co-billing-form').select('#remember-me-box');
                if (billingRememberMe.length > 0) {
                    if ($('login:guest') && $('login:guest').checked) {
                        billingRememberMe[0].hide();
                    } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                        billingRememberMe[0].show();
                    }
                }
            });
        }

        var shipping = new Customshipping('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
            '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
        var shippingForm = new VarienForm('co-billing-form');
        shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';

        //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');

        $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

        var shippingRegionUpdater = new CustomRegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');


        $j('#billing-address-select').on("change", function(){
            if($j(this).val()=="") {
                $j('#page-shopping-cart-billing-container').find('.save-in-address-book').show();
            }else {
                $j('#page-shopping-cart-billing-container').find('.save-in-address-book').hide();
            }
			//var countryIDdd = '<?= Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getData('country_id') ?>';
			//jQuery('.selfcollect')[countryIDdd == 'SG' ? 'show' : 'hide']();
        });

        $j('#shipping-address-select').on("change", function(){//alert('k');
            if($j(this).val()=="") {
                $j('#page-shopping-cart-shipping-container').find('.save-in-address-book').show();
            }else {
                $j('#page-shopping-cart-shipping-container').find('.save-in-address-book').hide();
                $j(".same-as-billing-checkbox").attr('checked', false);
            }
			var countryIDdd = $j('#shipping\\:country_id').val();//alert(countryIDdd);
			jQuery('.selfcollect')[countryIDdd == 'SG' ? 'show' : 'hide']();
        });
		
		/*var currentCountryIdload = $j('#billing:country_id').val();    
		jQuery('.selfcollect')[currentCountryIdload == 'SG' ? 'show' : 'hide']();*/
			
		$j('#shipping\\:country_id').on("change", function(){//alert('k');
			var currentCountryId = $j(this).val();   //alert(currentCountryId); 
			jQuery('.selfcollect')[currentCountryId == 'SG' ? 'show' : 'hide']();
        });
		
		$j( document ).ready(function() {
			//alert( "ready!" );
			var currentCountryIdLoad = $j('#shipping\\:country_id').val();   //alert(currentCountryIdLoad); 
			jQuery('.selfcollect')[currentCountryIdLoad == 'SG' ? 'show' : 'hide']();
		});
		
		
		
		
		$j( document ).ready(function() {
			
		if(window.location.href.indexOf("tsc") > -1) {
		var uurlStringkk = window.location.href.split('?')[1];//alert(uurlStringkk);
		if (typeof uurlStringkk !== "undefined") {
			var resQyertkk = uurlStringkk.split("=");
			var curCId = resQyertkk[1];
			if(curCId == '1'){
				jQuery("#s_method_freeshipping_freeshipping").attr('checked', true);				
				jQuery('.selfcollect').show();
				//$j(".validate-select").val('SG');
			}
			//alert(curCId);
		}

		var bfirstname = getCookie("bfirstname");
		var bmiddlename = getCookie("bmiddlename");
		var blastname = getCookie("blastname");
		var bstreet1 = getCookie("bstreet1");
		var bstreet2 = getCookie("bstreet2");
		var bcity = getCookie("bcity");
		var bpostcode = getCookie("bpostcode");
		var bcountry_id = getCookie("bcountry_id");
		var bregion = getCookie("bregion");
		var btelephone = getCookie("btelephone");
		var bfax = getCookie("bfax");
		
		jQuery("#billing\\:firstname").val(bfirstname);
		jQuery("#billing\\:middlename").val(bmiddlename);
		jQuery("#billing\\:lastname").val(blastname);
		jQuery("#billing\\:street1").val(bstreet1);
		jQuery("#billing\\:street2").val(bstreet2);
		jQuery("#billing\\:city").val(bcity);
		jQuery("#billing\\:postcode").val(bpostcode);
		jQuery("#billing\\:country_id").val(bcountry_id);
		jQuery("#billing\\:region").val(bregion);
		jQuery("#billing\\:telephone").val(btelephone);
		jQuery("#billing\\:fax").val(bfax);	
		
		var sfirstname = getCookie("sfirstname");
		var smiddlename = getCookie("smiddlename");
		var slastname = getCookie("slastname");
		var sstreet1 = getCookie("sstreet1");
		var sstreet2 = getCookie("sstreet2");
		var scity = getCookie("scity");
		var spostcode = getCookie("spostcode");
		var scountry_id = getCookie("scountry_id");
		var sregion = getCookie("sregion");
		var stelephone = getCookie("stelephone");
		var sfax = getCookie("sfax");
		
		jQuery("#shipping\\:firstname").val(sfirstname);
		jQuery("#shipping\\:middlename").val(smiddlename);
		jQuery("#shipping\\:lastname").val(slastname);
		jQuery("#shipping\\:street1").val(sstreet1);
		jQuery("#shipping\\:street2").val(sstreet2);
		jQuery("#shipping\\:city").val(scity);
		jQuery("#shipping\\:postcode").val(spostcode);
		jQuery("#shipping\\:country_id").val(scountry_id);
		jQuery("#shipping\\:region").val(sregion);
		jQuery("#shipping\\:telephone").val(stelephone);
		jQuery("#shipping\\:fax").val(sfax);

		
		}
		
		/*var uurlString = window.location.href.split('?')[1];
		
		var resQyert = uurlString.split("&c=");
		var curContryId = resQyert[1];
		
		var resQyertzero = resQyert[0];
		var resQyerttsc = resQyertzero.split("tsc=");
		var tscflag = resQyerttsc[1];
		//alert(tscflag);
		/*	$j(".validate-select > option").each(function() {
				alert($j(this).val());
				return ($j(this).value == curContryId);
			}).prop('selected', true);*/
			
		//$j(".validate-select").val(curContryId);
		/*if(tscflag == 1){
			jQuery("#s_method_freeshipping_freeshipping").attr('checked', true);
		}
		jQuery('.selfcollect')[curContryId == 'SG' ? 'show' : 'hide']();*/
		});
		//$j('.myclass option:selected').filter("[value=audi]")

		/*$j('[class=validate-select] option').filter(function() { 
			return ($(this).text() == 'Blue'); //To select Blue
		}).prop('selected', true); */
		
                
    //]]>
	
	function traderselfcollectyesno(idd,iddd){
		//alert(idd);
		jQuery("#"+idd).removeAttr('checked');
		
		var tsr = jQuery("#"+iddd).val();
		//alert(tsr);alert(iddd);
		if(tsr == 1){
			jQuery("#billing\\:selfcollecthidden").val(1);
			jQuery("#s_method_freeshipping_freeshipping").attr('checked', true);
		}else{
		
		}
		jQuery("#"+iddd).attr('checked', true);
		
		//window.location.href = window.location.href + "?tsc="+tsr;
		//billing.save();		
		//location.reload();
		
		// save billing and shipping address in cookie
		
		setCookie("bfirstname", jQuery("#billing\\:firstname").val(), 365);
		setCookie("bmiddlename", jQuery("#billing\\:middlename").val(), 365);
		setCookie("blastname", jQuery("#billing\\:lastname").val(), 365);
		setCookie("bstreet1", jQuery("#billing\\:street1").val(), 365);
		setCookie("bstreet2", jQuery("#billing\\:street2").val(), 365);
		setCookie("bcity", jQuery("#billing\\:city").val(), 365);
		setCookie("bpostcode", jQuery("#billing\\:postcode").val(), 365);
		setCookie("bcountry_id", jQuery("#billing\\:country_id").val(), 365);
		setCookie("bregion", jQuery("#billing\\:region").val(), 365);
		setCookie("btelephone", jQuery("#billing\\:telephone").val(), 365);
		setCookie("bfax", jQuery("#billing\\:fax").val(), 365);	
		
		setCookie("sfirstname", jQuery("#shipping\\:firstname").val(), 365);
		setCookie("smiddlename", jQuery("#shipping\\:middlename").val(), 365);
		setCookie("slastname", jQuery("#shipping\\:lastname").val(), 365);
		setCookie("sstreet1", jQuery("#shipping\\:street1").val(), 365);
		setCookie("sstreet2", jQuery("#shipping\\:street2").val(), 365);
		setCookie("scity", jQuery("#shipping\\:city").val(), 365);
		setCookie("spostcode", jQuery("#shipping\\:postcode").val(), 365);
		setCookie("scountry_id", jQuery("#shipping\\:country_id").val(), 365);
		setCookie("sregion", jQuery("#shipping\\:region").val(), 365);
		setCookie("stelephone", jQuery("#shipping\\:telephone").val(), 365);
		setCookie("sfax", jQuery("#shipping\\:fax").val(), 365);
		
		
		$uurl = window.location.href.split('?')[0];
		//window.location.href = $uurl + "?tsc="+tsr+"&c="+$j('.validate-select').val();
		window.location.href = $uurl + "?tsc="+tsr;
		$j('#billcurrentcountry').val($j('.validate-select').val());
	
	}
		
    </script>
    </div>
</div>
    