<?php
/**
 * Gift Card select in Checkout cart page
 */
?>

<?php 
$groupname = '';
if(Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customerData = Mage::getSingleton('customer/session')->getCustomer();
    $customerGroupId = $customerData->getGroupId();
    $groupname = Mage::getModel('customer/group')->load($customerGroupId)->getCustomerGroupCode();  
} 
?>
<?php if($groupname!='Trader-Temp' && $groupname!='Trader-Regular' && $groupname!='Trader-Priority' && $groupname!='Trader-Premium'): ?>

<?php // echo $this->getCouponHtml() ?>
<?php $store_Id = Mage::app()->getStore()->getId(); ?>
<?php if ( Mage::helper('giftvoucher')->getGeneralConfig('active', $store_Id) && Mage::helper('giftvoucher')->getInterfaceCheckoutConfig('show_gift_card', $store_Id)): ?>

<?php $_code = 'giftvoucher' ?>
<?php $_giftCards = $this->getExistedGiftCard() ?>
<div class="form-group">
<form id="discount-giftcard-form" class="checkout-form" action="<?php echo $this->getUrl('giftvoucher/checkout/giftcardPost') ?>" method="post" autocomplete="off">
    <div class="discount">
        <!-- <h2><?php echo $this->__('Gift Card') ?></h2> -->
        <div class="discount-form">
            <?php
            $cart = Mage::getSingleton('checkout/session');
            $count = 0;
            $items = $cart->getQuote()->getAllItems();
            foreach ($items as $item) {
                $data = $item->getData();
                if ($data['product_type'] == 'giftvoucher') {
                    $count++;
                }    
            }
            ?>
            <?php if ($count > 0): ?>
                <ul>
                    <li class="message">
                        <ul class="notice-msg">
                            <li><?php //echo $this->__('Gift Cards cannot be used to purchase Gift Card products') ?></li>
                        </ul>
                    </li>
                </ul>
            <?php endif; ?>   
            <dl id="<?php echo $_code ?>_container" style="<?php if ($count == count($items)) echo 'display:none'; ?>">
                <?php if (Mage::helper('giftvoucher')->getGeneralConfig('enablecredit')): ?>
                    <?php if ($_customerCredit = $this->getCustomerCredit()): ?>
                        <dt class="<?php echo $_code ?>_credit" style="display:none;">
                        <input type="checkbox" name="<?php echo $_code ?>_credit" id="<?php echo $_code ?>_credit"<?php if ($this->getUseGiftCredit()): ?> checked="checked"<?php endif ?> value="1" onclick="showCartCreditInput(this)" />
                        <label for="<?php echo $_code ?>_credit" style="font-weight: bold; color: #666;"><?php echo $this->__('Use Gift Card credit to check out (%s)', $this->formatBalance($_customerCredit, true)) ?></label>
                        </dt>
                        <dd class="<?php echo $_code ?>_credit"<?php if (!$this->getUseGiftCredit()): ?> style="display: none;"<?php else: ?>style="display: none;"<?php endif ?>>
                            <div>
                                <label>
                                    <?php echo $this->__('Store Credits') ?>
                                </label>      
                                <div class="input-box">
                                    <input class="input-text" type="text" value="<?php //echo $this->getUseGiftCreditAmount() ?>" title="<?php echo $this->__('Credit') ?>" name="credit_amount" />     
                                </div>                                          
                                <button class="form-button-alt button cta apply apply_giftcard" type="button">
                                    <span><span><?php echo $this->__('Apply') ?></span></span>
                                </button>    
                                <span class="points"><?php echo $this->__('Accumulated Credits : %s', $this->formatBalance($_customerCredit, true)) ?></span>       
                            </div>
                            <div style="color: #A70101;padding-left: 174px;margin-top: 7px;font-size: 11px;font-weight: bold;line-height: 13px; display:none" id="giftcredit_notice"><?php echo $this->__('Please change amount')?></div>
                            <br />
                        </dd>
                    <?php endif ?>
                <?php endif ?>
                <dt class="<?php echo $_code ?>" style="display:none;">
                <input type="checkbox" name="<?php echo $_code ?>" id="<?php echo $_code ?>"<?php if ($this->getUseGiftVoucher()): ?> checked="checked"<?php endif ?> value="1" onclick="showCartGiftCardInput(this)" />
                <label for="<?php echo $_code ?>" style="font-weight: bold; color: #666;"><?php echo $this->__('Use Gift Card to check out') ?></label>
                </dt>
                <dd class="<?php echo $_code ?>" <?php if (!$this->getUseGiftVoucher()): ?> style="display: none;"<?php endif ?>>                
                    <div class="form-list" id="payment_form_<?php echo $_code ?>">
                        <div class="giftvoucher-description">
                            <?php // echo $this->getDescription() ?>
                        </div>
                        <?php $discounts = $this->getGiftVoucherDiscount() ?>
                        <?php if (count($discounts)): ?>
                            <!--<ul class="messages">
                                <?php foreach ($discounts as $code => $discount): ?>
                                    <?php if($discount <=0): ?>
                                        <li class="notice-msg">
                                            <ul><li><span><?php echo Mage::helper('giftvoucher')->__('Gift code "%s" hasn\'t been used yet.', Mage::helper('giftvoucher')->getHiddenCode($code)) ?></span></li></ul>
                                        </li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>-->
                            <div class="giftvoucher-discount-code" style="display:none;">
                                <ul>
                                    <?php foreach ($discounts as $code => $discount): ?>
                                        <?php
                                        if($discount <= 0){
//                                            $session = Mage::getSingleton('checkout/session');
//                                            $codesArray = array_unique(explode(',', $session->getGiftCodes()));
//                                            foreach($codesArray as $key => $val){
//                                                if($val == $code){
//                                                    unset($codesArray[$key]);
//                                                    $codes = implode(',', array_unique($codesArray));
//                                                    $session->setGiftCodes($codes);
//                                                }
//                                            }
                                            continue;
                                        } 
                                        ?>
                                        <li>
                                            <label for="<?php echo $code ?>">
                                                <?php echo Mage::helper('giftvoucher')->getHiddenCode($code) ?>
                                                (<span class="giftcard_change" onclick="showGiftCardAmountInput(this);
                                                                return false;" style="cursor: pointer;" title="<?php echo $this->__('Edit') ?>"><a class="giftcard-amount" href="#" onclick="return false;"><?php echo Mage::helper('checkout')->formatPrice($discount) ?></a><img src="<?php echo $this->getSkinUrl('images/btn_edit.gif') ?>" alt="<?php echo $this->__('Edit') ?>" class="ajax-loader v-middle" /></span><input class="input-text" type="text" value="<?php echo $discount ?>" title="<?php echo $this->__('Gift Card Amount') ?>" style="width: 68px; display: none;" disabled="disabled" name="giftcodes[<?php echo $code ?>]" />)
                                            </label>
                                            <a href="<?php echo $this->getUrl('giftvoucher/checkout/removegift', array('code' => $code)) ?>" id="remove_card" title="<?php echo $this->__('Remove') ?>">
                                                <img src="<?php echo $this->getSkinUrl('images/btn_remove.gif') ?>" alt="<?php echo $this->__('Remove') ?>" style="margin-left: 5px;margin-top: 3px;" />
                                            </a>
                                        </li>
                                    <?php endforeach ?>
                                </ul>
                            </div>
                        <?php endif ?>
                        <div id="<?php echo $_code ?>_message">
                            <?php if (!Mage::helper('giftvoucher')->isAvailableToAddCode()): ?>
                                <ul class="error-msg">
                                    <li><?php echo $this->__('The maximum number of times to enter Gift Card code is %d!', Mage::helper('giftvoucher')->getGeneralConfig('maximum')) ?></li>
                                </ul>
                            <?php endif ?>
                        </div>
                        <div id="giftvoucher-custom-code">
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="<?php echo $_code ?>_code"><?php echo $this->__('GIFT CERTIFICATE') ?></label>                     
                                </div>
                                <div class="col-md-8">
                                    <div class="row">
                                        <div class="col-md-8 col-sm-6 col-xs-8">
                                            <?php
                                            $customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
                                            $customer_email = Mage::getSingleton('customer/session')->getCustomer()->getEmail();

                                            $collection = Mage::getModel('giftvoucher/customervoucher')->getCollection();
                                                    // ->addFieldToFilter('main_table.customer_id', $customer_id);
                                            $voucherTable = Mage::getModel('core/resource')->getTableName('giftvoucher');
                                            $voucherHistoryTable = Mage::getModel('core/resource')->getTableName('giftvoucher_history');
                                            $collection->getSelect()
                                                    ->joinleft(array('voucher_table' => $voucherTable), 'main_table.voucher_id = voucher_table.giftvoucher_id', array('recipient_name', 'gift_code', 'balance', 'currency', 'status', 'expired_at', 'customer_check_id' => 'voucher_table.customer_id', 'recipient_email', 'customer_email'))
                                                    ->joinleft(array('voucher_history_table' => $voucherHistoryTable), 'main_table.voucher_id = voucher_history_table.giftvoucher_id', array('customer_id', 'order_increment_id'))
                                                    ->where('voucher_table.status <> ?', Magestore_Giftvoucher_Model_Status::STATUS_DELETED)
                                                    ->where('voucher_table.status <> ?', Magestore_Giftvoucher_Model_Status::STATUS_USED)
                                                    ->where('voucher_table.status <> ?', Magestore_Giftvoucher_Model_Status::STATUS_PENDING)
                                                    ->where('voucher_table.recipient_email = ?', $customer_email)
                                                    ->where('voucher_history_table.status = ?', Magestore_Giftvoucher_Model_Status::STATUS_PENDING);

                                            // $collection = Mage::getModel('giftvoucher/customervoucher')->getCollection()->addFieldToFilter('main_table.customer_id', $customer_id);
                                            // $voucherTable = Mage::getModel('core/resource')->getTableName('giftvoucher');
                                            // $collection->getSelect()->joinleft(array('voucher_table' => $voucherTable), 'main_table.voucher_id = voucher_table.giftvoucher_id', array('recipient_name', 'gift_code', 'balance', 'currency', 'status', 'expired_at', 'customer_check_id' => 'voucher_table.customer_id', 'recipient_email', 'customer_email'))->where('voucher_table.status <> ?', Magestore_Giftvoucher_Model_Status::STATUS_DELETED);

                                            $this->setCollection($collection);
                                            $this->getCollection();
                                            ?>                                
                                            <?php if ($collection->count()): ?>
                                                <input type="hidden" title="<?php echo $this->__('Gift Card Code') ?>" class="input-text" value="<?php echo $code; ?>" id="<?php echo $_code ?>_code" name="giftvoucher_code" <?php if (!Mage::helper('giftvoucher')->isAvailableToAddCode()) echo 'disabled="true"' ?> />
                                                <div class="dropdown">
                                                    <select name="select_gift_code" id="select_gift_code">
                                                    <option value="">Please select</option>
                                                    <?php foreach ($collection as $row): ?>
                                                        <option value="<?php echo $row->getGiftCode(); ?>"><?php echo $row->getGiftCode(); ?></option>
                                                    <?php endforeach; ?>
                                                    </select>
                                                </div>                                                    
                                            <?php else: ?>
                                                <div class="input-box">
                                                    <input type="text" title="<?php echo $this->__('Gift Card Code') ?>" class="input-text" value="" id="<?php echo $_code ?>_code" name="giftvoucher_code" <?php if (!Mage::helper('giftvoucher')->isAvailableToAddCode()) echo 'disabled="true"' ?> />
                                                    <!-- <?php echo $code ?> -->
                                                </div>
                                            <?php endif; ?>
                                            <div class="validation-advice" id="giftcard_notice" style="display: none;"></div>
                                        </div>
                                        <div class="col-md-4 col-sm-3 col-xs-4">
                                            <div class="cart-discount-cta-container">                
                                                <?php $discounts = $this->getGiftVoucherDiscount() ?>
                                                <?php if (count($discounts)): ?>
                                                    <button class="form-button-alt button square-cta full-width-version apply apply_giftcard" type="button">
                                                        <span><span><?php echo $this->__('Apply') ?></span></span>
                                                    </button>           
                                                    <button style="display: none;" class="form-button-alt button square-cta full-width-version apply cancel_giftcard" type="button">
                                                        <span><span><?php echo $this->__('Apply') ?></span></span>
                                                    </button>           
                                                <?php else: ?>
                                                    <button class="form-button-alt button square-cta full-width-version apply apply_giftcard" type="button">
                                                        <span><span><?php echo $this->__('Apply') ?></span></span>
                                                    </button>           
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>                            
                                                    
                        </div>
                        <?php if (count($_giftCards)): ?>
                            <!-- <div>
                                <label for="<?php echo $_code ?>_existed_code"><?php echo $this->__('or select from your existing Gift Card code(s)') ?></label>
                                <div class="input-box">
                                    <select title="<?php echo $this->__('Existed Gift Card Code') ?>" class="input-select" id="<?php echo $_code ?>_existed_code" name="existed_giftvoucher_code" <?php if (!Mage::helper('giftvoucher')->isAvailableToAddCode()) echo 'disabled="true"' ?>>
                                        <option value=""><?php echo $this->__('-- Please Select --') ?></option>
                                        <?php foreach ($_giftCards as $_giftCard): ?>
                                            <option value="<?php echo $_giftCard['gift_code'] ?>"><?php echo $_giftCard['hidden_code'] ?> (<?php echo $_giftCard['balance'] ?>)</option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div> -->
                        <?php endif ?>                            
                        <div style="display:none;">
                            <?php if ($this->checkCustomerIsLoggedIn()): ?>
                                <?php echo $this->__('To manage your Gift Card, please click <a target="_blank" href="%s">here</a>.', $this->getUrl('giftvoucher/index/index')) ?>
                            <?php else: ?>
                                <?php echo $this->__('To check your Gift card information, please click <a target="_blank" href="%s">here</a>.', $this->getUrl('giftvoucher/index/check')) ?>
                            <?php endif ?>
                        </div>
                    </div>
                </dd>
                <dt style="display: none;"></dt>
                <dd id="giftcard_shoppingcart_apply" <?php if (!$this->getUseGiftCredit() && !$this->getUseGiftVoucher()): ?> <?php endif ?> style="display:none;">
                    <ul>
                        <li>
                            <div class="input-box">
                                 <!--<button type="submit" class="button">-->
                                <button type="button" class="button validation-passed" onclick="check_giftcode()">
                                    <span><span><?php echo $this->__('Apply Gift Card') ?></span></span>
                                </button>
                            </div>
                        </li>
                        <p></p>
                    </ul>
                </dd>
                <dt style="display: none;"></dt>
                <dd id="giftcard_shoppingcart_reloading" style="display:none;">
                    <p style="font-weight: normal; font-style: italic;">
                        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading...') ?>" title="<?php echo $this->__('Refreshing cart, please wait') ?>..." class="v-middle" />
                        <?php echo $this->__('Refreshing cart, please wait') ?>...
                    </p>
                </dd>
            </dl>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var giftcardForm = new VarienForm('discount-giftcard-form');
    var noGiftCardTicked = <?php echo (!$this->getUseGiftCredit() && !$this->getUseGiftVoucher()) ? '1' : '0' ?>;
    if ($('giftvoucher_credit'))
        $('giftvoucher_credit').observe('click', function() {
            if ($('giftvoucher_credit').checked || $('giftvoucher').checked) {
                $('giftcard_shoppingcart_apply').show();
            } else if (noGiftCardTicked) {
                $('giftcard_shoppingcart_apply').hide();
            } else {
                $('giftcard_shoppingcart_apply').hide();
                $('giftcard_shoppingcart_reloading').show();
                giftcardForm.submit();
            }
        });
    $('giftvoucher').observe('click', function() {
        var creditChecked = false;
        if ($('giftvoucher_credit'))
            creditChecked = $('giftvoucher_credit').checked;
        if (creditChecked || $('giftvoucher').checked) {
            $('giftcard_shoppingcart_apply').show();
        } else if (noGiftCardTicked) {
            $('giftcard_shoppingcart_apply').hide();
        } else {
            $('giftcard_shoppingcart_apply').hide();
            $('giftcard_shoppingcart_reloading').show();
            giftcardForm.submit();
        }
    });
    function check_giftcode()
    {
        var giftcredit_checked = false;
        if($('giftvoucher_credit')) giftcredit_checked = $('giftvoucher_credit').checked;
        
        if(giftcredit_checked)
        {
            if($$('dd.giftvoucher_credit')[0].down('.input-text').value==0)
                {
                  if($('giftcredit_notice')) $('giftcredit_notice').style.display="block";
                  if($$('dd.giftvoucher_credit')[0]!=null)$$('dd.giftvoucher_credit')[0].down('.input-text').addClassName('validation-failed');
                } 
            else
            {
                if($('giftcredit_notice')) $('giftcredit_notice').style.display="none";
                if($$('dd.giftvoucher_credit')[0]!=null)$$('dd.giftvoucher_credit')[0].down('.input-text').removeClassName('validation-failed');
                if($('giftcard_notice'))$('giftcard_notice').innerHTML = "";
                giftcardForm.submit();             
            }
        }
        if($('giftvoucher').checked)
        { 
            if($$('.giftvoucher-discount-code')[0]!=null||(giftcredit_checked && $$('dd.giftvoucher_credit')[0]!=null && $$('dd.giftvoucher_credit')[0].down('.input-text').value!=0))
            {
                if($('giftcredit_notice')) $('giftcredit_notice').style.display="none";
                giftcardForm.submit(); 
            }
            else
            {    
                if($('giftvoucher_code')&& $('giftvoucher_code').value=="")
                {
                    if($('giftvoucher_existed_code')==null)
                    {
                        if($('giftvoucher_code'))  $('giftvoucher_code').addClassName("validation-failed");
                        if($('giftcard_notice')) $('giftcard_notice').innerHTML = "<?php echo $this->__('This is a required field.')?>";
                        jQuery('#giftcard_notice').fadeIn('slow');
                    }

                    if($('giftvoucher_existed_code')&& $('giftvoucher_existed_code').value=="")
                    {   
                        if($('giftvoucher_code'))  $('giftvoucher_code').addClassName("validation-failed");
                        if($('giftvoucher_existed_code'))  $('giftvoucher_existed_code').addClassName("validation-failed");
                        if($('giftcard_notice'))$('giftcard_notice').innerHTML = "<?php echo $this->__('Please enter or chose your code')?>";
                        jQuery('#giftcard_notice').fadeIn('slow');
                    }
                    if($('giftvoucher_existed_code')&& $('giftvoucher_existed_code').value!="") 
                    {
                        if($('giftcredit_notice')) $('giftcredit_notice').style.display="none";
                        if($('giftcard_notice'))$('giftcard_notice').innerHTML = "";
                        giftcardForm.submit();
                    }
                }
                else
                {
                    if($('giftcredit_notice')) $('giftcredit_notice').style.display="none";
                    if($('giftcard_notice'))$('giftcard_notice').innerHTML = "";
                    giftcardForm.submit();
                }
            }
        }
    }

    if ( $j('#select_gift_code').length ) {
        $j('#select_gift_code').on("change", function(){
            $j('input[name=giftvoucher_code]').val($j(this).val());
        });
        var code = '<?php echo $code; ?>';

        if(code!='') {
            $j('#select_gift_code').val(code);
        }else {
            $j('#select_gift_code').trigger("change");
        }
    }
    
//]]>
</script>
<?php endif; ?>
<?php endif; ?>
</div>