
<?php if (Mage::getStoreConfig('amrules/general/breakdown')):?>
    <?php if (is_array($this->getTotal()->getFullInfo())) : ?>
    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
    <div class="each-details">
        <tr class="summary-details-amrules summary-details" style="display:none;">
            <td class="a-right" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $info['label']; ?>
                <br />
            </td>
            <td class="a-right" rowspan="1">
                -<?php echo $this->helper('checkout')->formatPrice($info['amount']); ?>
            </td>
        </tr>
    </div>
    <?php endforeach; ?>
        <?php if (Mage::getConfig()->getModuleConfig('Amasty_Rules')->is('active', 'true') && ($pts = Mage::helper('rewardpoints/event')->getCreditPoints($this->getQuote()))):?>
        <div class="each-details">
            <tr class="summary-details-amrules summary-details" style="display:none;">
                <td class="a-right totals-rewards" colspan="<?php echo $this->getColspan(); ?>">
                    <?php echo $this->__('%s points used', $pts);?>
                    <br />
                </td>
                <td class="a-right" rowspan="1">
                    -<?php echo $this->helper('checkout')->formatPrice($this->getQuote()->getStore()->convertPrice(Mage::helper('rewardpoints/data')->convertPointsToMoneyEquivalence($pts))); ?>
                </td>
            </tr>
        </div>
        <?php endif;?>
    <?php endif; ?>
    <div class="each-details">
        <tr class="summary-total" onclick="expandDetails(this, '.summary-details-amrules')" >
            <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
                     <div class="summary-collapse"><?php echo $this->getTotal()->getTitle() ?></div>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
            </td>
            <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
                    <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
            </td>
        </tr>
    </div>
<?php else:?>


    <?php if ($pts = Mage::helper('rewardpoints/event')->getCreditPoints($this->getQuote())):?>
        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="column-01">
                    <p>REBATE:</p>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="column-02">
                    <p class="applied_discount_code minus">-<?php echo $this->helper('checkout')->formatPrice($this->getQuote()->getStore()->convertPrice(Mage::helper('rewardpoints/data')->convertPointsToMoneyEquivalence($pts))); ?></p>
                </div>
            </div>
        </div>       
    <?php endif; ?>
    

    <?php 
        $appliedRuleIds = Mage::getSingleton('checkout/session')->getQuote()->getAppliedRuleIds();
        $appliedRuleIds = explode(',', $appliedRuleIds);

        $all_rules = Mage::getResourceModel('salesrule/rule_collection')->load();
        $rules =  Mage::getModel('salesrule/rule')->getCollection()->addFieldToFilter('rule_id' , array('in' => $appliedRuleIds));

        foreach ($rules as $rule) {
            if ($rule->getIsActive()) {
                if(!empty($current_rule_name))
                    $current_rule_name .= ', ' . $rule->getName();
                else
                    $current_rule_name = $rule->getName();
            }
        }
    ?>
    <?php if(!empty($current_rule_name)): ?>
        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="column-01">
                    <p>DISCOUNT:</p>
                    <span class="discount_desc">(<?php echo $this->getTotal()->getTitle(); ?>)</span>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="column-02">
                    <?php if($pts > 0): ?>
                        <?php $pts = $this->getQuote()->getStore()->convertPrice(Mage::helper('rewardpoints/data')->convertPointsToMoneyEquivalence($pts)) ?>
                        <?php $discount_including_pts = abs($this->getTotal()->getValue()); ?>
                        <p class="applied_discount_code minus">-<?php echo $this->helper('checkout')->formatPrice($discount_including_pts - $pts) ?></p>
                    <?php else: ?>
                        <p class="applied_discount_code minus no-rebate"><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
