<?php if($this->getCurrencyCount()>1): ?>
<a class="desktop-header-current-currency"><?php echo $this->getCurrentCurrencyCode(); ?></a>
<div class="desktop-header-currency-switcher">  
  <div class="desktop-header-currency-form">      
    <select id="desktop-header-currency-select" name="currency" title="<?php echo $this->__('Your Currency') ?>" onchange="setLocation(this.value)">
      <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
        <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
            <?php echo $_code ?>
        </option>
      <?php endforeach; ?>
    </select>
  </div>
  <div class="desktop-header-currency-dropdown-container">
    <ul class="desktop-header-currency-select all-dropdown">
      <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
        <li><a href="#" id="<?php echo $_code ?>"><?php echo $_code ?> - <?php echo Mage::app()->getLocale()->currency($_code)->getSymbol(); ?></a></li>
      <?php endforeach; ?>
    </ul>
  </div>
</div>
<?php endif; ?>