<?php if($this->getCurrencyCount()>1): ?>
<?php echo $this->getCurrentCurrencyCode(); ?>
<select id="desktop-header-currency-select" name="currency" title="<?php echo $this->__('Your Currency') ?>" onchange="setLocation(this.value)">
    <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
    <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
        <?php echo $_code ?>
    </option>
<?php endforeach; ?>
</select>
<?php endif; ?>