      <!-- inside #page-wrapper-content -->


    </div> <!-- #page-wrapper-content -->
  </div> <!-- #page-wrapper -->


  <!--
     _____ ___   ___ _____ _____ ____
    |  ___/ _ \ / _ \_   _| ____|  _ \
    | |_ | | | | | | || | |  _| | |_) |
    |  _|| |_| | |_| || | | |___|  _ <
    |_|   \___/ \___/ |_| |_____|_| \_\

  -->
  
  <footer id="desktop-footer" class="visible-md visible-lg">
    <div class="container-fluid has-breakpoint">
      <div class="row">
        <div class="col-md-6">
          <div id="desktop-footer-copyright">
            <p>Roji by gryphon tea company &copy; 2017</p>
          </div>
        </div>
        <div class="col-md-6">

          <div id="desktop-footer-links">
            <ul>
              <li><a href="javascript:void(0);">Shipping Information</a></li>
              <li><a href="javascript:void(0);">Privacy Policy</a></li>
              <li><a href="javascript:void(0);">Terms of Use</a></li>
            </ul>
          </div> <!-- desktop-footer-links -->

        </div>
      </div>
    </div>
  </footer>

  <footer id="mobile-footer" class="visible-sm visible-xs">
  </footer>


  <!--
     __  __    _    ___ _     ___ _   _  ____   _     ___ ____ _____
    |  \/  |  / \  |_ _| |   |_ _| \ | |/ ___| | |   |_ _/ ___|_   _|
    | |\/| | / _ \  | || |    | ||  \| | |  _  | |    | |\___ \ | |
    | |  | |/ ___ \ | || |___ | || |\  | |_| | | |___ | | ___) || |
    |_|  |_/_/   \_\___|_____|___|_| \_|\____| |_____|___|____/ |_|

  -->

  <div id="mailing-list-popup-container">

    <div class="black-bg"></div>

    <div id="mailing-list-popup">

      <div class="row">
        <div class="col-xs-6">

          <div class="column-01">
            <div id="mailing-list-image">
              <div class="manic-image-container">
                <img src="" data-image-desktop="images_cms/others/mailing-list.jpg">
              </div>
            </div> <!-- mailing-list-image -->
          </div> <!-- column-01 -->


        </div>
        <div class="col-xs-6">

          <div class="column-02">

            <div id="mailing-list-title">
              Join Our Mailing List
            </div>

            <div id="mailing-list-copy">
              <div class="default-copy">
                <small>Sign up for our mailing list be the first to hear about new arrivals, special promotions and exclusive offers.</small>
              </div>
            </div> <!-- mailing-list-copy -->

            <div id="mailing-list-form">

              <form class="mailing-form">
                <input type="email" name="" id="" placeholder="Enter your email address">
                <input type="submit" value=""> <!-- fa-paper-plane-o -->
              </form>

            </div> <!-- mailing-list-form -->
            
          </div> <!-- column-02 -->


        </div>
      </div>

      <div id="mailing-list-close-btn"></div>

    </div> <!-- mailing-list-popup -->
  </div> <!-- mailing-list-popup-container -->