      <!-- inside #page-wrapper-content -->


    </div> <!-- #page-wrapper-content -->
  </div> <!-- #page-wrapper -->


  <!--
     _____ ___   ___ _____ _____ ____
    |  ___/ _ \ / _ \_   _| ____|  _ \
    | |_ | | | | | | || | |  _| | |_) |
    |  _|| |_| | |_| || | | |___|  _ <
    |_|   \___/ \___/ |_| |_____|_| \_\

  -->
  
  <footer id="desktop-footer" class="visible-md visible-lg">
    <div class="container-fluid has-breakpoint">
      <div class="row">
        <div class="col-md-5">
          <div id="desktop-footer-copyright">
            <p><?php $storeCopyright = Mage::getStoreConfig('design/footer/copyright'); echo $storeCopyright; ?></p>
          </div>
        </div>
        <div class="col-md-7">

          <div id="desktop-footer-links">
            <ul>
              <li><a href="<?php echo $this->getUrl('faq'); ?>">FAQ</a></li>
              <li><a href="<?php echo $this->getUrl('shipping-info'); ?>">Shipping Information</a></li>
              <li><a href="<?php echo $this->getUrl('privacy-policy'); ?>">Privacy Policy</a></li>
              <li><a href="<?php echo $this->getUrl('terms-of-use'); ?>">Terms of Use</a></li>
            </ul>
          </div> <!-- desktop-footer-links -->

        </div>
      </div>
    </div>
  </footer>

  <footer id="mobile-footer" class="visible-sm visible-xs">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <div id="mobile-footer-copyright">
            <p><?php $storeCopyright = Mage::getStoreConfig('design/footer/copyright'); echo $storeCopyright; ?></p>
          </div>
        </div>
      </div>
    </div>
  </footer>


  <!--
     __  __    _    ___ _     ___ _   _  ____   _     ___ ____ _____
    |  \/  |  / \  |_ _| |   |_ _| \ | |/ ___| | |   |_ _/ ___|_   _|
    | |\/| | / _ \  | || |    | ||  \| | |  _  | |    | |\___ \ | |
    | |  | |/ ___ \ | || |___ | || |\  | |_| | | |___ | | ___) || |
    |_|  |_/_/   \_\___|_____|___|_| \_|\____| |_____|___|____/ |_|

  -->

  <div id="mailing-list-popup-container">

    <div class="black-bg"></div>

    <div id="mailing-list-popup">

      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">

          <div class="column-01">
            <div id="mailing-list-image">
              <div class="manic-image-container">
                <img src="" data-image-desktop="<?php echo $this->getSkinUrl('images_cms/others/mailing-list.jpg'); ?>">
              </div>
            </div> <!-- mailing-list-image -->
          </div> <!-- column-01 -->


        </div>
        <div class="col-md-6 col-xs-12">

          <div class="column-02">

            <div id="mailing-list-title">
              Join Our Mailing List
            </div>

            <div id="mailing-list-copy">
              <div class="default-copy">
                <small>Receive SGD5 Rebate Dollars when you sign up for our mailing list.</small>
              </div>
            </div> <!-- mailing-list-copy -->

            <div id="mailing-list-form">

              <form class="mailing-form">
                <input type="email" name="mailing-list-popup-email-input" id="mailing-list-popup-email-input" placeholder="Enter your email address">
                <input type="submit" id="mailing-list-popup-send-btn" value=""> <!-- fa-paper-plane-o -->
                <!-- <span class='newsletter_ajax_loader' style='display:none'><img src='<?php echo $this->getSkinUrl('images/icons/spin.svg')?>'/></span>                    -->
                <span class="ajax_msg italic"></span>
              </form>

            </div> <!-- mailing-list-form -->
            
          </div> <!-- column-02 -->


        </div>
      </div>

      <div id="mailing-list-close-btn" class="close-btn"></div>

    </div> <!-- mailing-list-popup -->
  </div> <!-- mailing-list-popup-container -->