<?php
$count = $this->helper('checkout/cart')->getSummaryCount();
$quote = Mage::getModel('checkout/session')->getQuote();
$quoteData= $quote->getData();
?>
<div id="page-preloader">
  <div id="page-preloader-bg"></div>
  <div id="page-preloader-center">
    <?php //require_once($this->getSkinUrl('images/preloader.svg')); ?>
  </div>
</div>

<header id="desktop-header" class="visible-md visible-lg">
  <div class="container-fluid has-breakpoint">
    <div class="row">
      <div class="col-md-2">

        <div id="desktop-header-logo-container">
          <a href="<?php echo $this->getUrl('') ?>" id="desktop-header-logo"></a>
        </div> <!-- desktop-header-logo-container -->

      </div>
      <div class="col-md-10">

        <div id="desktop-header-menu-container">
          <div id="desktop-header-menu">
            <?php echo $this->getChildHtml('topMenu'); ?>            
          </div> <!-- desktop-header-menu -->

          <div id="desktop-header-login-menu">
            <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>">Join/log in</a>
          </div> <!-- desktop-header-login-menu -->
          
          <div id="desktop-header-currency-menu">
            <!-- <div class="manic-dropdown"> -->
              <?php echo $this->getChildHtml('currency_top') ?>              
            <!-- </div> -->
          </div> <!-- desktop-header-currency-menu -->

          <div id="desktop-header-cart-menu">
            
            <a href="<?php echo $this->getUrl('checkout/cart'); ?>">
              <div id="desktop-header-cart-btn">
                <span class="cart-btn-value"><?php echo (!empty($count)) ? $count : 0; ?></span>
              </div>
            </a>

            <div id="desktop-header-cart-expand-container">

            </div>
          </div> <!-- desktop-header-cart-menu -->

        </div> <!-- desktop-header-menu-container -->
        

      </div>
    </div>
  </div>
</header>

<header id="mobile-header" class="visible-sm visible-xs">
</header>

<div id="page-wrapper">
  <div id="page-wrapper-content">

    <div id="desktop-header-spacer"></div>
    <div id="mobile-header-spacer"></div>

    <!-- inside #page-wrapper-content -->