<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '181822275684181',
      xfbml      : true,
      version    : 'v2.9'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<?php
$count = $this->helper('checkout/cart')->getSummaryCount();
$quote = Mage::getModel('checkout/session')->getQuote();
$quoteData= $quote->getData();
?>
<div id="page-preloader">
  <div id="page-preloader-bg"></div>
  <div id="page-preloader-center">
    <img src="<?php echo $this->getSkinUrl('images/preloader.svg'); ?>" alt="">    
  </div>
</div>

<header id="desktop-header" class="visible-md visible-lg">
  <div class="container-fluid has-breakpoint">
    <div class="row">
      <div class="col-md-2">

        <div id="desktop-header-logo-container">
          <a href="<?php echo $this->getUrl('') ?>" id="desktop-header-logo"></a>
        </div> <!-- desktop-header-logo-container -->

      </div>
      <div class="col-md-10">

        <div id="desktop-header-menu-container">
          <div id="desktop-header-menu">
            <?php echo $this->getChildHtml('topMenu'); ?>            
          </div> <!-- desktop-header-menu -->

          <div id="desktop-header-login-menu">
            <?php $session = Mage::getSingleton('customer/session'); ?>
            <?php if($session->isLoggedIn()): ?>
              <a href="<?php echo Mage::getUrl('customer/account'); ?>">My Account</a>
              <!-- <a href="javascript:void(0);">My Account</a> -->
            <?php else: ?>
              <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo $this->__('Join/log in') ?></a>
              <!-- <a href="javascript:void(0);">Join/log in</a> -->
            <?php endif; ?>
          </div> <!-- desktop-header-login-menu -->
          
          <div id="desktop-header-currency-menu">
            <!-- <div class="manic-dropdown"> -->
              <?php echo $this->getChildHtml('currency_top') ?>              
            <!-- </div> -->
          </div> <!-- desktop-header-currency-menu -->
          
          <div id="desktop-header-language-menu">
              <?php echo $this->getChildHtml('store_language') ?>
          </div> <!-- desktop-header-currency-menu -->

          <div id="desktop-header-cart-menu">
          
            <div id="desktop-header-cart-btn">
              <span class="cart-btn-value"><?php echo (!empty($count)) ? $count : 0; ?></span>
            </div>            

            <div id="desktop-header-cart-expand-container">              
                <h4 class="desktop-header-cart-expand-title">YOUR CART</h4>

                <?php 
                  $cart = Mage::getModel('checkout/cart')->getQuote();
                  $cartQty = $this->helper('checkout/cart')->getSummaryCount();
                  $cartTotal = Mage::getSingleton('checkout/cart')->getQuote()->getSubtotal();
                ?>

                <div class="desktop-header-cart-expand">
                  <?php if ($cartQty>0): ?>                                         
                      <?php               
                      foreach ($cart->getAllItems() as $item) {
                          $storeId = Mage::app()->getStore()->getStoreId();
                          $productId = $item->getProduct()->getId();
                          $productName = $item->getProduct()->getName();
                          $productNameInColor = Mage::getResourceModel('catalog/product')->getAttributeRawValue($productId, 'product_name_in_color', $storeId);
                          $productPrice = $item->getProduct()->getPrice();
                          $productQty = $item->getQty();
                          $price = $item->getRowTotal();
                          $productImage = Mage::helper('catalog/image')->init($item->getProduct(), 'thumbnail');
                          
                      ?>
                      <ul class="desktop-header-cart-expand-content">             
                        <li>
                          <div class="manic-image-container">
                            <img src="<?php echo $productImage; ?>" alt="">
                          </div>
                        </li>
                        <li>
                          <p><?php echo ($productQty) ? $productQty : ""; ?> x</p>
                          <p><?php echo ($productName) ? $productName : ""; ?></p>
                          <p><?php echo (!empty($productNameInColor)) ? $productNameInColor : ""; ?></p>
                          <p><?php echo Mage::helper('core')->currency($productPrice, true, false); ?></p>
                        </li>
                        <li>                        
                          <a href="javascript:void(0);" data-item-id="<?php echo $item->getProduct()->getId(); ?>" title="<?php echo $this->__('Remove item')?>" class="close-btn remove-item"></a>
                        </li>
                      </ul>
                      <?php
                      }
                      ?>                  
                  <?php else: ?>                
                    
                    <ul class="desktop-header-cart-expand-content">
                      <li class="empty-cart"><p>Your cart is empty.</p></li>
                    </ul>
                    
                  <?php endif; ?>

                </div>

                <ul class="desktop-header-cart-expand-summary">                                       
                    <li><h4 class="sub-total">SUB TOTAL:</h4></li>                 
                    <li><h4 class="sub-total-amount"><?php echo Mage::helper('core')->formatPrice($cartTotal, true); ?></h4></li>             
                </ul>             

                <div class="desktop-header-cart-expand-cta-btn">                    
                    <a href="<?php echo $this->getUrl('checkout/cart'); ?>" class="shopping-cart"><button type="button" class="square-cta"><span><span>Go to Cart</span></span></button></a>
                </div>
                
              
            </div>
          </div> <!-- desktop-header-cart-menu -->

        </div> <!-- desktop-header-menu-container -->
        

      </div>
    </div>
  </div>
</header>

<!--
     __  __  ___  ____ ___ _     _____   _   _ _____    _    ____  _____ ____
    |  \/  |/ _ \| __ )_ _| |   | ____| | | | | ____|  / \  |  _ \| ____|  _ \
    | |\/| | | | |  _ \| || |   |  _|   | |_| |  _|   / _ \ | | | |  _| | |_) |
    | |  | | |_| | |_) | || |___| |___  |  _  | |___ / ___ \| |_| | |___|  _ <
    |_|  |_|\___/|____/___|_____|_____| |_| |_|_____/_/   \_\____/|_____|_| \_\

  -->


  <header id="mobile-header" class="visible-sm visible-xs">

    <div class="mobile-header-bg"></div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-3">

          <div id="mobile-menu-btn-container">
            <div id="mobile-menu-btn">
              <span class="line-01"></span>
              <span class="line-02"></span>
              <span class="line-03"></span>
            </div>
          </div>
          
        </div>
        <div class="col-xs-6">

          <div id="mobile-header-logo-container">
            <a href="<?php echo $this->getUrl('') ?>" id="mobile-header-logo"></a>
          </div>

        </div>
        <div class="col-xs-3">

          <div id="mobile-header-cart-container">
            <a href="<?php echo $this->getUrl('checkout/cart'); ?>" id="mobile-header-cart-btn">
              <span class="cart-btn-value"><?php echo (!empty($count)) ? $count : 0; ?></span>
            </a>
          </div>

        </div>

      </div> <!-- row -->
    </div> <!-- container-fluid -->
  </header> <!-- mobile-header -->

  <!--
     __  __  ___  ____ ___ _     _____   _   _ _____    _    ____  _____ ____    _______  ______   _    _   _ ____
    |  \/  |/ _ \| __ )_ _| |   | ____| | | | | ____|  / \  |  _ \| ____|  _ \  | ____\ \/ /  _ \ / \  | \ | |  _ \
    | |\/| | | | |  _ \| || |   |  _|   | |_| |  _|   / _ \ | | | |  _| | |_) | |  _|  \  /| |_) / _ \ |  \| | | | |
    | |  | | |_| | |_) | || |___| |___  |  _  | |___ / ___ \| |_| | |___|  _ <  | |___ /  \|  __/ ___ \| |\  | |_| |
    |_|  |_|\___/|____/___|_____|_____| |_| |_|_____/_/   \_\____/|_____|_| \_\ |_____/_/\_\_| /_/   \_\_| \_|____/

  -->

  <header id="mobile-header-expanded">
    <div class="mobile-header-spacer"></div>
    <div id="mobile-header-account-container">

      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12">
            <?php $session = Mage::getSingleton('customer/session'); $customer = $session->getCustomer(); ?>
            <div id="mobile-header-account-single-link" class="<?php if($session->isLoggedIn()): ?>logged-in<?php endif; ?>">              
              <?php if($session->isLoggedIn()): ?>
                <a href="javascript:void(0);">Welcome, <?php echo $customer->getFirstname(); ?></a>
              <?php else: ?>
                
                <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>">Join / log in</a>
              <?php endif; ?>
            </div> <!-- mobile-header-account-single-link -->


            <div id="mobile-header-account-menu" style="display: none;">
              <?php
              $store_id = Mage::app()->getStore()->getId();
              $customerId = Mage::getModel('customer/session')->getCustomerId();
              if (Mage::getStoreConfig('rewardpoints/default/flatstats', $store_id)){
                  $reward_flat_model = Mage::getModel('rewardpoints/flatstats');
                  return $reward_flat_model->collectPointsCurrent($customerId, $store_id)+0;
              }        

              $reward_model = Mage::getModel('rewardpoints/stats');
              $current_point = $reward_model->getPointsCurrent($customerId, $store_id)+0; 

              $store = Mage::app()->getStore();  
              $currency = Mage::app()->getStore()->getCurrentCurrency();      
              ?>            
              <nav>
                <ul>
                  <li><a href="<?php echo $this->getUrl('customer/account'); ?>">My Account</a></li>
                  <li><a href="<?php echo Mage::getUrl('customer/address/'); ?>">Address Book</a></li>
                  <li><a href="<?php echo Mage::getUrl('sales/order/history/'); ?>">Order History</a></li>
                  <li><a href="<?php echo Mage::getUrl('giftvoucher/index/index'); ?>">Gift Card</a><!-- <span class="account-menu-value">$10.00</span> --></li>
                  <li><a href="<?php echo Mage::getUrl('rewardpoints/index/points/'); ?>">Rebate History</a><span class="account-menu-value"><?php echo $currency->format($store->convertPrice($current_point)); ?></span></li>
                  <li><a href="<?php echo Mage::getUrl('rewardpoints/index/referral/'); ?>">Friend Referral</a></li>
                  <li><a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>">Log out</a></li>
                </ul>
              </nav>
            </div> <!-- mobile-header-account-menu -->


          </div>
        </div>
      </div>
      
    </div> <!-- mobile-header-account-container -->

    <div id="mobile-header-menu-container">
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12">

            <div id="mobile-header-menu">
              <nav>
                <ul>

                  <li><a href="<?php echo $this->getUrl('about'); ?>">About</a></li>

                  <!-- currency converter functionality pending -->
                  <li class="currency-version">
                    <?php 
                    // TEA
                    $store_category = Mage::getModel('catalog/category')->loadByAttribute('name', 'Shop');
                    ?>
                    <a href="<?php echo $store_category->getUrl(); ?>">Shop</a>

                    <?php echo $this->getChildHtml('currency_top') ?>              

                  </li>

                  <li><a href="<?php echo $this->getUrl('our-teas'); ?>">Our Teas</a></li>

                  <!-- CLASS HAS TO BE ADDED BY THE JAVASCRIPT -->
                  <li class="submenu-version">
                    <?php 
                    // TEA
                    $gift_category = Mage::getModel('catalog/category')->loadByAttribute('name', 'Gifts');
                    ?>
                    <a href="<?php echo $gift_category->getUrl(); ?>">Gifts</a>
                    <ul>
                      <li><a href="<?php echo $gift_category->getUrl(); ?>">Tin</a></li>
                    </ul>
                  </li>

                  <li><a href="<?php echo $this->getUrl('blog'); ?>">Blog</a></li>
                  <li><a href="<?php echo $this->getUrl('chaseki-members-program'); ?>">Chaseki Members</a></li>
                  <li><a href="<?php echo $this->getUrl('contact'); ?>">Contact</a></li>
                  <li><a href="<?php echo $this->getUrl('faq'); ?>">FAQ</a></li>
                  <li><a href="<?php echo $this->getUrl('shipping-info'); ?>">Shipping Information</a></li>
                  <li><a href="<?php echo $this->getUrl('privacy-policy'); ?>">Privacy Policy</a></li>
                  <li><a href="<?php echo $this->getUrl('terms-of-use'); ?>">Terms of Use</a></li>
                  
                  

                </ul>
              </nav>
            </div>


          </div>
        </div>
      </div>


    </div> <!-- mobile-header-menu-container -->
        


  </header> <!-- mobile-header-expanded -->


  <div id="mobile-header-push-noti">
    <div id="mobile-header-push-noti-image-container" class="manic-image-container">
      <img src="" data-image-tablet="<?php echo $this->getSkinUrl('images/logo/logo-desktop-header.svg'); ?>" data-image-mobile="<?php echo $this->getSkinUrl('images/logo/logo-desktop-header.svg'); ?>" alt="">
    </div>    
  
    <div id="mobile-header-push-noti-text-container">
      <h4 class="title">Success</h4>
      <p>This item is added to cart.</p>
    </div>
    
    <a href="#" id="mobile-header-push-noti-close-btn" class="close-btn"></a>
  </div>

<div id="page-wrapper">
  <div id="page-wrapper-content">

    <div class="desktop-header-spacer visible-md visible-lg"></div>
    <div class="mobile-header-spacer visible-sm visible-xs"></div>

    <!-- inside #page-wrapper-content -->