<?php
//field expire date
$timeLife = Mage::getStoreConfig('giftvoucher/general/expire');
$timeSite = date("m/d/Y", Mage::getModel('core/date')->timestamp(time()));
$expire_day = date('m/d/Y', strtotime($timeSite . '+' . $timeLife . ' days'));
//end
$barcode = Mage::helper('giftvoucher')->getGeneralConfig('barcode_enable');
$barcode_type = Mage::helper('giftvoucher')->getGeneralConfig('barcode_type');
$url_barcode = '';
if ($barcode) {
    if ($barcode_type == 'code128')
        $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/default.png';
    else
        $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/qr.png';
}
if (Mage::getStoreConfig('giftvoucher/print_voucher/logo'))
    $logo = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/pdf/logo/' . Mage::getStoreConfig('giftvoucher/print_voucher/logo');
else
    $logo = $this->getSkinUrl('images/logo_print.gif');
?>
<div id="giftcard-template-back" class="vcenter" style="/*display:none*/">
    <div class="giftcard-template-content" style= "display:none"></div>
    <div class="giftcard-change-image-background-popup giftcard-change-image vcenter2" style="background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/default.png' ?>);">   

        <div id="gift-design-01">
            <div id="gifttext" class="gifttext giftcard-style-color">
                <div class="gifttext-intro">Dear <span class="giftcard-send-to" id='giftcard-to'></span>, a special gift for you <br>from <span class="giftcard-send-from" id='giftcard-from' >&nbsp;<?php echo Mage::helper('customer')->isLoggedIn() ? Mage::helper('customer')->getCustomerName() : ''; ?></span></div>
                <div class="gifttext-copy giftcard-custom-message"></div>
                <div class="gifttext-code-title"><span>gift card code:</span> <br>
                    <?php if ($url_barcode != ''): ?>
                    <!-- <div class="gifttext-code"><span class = "barcode"><img src="<?php echo $url_barcode ?>" /></span></div> -->
                    <div class="gifttext-code"><span class = "barcode">GIFT-XXXX-XXXX</span></div>
                    <?php else: ?>
                    <div class="gifttext-code"><span class = "barcode">GIFT-XXXX-XXXX</span></div>
                    <?php endif; ?>
                </div>                
                <div class="gifttext-amount"><span class="gifttext-amount-number giftcard-price-change">$100</span></div>
                <div class="gifttext-disclaimer">Converting the e-gift card to cash is not allowed.<br class="hidden-xs">Please redeem your gift card at www.monogramtea.com.</div>
            </div>            
        </div> 

        <div class = "giftcard-logo" style="display:none;"><img src = "<?php echo $logo ?>"/></div>            
        <div class="expire-day expire-day-top" id = "expire-day-background" style="display:none; font-size: 10px; float: right; margin-top: 5px;margin-right: 5px; color: white; font-weight: bold; "></div> 
        <div class = "title-value giftcard-logo-background" style="display:none;">
            <div class="giftcard-style-color giftcard-title"><?php echo $this->__('Giftcard Title') ?></div>
            <div class="giftcard-value-color">
                <span class="giftcard-style-color"><?php echo $this->__('Value') ?></span>
                <span class="giftcard-style-color giftcard-price-change">$100.00</span>
            </div>
        </div>
        <div class= "from-to-barcode-background" style="display:none;">
            <div class = "from-to">
                <div class = "giftcard-form">
                    <label class="giftcard-text-color" for="giftcard-from"><?php echo $this->__('From') ?>:</label>
                    <span class="giftcard-style-color giftcard-send-from" id='giftcard-from' >&nbsp;<?php echo Mage::helper('customer')->isLoggedIn() ? Mage::helper('customer')->getCustomerName() : ''; ?></span>
                </div>
                <div class = "giftcard-to" style="">
                    <label class="giftcard-text-color" for="giftcard-to"><?php echo $this->__('To') ?>: </label>
                    <span class="giftcard-style-color giftcard-send-to" id='giftcard-to'>&nbsp;</span>
                </div>
            </div>
            <div class ="giftcard-barcode">                
                <?php if ($url_barcode != ''): ?>
                    <div class="giftcard-number">                
                        <span class="giftcard-style-color" style="">GIFT-XXXX-XXXX</span>
                    </div>
                    <span class = "barcode"><img src="<?php echo $url_barcode ?>" /></span>
                <?php else: ?>
                    <div class="giftcard-number">                
                        <span class="giftcard-style-color" style="">GIFT-XXXX-XXXX</span>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <div class = "giftcard-box-background" style="display:none;">
            <div class = "giftcard-text-box"><pre class="giftcard-text-color giftcard-custom-message"></pre></div>
        </div>
        <div class = "giftcard-note-background" style="display:none;">
            <div class = "form-note">
                <p class="giftcard-text-color"><?php echo Mage::getSingleton('giftvoucher/giftvoucher')->getPrintNotes(); ?></p>
            </div>
        </div>

    </div>
</div>
<script>
    var d = new Date();
    var check = <?php echo (Mage::helper('giftvoucher')->getGeneralConfig('show_expiry_date') && $timeLife) ? $timeLife : 0 ?>;
    if (check != 0)
    {
        d.setDate(d.getDate() + check);
        var month = d.getMonth() + 1;
        var day = d.getDate();
        var year = d.getFullYear();
        document.getElementById("expire-day-background").innerHTML = "Expired: " + month + "/" + day + "/" + year;
    }
</script>