<?php
/**
 * Gift Voucher product media template
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$templates = Mage::getBlockSingleton('giftvoucher/product_view')->getAvailableTemplate();
if (count($templates)):
    ?>
    <div class="giftcard-product-media" id="giftcard-product-media">
        <div class = "background-popup" style="cursor: pointer; -moz-transform-origin: left top;" onclick="getPreview()">
            <?php include 'template/background.phtml'; ?>
        </div>
        <div class = "top-popup" style="cursor: pointer;-moz-transform-origin: left top;" onclick="getPreview()">
            <?php include 'template/top.phtml'; ?>
        </div>
        <div class = "left-popup" style="cursor: pointer; -moz-transform-origin: left top;" onclick="getPreview()">
            <?php
            include 'template/left.phtml';
            ?>
        </div>
    </div>
    <!--    Popup   -->
    <div id="giftcard-preview-template" style="display: none; width: 100%; ">        
        <div id="giftcard-preview-template-content"></div>
    </div>
    <script type="text/javascript">
        $('giftcard-template-back').hide();
        $('giftcard-template-top').hide();
        $('giftcard-template-left').hide();
        var body = $$('body.catalog-product-view')[0];
        if (body)
            body.insert('<div id="popup-giftcard"style="display:none;"><a href="javascript:void(0);" id="close-popup-giftcard" onclick="closePopupGift()">&nbsp;</a></div><div id="bg-fade" style="display:none;"></div>');
        function getPreview() {
            var isMobile = navigator.userAgent.match(/iPhone|iPod/i) || navigator.userAgent.match(/Android/i) || navigator.userAgent.match(/BlackBerry/i) || navigator.userAgent.match(/Opera Mini/i) || navigator.userAgent.match(/IEMobile/i);
            var windownWidth = window.innerWidth;
            if (windownWidth > 600) {
                var wrapper = $$('.wrapper')[0];
                var popup_height = wrapper.getHeight();
                $('bg-fade').setStyle({
                    height: popup_height + 'px'
                });
                var giftcard = $('giftcard-product-media');
                var html = giftcard.innerHTML;
                $('popup-giftcard').innerHTML = '<a href="javascript:void(0);" id="close-popup-giftcard" onclick="closePopupGift()">&nbsp;</a>' + html;
                $('popup-giftcard').show();
                $('bg-fade').show();
            }
        }
        $('bg-fade').observe('click', function() {
            this.hide();
            $('popup-giftcard').hide();
            $('popup-giftcard').innerHTML = '<a href="javascript:void(0);" id="close-popup-giftcard" onclick="closePopupGift()">&nbsp;</a>';
        });
        function closePopupGift() {
            $('popup-giftcard').hide();
            $('bg-fade').hide();
            // $('popup-giftcard').innerHTML = '<a href="javascript:void(0);" id="close-popup-giftcard">&nbsp;</a>';
        }
    </script>
    <?php
else:
    ?>
    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <p class="product-image product-image-zoom">
            <?php
            $_img = '<img id="image" src="' . $this->helper('catalog/image')->init($_product, 'image') . '" alt="' . $this->escapeHtml($this->getImageLabel()) . '" title="' . $this->escapeHtml($this->getImageLabel()) . '" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
        <p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
        <div class="zoom">
            <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
            <div id="track">
                <div id="handle"></div>
            </div>
            <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
        </div>
        <script type="text/javascript">
        //<![CDATA[
            Event.observe(window, 'load', function() {
                product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
            });
        //]]>
        </script>
    <?php else: ?>
        <p class="product-image">
            <?php
            $_img = '<img src="' . $this->helper('catalog/image')->init($_product, 'image')->resize(265) . '" alt="' . $this->escapeHtml($this->getImageLabel()) . '" title="' . $this->escapeHtml($this->getImageLabel()) . '" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
    <?php endif; ?>
    <?php if (count($this->getGalleryImages()) > 0): ?>
        <div class="more-views">
            <h2><?php echo $this->__('More Views') ?></h2>
            <ul>
                <?php foreach ($this->getGalleryImages() as $_image): ?>
                    <li>
                        <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');
                                return false;" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" /></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
<?php
endif;
?>
<script type="text/javascript">

    var widthImageMedia = $$('.product-img-box')[0].getWidth();
    var widthImageGC = 600;
    var heightImageGC = $$('.giftcard-product-media')[0].getHeight();

    $$('.product-img-box')[0].setStyle({'height': 'auto'});
    zoomStyle(widthImageMedia, widthImageGC);

    function zoomStyle(productImgBox_Width, widthImageGC) {
        var ratio = productImgBox_Width / widthImageGC;
        var newHeight = heightImageGC * ratio;
        if (navigator.userAgent.indexOf("Firefox") > 0)
            $$('.giftcard-product-media')[0].setStyle({'transform': 'scale(' + ratio + ')', });
        else if (navigator.userAgent.indexOf("Safari") > 0)
            $$('.giftcard-product-media')[0].setStyle({'-webkit-transform': 'scale(' + ratio + ')'});
        else
            $$('.giftcard-product-media')[0].setStyle({'zoom': ratio});

        $$('.giftcard-product-media')[0].setStyle({'height': newHeight + 'px'});

        if (window.innerWidth <= 600) {
            if ($('giftcard-preview-button-add'))
                $('giftcard-preview-button-add').hide();
        } else {
            if ($('giftcard-preview-button-add'))
                $('giftcard-preview-button-add').show();
        }
    }

    window.onresize = resize;
    function resize() {
        productImgBox_Width = $$('.product-img-box')[0].getWidth();
        zoomStyle(productImgBox_Width, widthImageGC);
    }
</script>

