
<!--
<div id="under-construction-disclaimer">
  <p>Home page is under-construction</p>
</div>
-->








<!--
   __  __  ___  ____ ___ _     _____
  |  \/  |/ _ \| __ )_ _| |   | ____|
  | |\/| | | | |  _ \| || |   |  _|
  | |  | | |_| | |_) | || |___| |___
  |_|  |_|\___/|____/___|_____|_____|

-->






<article id="home-mobile-landing-section">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div id="home-mobile-landing-copy">
          <div class="default-copy white-version">

            <a href="javascript:void(0);"  id="home-mobile-intro-logo">
              <div class="home-intro-logo-logo-mobile"></div>
              <div class="home-intro-logo-name-mobile"></div>
            </a>

            <h1>The art of <br>tea layering</h1>
            <p>Excite the palate and discover a world of simplexity tea flavours with Monogram. Exuding class and sophistication, playful and dynamic, explore the art of tea layering with every cup. With no two brews tasting the same, curate a personal identity with the world’s finest handpicked tea leaves and herbs.</p>
            <!-- <p>Get hands on and experimental with Monogram, layering the silken sachets to harmonious perfection. With each sachet carefully selected to complement each other, half the fun is to discover your very own brew. More importantly, the special bond that comes with each tea layering experience.</p> -->

          </div> <!-- default-copy -->
        </div> <!-- #home-mobile-landing-copy -->

        <div id="home-mobile-landing-graph-subsection">
          <div id="home-mobile-landing-graph-title">
            <h4>tea layering suggestions</h4>
          </div>
          <!-- insert graph here -->



          <!--
             __  __  ___  ____ ___ _     _____   _        _    _   _ ____ ___ _   _  ____    ____ ____      _    ____  _   _
            |  \/  |/ _ \| __ )_ _| |   | ____| | |      / \  | \ | |  _ \_ _| \ | |/ ___|  / ___|  _ \    / \  |  _ \| | | |
            | |\/| | | | |  _ \| || |   |  _|   | |     / _ \ |  \| | | | | ||  \| | |  _  | |  _| |_) |  / _ \ | |_) | |_| |
            | |  | | |_| | |_) | || |___| |___  | |___ / ___ \| |\  | |_| | || |\  | |_| | | |_| |  _ <  / ___ \|  __/|  _  |
            |_|  |_|\___/|____/___|_____|_____| |_____/_/   \_\_| \_|____/___|_| \_|\____|  \____|_| \_\/_/   \_\_|   |_| |_|

          -->

          <div id="home-mobile-landing-graph-container">

            <div id="home-mobile-landing-combination-graph" class="monogram-combination-graph">
              <div class="graph-svg"></div>                
              <div class="graph-name-overlay">
                <div class="graph-name-item floral-version"></div>
                <div class="graph-name-item creamy-version"></div>
                <div class="graph-name-item marine-version"></div>
                <div class="graph-name-item mineral-version"></div>
                <div class="graph-name-item citrus-version"></div>
                <div class="graph-name-item fruity-version"></div>
                <div class="graph-name-item sweet-version"></div>
                <div class="graph-name-item wood-version"></div>
                <div class="graph-name-item herbaceous-version"></div>
              </div>
              <div class="graph-overlay"></div>
            </div>

          </div> <!-- #home-mobile-landing-graph-container -->




          <div id="home-mobile-landing-graph-bottom">
            <div class="default-copy">

              
              <div class="graph-selection-name">
                <div id="graph-selection-name-01">
                  <h2><span style="color:#c0cdd5">Earl Grey</span> <span style="color:#d8d1ca">Neroli</span></h2>
                </div>
                <div id="graph-selection-name-02">
                  <div class="plus-sign">+</div>
                  <h2><span style="color:#c7c89b">Shiso</span> <span style="color:#bcc4b9">Mint</span></h2>
                </div>
              </div>

              <p>Fresh approach to a unique blend of mint and bergamot. An alluring experience that promises more adventure to come.</p>

              <div class="cta-container">
                <?php 
                $groupname = '';
                if(Mage::getSingleton('customer/session')->isLoggedIn()) {
                    $customerData = Mage::getSingleton('customer/session')->getCustomer();
                    $customerGroupId = $customerData->getGroupId();
                    $groupname = Mage::getModel('customer/group')->load($customerGroupId)->getCustomerGroupCode();  
                }
                if($groupname=='Trader-Temp' || $groupname=='Trader-Regular' || $groupname=='Trader-Priority' || $groupname=='Trader-Premium') $trade = true;        
                else $trade = false; ?>
                <?php if(!$trade): ?>
                  <a href="javascript:void(0);" id="home-mobile-buy-both-teas-cta" class="home-mobile-buy-both-teas-cta square-cta">add both to cart</a>
                <?php endif; ?>
                <a href="#selection" class="square-cta">see more layering suggestions</a>
              </div>
            </div>
          </div>
        </div> <!-- #home-mobile-landing-graph-subsection -->


        
        <div id="home-mobile-landing-popular-subsection">
          <div id="home-mobile-landing-popular-title">
            <h4>Featured Teas</h4>
          </div>

          <div id="home-mobile-landing-popular-item-container" class="row">
          <?php 
          $_productCollection = Mage::getModel('catalog/category')->load(8)
                       ->getProductCollection()
                       ->addAttributeToSelect('*')
                       ->addAttributeToFilter('status', 1) // enabled
                       ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
                       ->addAttributeToSort('position', Varien_Data_Collection::SORT_ORDER_ASC);
          ?>
          <?php foreach ($_productCollection as $key => $_product):    
              $_imgSize = 160;
              $_imgSize2x = 320;
              $categoryIds = $_product->getCategoryIds();               
          ?>          

            
            <div class="col-xs-6">

              <a href="<?php echo $_product->getProductUrl() ?>" class="home-mobile-landing-popular-item">
                <div class="home-mobile-landing-popular-item-image">
                  <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize2x, 400); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img"/>                  
                </div>
                <div class="home-mobile-landing-popular-item-copy">

                  <div class="home-mobile-landing-popular-item-title">
                    <?php if(!empty($_product->getData('product_name_in_color'))): ?>
                    <h2><?php echo $_product->getData('product_name_in_color') ?></h2>
                    <?php else: ?>
                    <h2><?php echo $_product->getName(); ?></h2>
                    <?php endif; ?>                    
                  </div>
                  <p><?php echo $_product->getShortDescription(); ?></p>
                </div>
              </a>
              
            </div>

            <?php $count++; ?>
          <?php endforeach; ?>        


            <!-- <div class="col-xs-6">

              <a href="javascript:void(0);" class="home-mobile-landing-popular-item">
                <div class="home-mobile-landing-popular-item-image">
                  <img src="http://www.monogramtea.com/skin/frontend/gryphon/gryphon_theme/images/products_svg/cherry-japonais.svg" class="parent" alt="">                              
                  <img src="http://www.monogramtea.com/skin/frontend/gryphon/gryphon_theme/images/products_svg/uji-sencha.svg" class="overlay" alt="">
                </div>
                <div class="home-mobile-landing-popular-item-copy">

                  <div class="home-mobile-landing-popular-item-title">
                    <h2><span style="color:#c0cdd5">Earl Grey</span> <span style="color:#d8d1ca">Neroli</span></h2>
                    <div class="plus-sign">+</div>
                    <h2><span style="color:#c7c89b">Shiso</span> <span style="color:#bcc4b9">Mint</span></h2>
                  </div>

                  <h6>by monogram</h6>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada massa...</p>
                </div>
              </a>

            </div> -->

          </div> <!-- #home-mobile-landing-popular-item -->

          <div id="home-mobile-landing-popular-cta-container">
            <a href="http://www.monogramtea.com/store.html" class="square-cta">visit store</a>
          </div>
        </div> <!-- #home-mobile-landing-popular-subsection -->

      </div>
    </div>
  </div>
</article> <!-- home-mobile-landing-section -->



<article id="home-mobile-tea-layering-section">

  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div id="home-mobile-tea-layering-title">
          <h4>Tea Layering Suggestions</h4>
          <p>Choose a tea to see its layering suggestions.</p>
        </div>
      </div>
    </div>
  </div>


  <!--
     __  __  ___  ____ ___ _     _____   ____  ____   ___  ____  _   _  ____ _____   _     ___ ____ _____
    |  \/  |/ _ \| __ )_ _| |   | ____| |  _ \|  _ \ / _ \|  _ \| | | |/ ___|_   _| | |   |_ _/ ___|_   _|
    | |\/| | | | |  _ \| || |   |  _|   | |_) | |_) | | | | | | | | | | |     | |   | |    | |\___ \ | |
    | |  | | |_| | |_) | || |___| |___  |  __/|  _ <| |_| | |_| | |_| | |___  | |   | |___ | | ___) || |
    |_|  |_|\___/|____/___|_____|_____| |_|   |_| \_\\___/|____/ \___/ \____| |_|   |_____|___|____/ |_|

  -->


  <?php 
    $groupname = '';
    if(Mage::getSingleton('customer/session')->isLoggedIn()) {
        $customerData = Mage::getSingleton('customer/session')->getCustomer();
        $customerGroupId = $customerData->getGroupId();
        $groupname = Mage::getModel('customer/group')->load($customerGroupId)->getCustomerGroupCode();  
    }
    if($groupname=='Trader-Temp' || $groupname=='Trader-Regular' || $groupname=='Trader-Priority' || $groupname=='Trader-Premium') $categoryId = 118;        
    else $categoryId = 92;

    $_productCollection = Mage::getModel('catalog/category')->load($categoryId)
                         ->getProductCollection()
                         ->addAttributeToSelect('*')
                         ->addAttributeToFilter('status', 1) // enabled
                         ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
                         ->addAttributeToSort('position', Varien_Data_Collection::SORT_ORDER_ASC);
    $_helper = $this->helper('catalog/output');
  ?>


  <div id="home-tea-item-container-mobile">
      <?php $count = 0; ?>
      <?php foreach ($_productCollection as $key => $_product):    
          $_imgSize = 300;
          $_imgSize2x = 600;
          $categoryIds = $_product->getCategoryIds();

          $color_arr = ["#eebec7", "#abc6ca", "#a1b2ca", "#d9d1c3", "#c7b4e3", "#f0a693", "#beced6", "#fed198", "#c2cb7e", "#f9a960", "#fa91a2", "#bac4b8"];        

          $product_name = $_product->getName();

          $product_name = strtolower($product_name);
          $product_name = str_replace(" ", "-", $product_name);
      ?>

      <a href="#graph/<?php echo $product_name; ?>" class="home-tea-item-mobile home-page-add-to-cart-mobile" id="add-to-cart-<?php echo $product_name; ?>"  data-id="<?php echo $product_name; ?>">
          <div class="home-tea-item-bg" style="background-color: <?php echo $color_arr[$count]; ?>;"></div>
          <div class="home-tea-item-text">
              <?php if(!empty($_product->getData('product_name_in_color'))): ?>
              <h2><?php echo $_product->getData('product_name_in_color') ?></h2>
              <?php else: ?>
              <h2><?php echo $_product->getName(); ?></h2>
              <?php endif; ?>


          </div>
      </a>
      <?php $count++; ?>
      <?php endforeach; ?>        
  </div> <!-- #home-tea-item-container -->


  <script>
    $j(document).ready(function($){
      $('.home-mobile-buy-both-teas-cta').on('click', function(e){
        e.preventDefault();
        $('#add-to-cart-shiso-mint').trigger('click');
        $('#add-to-cart-earl-grey-neroli').trigger('click');

        // alert('Added to cart');
      });

      $('.home-mobile-buy-both-teas-cta-2').on('click', function(e){
        e.preventDefault();
        var main_tea = $('.graph-selection-tea-mobile').find("#graph-selection-name-01").data("id");
        var sub_tea = $('.graph-selection-tea-mobile').find("#graph-selection-name-02").data("id");
        
        $('#add-to-cart-'+main_tea).trigger('click');
        $('#add-to-cart-'+sub_tea).trigger('click');

        // alert('Added to cart');
      });
    });
  </script>

  <!--
  <script>
  $j(document).ready(function($){
      function do_update() {
          $.ajax({
              url: '/discovertea/index/cartpreview',
              dataType: 'json',
              type : 'get',
              success: function(data){

                  // update product count in cart
                  $j("#desktop-header-cart").find(".count").text("("+data.cart_qty+")");
            
              }
          });                     
      }
      $(".home-page-add-to-cart-mobile").on("click", function(e){
          e.preventDefault();

          var add_to_cart_url = $(this).attr("href");
          $.get( add_to_cart_url, function( data ) {
             do_update();
          });
      });
  });
  </script>
  -->

  <!--
     __  __  ___  ____ ___ _     _____   ____  ____   ___  ____  _   _  ____ _____   _     ___ ____ _____   _____ _   _ ____
    |  \/  |/ _ \| __ )_ _| |   | ____| |  _ \|  _ \ / _ \|  _ \| | | |/ ___|_   _| | |   |_ _/ ___|_   _| | ____| \ | |  _ \
    | |\/| | | | |  _ \| || |   |  _|   | |_) | |_) | | | | | | | | | | |     | |   | |    | |\___ \ | |   |  _| |  \| | | | |
    | |  | | |_| | |_) | || |___| |___  |  __/|  _ <| |_| | |_| | |_| | |___  | |   | |___ | | ___) || |   | |___| |\  | |_| |
    |_|  |_|\___/|____/___|_____|_____| |_|   |_| \_\\___/|____/ \___/ \____| |_|   |_____|___|____/ |_|   |_____|_| \_|____/

  -->
  
</article> <!-- home-mobile-tea-layering-section -->











<!--
    ____ ____      _    ____  _   _
   / ___|  _ \    / \  |  _ \| | | |
  | |  _| |_) |  / _ \ | |_) | |_| |
  | |_| |  _ <  / ___ \|  __/|  _  |
   \____|_| \_\/_/   \_\_|   |_| |_|

-->


<article id="tea-layering-detail-graph-section">


  <div id="tea-layering-graph-mobile" class="monogram-combination-graph">

    <div class="graph-svg"></div>                
    <div class="graph-name-overlay">
      <div class="graph-name-item floral-version"></div>
      <div class="graph-name-item creamy-version"></div>
      <div class="graph-name-item marine-version"></div>
      <div class="graph-name-item mineral-version"></div>
      <div class="graph-name-item citrus-version"></div>
      <div class="graph-name-item fruity-version"></div>
      <div class="graph-name-item sweet-version"></div>
      <div class="graph-name-item wood-version"></div>
      <div class="graph-name-item herbaceous-version"></div>
    </div>
    <div class="graph-overlay"></div>


    <!--
    <div id="combination-graph-text-container">
    </div>
    <div id="combination-graph-svg-container">
      <div id="combination-graph-svg"></div>
    </div>

    <div id="combination-graph-label">
      <div class="graph-label-image graph-label-wood"></div>
      <div class="graph-label-image graph-label-savoury"></div>
      <div class="graph-label-image graph-label-herbaceous"></div>
      <div class="graph-label-image graph-label-floral"></div>
      <div class="graph-label-image graph-label-nutty"></div>
      <div class="graph-label-image graph-label-dairy"></div>
      <div class="graph-label-image graph-label-minerality"></div>
      <div class="graph-label-image graph-label-citrus"></div>
      <div class="graph-label-image graph-label-stone-fruit"></div>
      <div class="graph-label-image graph-label-red-fruit"></div>
      <div class="graph-label-image graph-label-sweet"></div>
    </div>
    -->

  </div>
</article>


<!--
    ____ ___  ______   __
   / ___/ _ \|  _ \ \ / /
  | |  | | | | |_) \ V /
  | |__| |_| |  __/ | |
   \____\___/|_|    |_|

 -->


<article id="tea-layering-detail-copy-section">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">

        <div class="graph-selection-tea-mobile">

          <div class="graph-selection-title">
            <h4>layering suggestions <span class="number">1/4</span></h4>
          </div>

          <div class="graph-selection-name">
            <div id="graph-selection-name-01">
              <h2><span style="color:#c0cdd5">Earl Grey</span> <span style="color:#d8d1ca">Neroli</span></h2>
            </div>
            <div id="graph-selection-name-02">
              <div class="plus-sign">+</div>
              <h2><span style="color:#c7c89b">Shiso</span> <span style="color:#bcc4b9">Mint</span></h2>
            </div>
          </div>

          <div class="tea-copy-content">
            <p>Suspendisse in enim nisl. Duis nec lacus magna. Curabitur tempus metus in libero lacinia posuere. Duis accumsan bibendum dapibus. </p>
          </div>


          <div id="page-tea-layering-detail-next-arrow"></div>
          <div id="page-tea-layering-detail-prev-arrow"></div>

        </div> <!-- graph-selection-tea-mobile -->



        <div class="button-container button-container-01">
          <?php if(Mage::getSingleton('customer/session')->isLoggedIn() && !$trade): ?>
          <a href="javascript:void(0);" id="home-mobile-save-layering" class="square-cta square-cta-01">save layering</a>
          <?php else: ?>
          <?php $store_category = Mage::getModel('catalog/category')->loadByAttribute('name', 'Store'); ?>
          <a href="<?php echo $store_category->getUrl(); ?>" class="square-cta square-cta-01">visit tea bar</a>
          <?php endif; ?>
          <?php if(!$trade): ?>
          <a href="javascript:void(0);" class="home-mobile-buy-both-teas-cta-2 square-cta square-cta-02">add both to cart</a>
          <?php endif; ?>
          <div class="home-customized-share-button square-cta square-cta-02">
            <span>Share Layering</span>
            <ul>
              <li><a href="http://www.pinterest.com" target="_blank" class="fa fa-pinterest"></a></li>
              <li><a href="http://www.twitter.com" target="_blank" class="fa fa-twitter"></a></li>
              <li><a href="http://www.facebook.com" class="fa fa-facebook"></a></li>
            </ul>
          </div>
        </div>
        <?php if(!$trade): ?>
        <div class="button-container button-container-02">
          <a href="" class="square-cta square-cta-03" id="tea-layering-detail-copy-tea-detail-01-cta">see earl grey neroli</a>
          <a href="" class="square-cta square-cta-04"  id="tea-layering-detail-copy-tea-detail-02-cta">see shiso mint</a>
        </div>
        <?php endif; ?>

        
        

      </div>
    </div>
  </div>
</article>








<!--
   _____ ___   ___ _____ _____ ____
  |  ___/ _ \ / _ \_   _| ____|  _ \
  | |_ | | | | | | || | |  _| | |_) |
  |  _|| |_| | |_| || | | |___|  _ <
  |_|   \___/ \___/ |_| |_____|_| \_\

-->


<footer id="tea-layering-detail-footer-mobile-fixed">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-next-suggestion-container">
          <div class="page-tea-layering-detail-next-suggestion-btn">
            <span class="fa fa-arrows-h"></span>
            <h4>Next Suggestion</h4>
          </div>
        </div>

      </div>
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-other-container">
          <a href="#selection" class="page-tea-layering-detail-other-btn">
            <span class="fa fa-th"></span>
            <h4>Choose Other Teas</h4>
          </a>
        </div>

      </div>
    </div>
  </div>
</footer>



<div id="tea-layering-detail-footer-mobile-spacer">
  <div class="step-01"></div>
  <div class="step-02"></div>
  <div class="step-03"></div>
  <div class="step-04"></div>
  <div class="step-05"></div>
  <div class="step-06"></div>
</div>


<footer id="tea-layering-detail-footer-mobile">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-next-suggestion-container">
          <div class="page-tea-layering-detail-next-suggestion-btn">
            <span class="fa fa-arrows-h"></span>
            <h4>Next Suggestion</h4>
          </div>
        </div>

      </div>
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-other-container">
          <a href="#selection" class="page-tea-layering-detail-other-btn">
            <span class="fa fa-th"></span>
            <h4>Choose Other Teas</h4>
          </a>
        </div>

      </div>
    </div>
  </div>
</footer>









<!--
   __  __  ___  ____ ___ _     _____   _____ ___   ___ _____ _____ ____
  |  \/  |/ _ \| __ )_ _| |   | ____| |  ___/ _ \ / _ \_   _| ____|  _ \
  | |\/| | | | |  _ \| || |   |  _|   | |_ | | | | | | || | |  _| | |_) |
  | |  | | |_| | |_) | || |___| |___  |  _|| |_| | |_| || | | |___|  _ <
  |_|  |_|\___/|____/___|_____|_____| |_|   \___/ \___/ |_| |_____|_| \_\

-->

<!-- not sure why it's not available in the home page... -->

<footer id="mobile-footer" class="visible-sm visible-xs">

  <div id="mobile-footer-copy-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">


            
          <div id="mobile-footer-copy">
            <h4>Newsletter</h4>
            <p>Get the latest news, product, announcments, promotions, and more!</p>
          </div> <!-- mobile-footer-copy -->

          <form id="mobile-newsletter-subscribe-form" class="home-page-mobile-subscribe-form simple-form-check">
              <div class="form-group">
                <input type="text" name="subscribe_email" class="subscribe_email required only-email" placeholder="Enter Your Email Address">
                <input type="submit" class="subscribe_newsletter">
                <span class='newsletter_ajax_loader' style='display:none'><img src='<?php echo $this->getSkinUrl('images/icons/spin.svg')?>'/></span>
              </div>
              <span class="ajax_msg italic"></span>
            </form>

          <div id="mobile-footer-links">
            <ul>
              <li><a href="<?php echo $this->getUrl('privacy-policy'); ?>">Privacy Policy</a></li>
              <li><a href="<?php echo $this->getUrl('terms-and-conditions'); ?>">Terms & Conditions</a></li>
            </ul>
          </div>

        </div>
      </div>



    </div>
  </div> <!-- mobile-footer-copy-section -->

  <div id="mobile-footer-copyright-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">

          <div id="mobile-footer-copyright">
            <a href="<?php echo $this->getUrl('') ?>" id="mobile-footer-logo"></a>
            <h4>Monogram by Gryphon Tea Company</h4>
          </div>

        </div>
      </div>
    </div>
  </div> <!-- mobile-footer-copywrite-section -->

</footer>
<script>
    jQuery(document).ready(function($){
      $('.home-page-mobile-subscribe-form').find('.subscribe_email').keypress(function(event){
        var keycode = (event.keyCode ? event.keyCode : event.which);
        if(keycode == '13') 
          $('.home-page-mobile-subscribe-form').find('.subscribe_newsletter').trigger('click');
      });
      $('.home-page-mobile-subscribe-form').find('.subscribe_newsletter').click(function(e){
        e.preventDefault();        
        var subscribe_email = $(this).prev('.subscribe_email').val();

        if(subscribe_email!=="" && subscribe_email!=="Enter Your Email Address") {
          $('.newsletter_ajax_loader').show();

          var request = $.ajax({
              url: "<?php echo $this->getUrl('discovertea/index/subscribe', array('_secure'=>true)) ?>",
              method: "POST",
              data: { subscribe_email : subscribe_email },
              dataType: "html"
          });
           
          request.done(function( msg ) {
            var message = JSON.parse(msg);
            console.log(message);
            $('.newsletter_ajax_loader').hide();
            if(message.error_messages)
              $('span.ajax_msg').html('<p>'+message.error_messages+'</p>').show().delay(5000).fadeOut();              
              else
              $('span.ajax_msg').html('<p>Successfully subscribed to newsletter</p>').show().delay(5000).fadeOut();
          });
        }        
      });

      $('#home-mobile-save-layering').click(function(e){
        e.preventDefault();
        var pidvalue1 = jQuery(".graph-selection-tea-mobile .graph-selection-name #graph-selection-name-01").attr('data-id');
        var pidvalue2 = jQuery(".graph-selection-tea-mobile .graph-selection-name #graph-selection-name-01").attr('data-id');
        //alert(pidvalue1);alert(pidvalue2);
        // jQuery("#successmsg").hide();
        // jQuery("#ajax_loadermsg").show();    
        console.log(pidvalue1)
        console.log(pidvalue2)
        var cid = '<?php echo $cid ?>';
        var pid = pidvalue1+'|||'+pidvalue2;
        var dataString = 'cid='+ cid + '&pid='+ pid;
              jQuery.ajax({
                  type: "POST",
                  data: dataString,
                  url: "<?php echo Mage::getUrl('savelayering/index/ajax'); ?>"
              }).done(function(result) { 
                // jQuery("#ajax_loadermsg").hide();
                // jQuery("#successmsg").show();
                // jQuery("#successmsg").html(''+result+'');        
                alert(result);
              });
      });
    });
  </script>