<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>

<?php $_collectionSize = 5;//count($_products->getItems()); echo $_collectionSize; ?>

<?php $i=1; foreach ($_products->getItems() as $_product): ?>
    <div class="center-text">
        <a href="<?php echo $_product->getProductUrl() ?>" class="product-img">
            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150, 150); ?>" alt="tea <?php echo $i ?>">
            <p class="caption"><?php echo $this->htmlEscape($_product->getName()) ?></p>
            <?php $product_data = $_product->getData(); ?>
            <!-- <p class="caption-2"><?php //echo Mage::helper('core/string')->truncate($product_data['short_description'], 50); ?></p>         -->
            <?php
            $categoryIds = $_product->getCategoryIds();
            if(count($categoryIds) ){
                foreach ($categoryIds as $key => $categoryId) {
                    $_category = Mage::getModel('catalog/category')->load($categoryId);
                    $parent_category = Mage::getModel('catalog/category')->load($categoryId)->getParentCategory();    
                    if($parent_category->getId()==5) { ?>
                        <p><?php echo $_category->getName(); ?></p>
            <?php   }
                }
            }
            ?>
        </a>
        <!-- <ul class="cta-list">
            <li><a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/icons/magnifying-glass.png'); ?>" alt="magnifying glass"></a></li>
            <li><a href="<?php echo $this->getAddToCartUrl($_product) ?>"><img src="<?php echo $this->getSkinUrl('images/icons/plus-sign.png'); ?>" alt="plus sign"></a></li>
        </ul> -->
    </div>
    <!-- <li id="td_<?php echo $i;?>" <?php if($i%5==0 or $i==$_collectionSize){echo 'class="last"';} ?> >
        <div id="cont_<?php echo $i;?>">        
            <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
            </a>
            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
            <div class="a-center">                        
                <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <?php if($_product->isSaleable()): ?>
                    <button class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><span><?php echo $this->__('Add to Cart') ?></span></span></span></button>
                    <div class="clear"></div>
                <?php else: ?>
                    <p class="availability"><span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                    <div class="clear"></div>
                <?php endif; ?>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                    <li class="last"><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </li> -->
<?php $i++; endforeach; $kol = $_collectionSize; ?>




<?php endif; ?>