<?php
$groupname = '';
if(Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customerData = Mage::getSingleton('customer/session')->getCustomer();
    $customerGroupId = $customerData->getGroupId();
    $groupname = Mage::getModel('customer/group')->load($customerGroupId)->getCustomerGroupCode();  
}
if($groupname=='Trader-Temp' || $groupname=='Trader-Regular' || $groupname=='Trader-Priority' || $groupname=='Trader-Premium') $categoryId = 118;        
else $categoryId = 92;

$_productCollection = Mage::getModel('catalog/category')->load($categoryId)
                     ->getProductCollection()
                     ->addAttributeToSelect('*')
                     ->addAttributeToFilter('status', 1) // enabled
                     ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
                     ->addAttributeToSort('position', Varien_Data_Collection::SORT_ORDER_ASC);
$_helper = $this->helper('catalog/output');   
$count = 1;
?>


<!--
   ____  _____ ____  _  _______ ___  ____
  |  _ \| ____/ ___|| |/ /_   _/ _ \|  _ \
  | | | |  _| \___ \| ' /  | || | | | |_) |
  | |_| | |___ ___) | . \  | || |_| |  __/
  |____/|_____|____/|_|\_\ |_| \___/|_|

-->



<style id="graph-zooming-style"></style>

<article id="tea-matrix-section-1" class="visible-md visible-lg">

  









  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
          
      </div>
    </div>  
  </div>     
  <div id="tea-matrix-content">

      <div id="tea-matrix-content-section-container-container">
        <?php 
        $count = 1;
        foreach ($_productCollection as $key => $_product):            
            $product_name = $_product->getName();
        ?>


        
          <div id="tea-matrix-content-section-<?php echo $count; ?>" class="section">
            <div class="tea-matrix-content-text-cta">
              <h3 class="tea-matrix-content-animate"><?php echo ($_product->getData('product_name_in_color')) ? $_product->getData('product_name_in_color') : $product_name ; ?></h3>
              <p class="tea-matrix-content-animate"><?php echo $_product->getDescription(); ?></p>
              <hr class="top tea-matrix-content-animate">
              <?php echo $_product->getData('tea_matrix_content'); ?>              
              <hr class="bottom tea-matrix-content-animate">

              <div class="suggestions">                
                <h5 class="tea-matrix-content-animate">Layering Suggestions</h5>
                <?php 
                $object = Mage::getModel('catalog/product');
                $upsell_product = $_product->getUpSellProductCollection()->addAttributeToSort('position', Varien_Db_Select::SQL_ASC)->addStoreFilter();
                  //if result is not empty then get  upsell product detail using foreach loop      
                  foreach($upsell_product as $_upsell):
                    //get detail of single upsell prdocut using upsell product id
                    $upsp = $object->load($_upsell->getId());        
                  ?>    
                
                <div class="suggestion tea-matrix-content-animate"><?php echo $upsp->getData('product_name_in_color') ?></div>
                <?php endforeach; ?>
              </div>

              <a href="<?php echo $_product->getProductUrl() ?>" class="square-cta tea-matrix-content-animate">View Product</a>
              <?php if($groupname!=='Trader-Temp' && $groupname!=='Trader-Regular' && $groupname!=='Trader-Priority' && $groupname!=='Trader-Premium'): ?>
                <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="square-cta tea-matrix-content-animate tea-matrix-add-to-cart">add to cart</a>
              <?php endif; ?>
              <span id='ajax_loader_product' style='display:none'><img src='<?php echo $this->getSkinUrl('images/icons/spin.svg')?>'/></span>
              <span class="ajax_msg_product italic"></span>
            </div> <!-- .tea-matrix-content-text-cta -->

          </div>
        



          <?php $count++; ?>
        <?php endforeach; ?>
      </div> <!-- #tea-matrix-content-section-container-container -->



      <div id="monograph-graph-data" 
        data-graph-data-url="/skin/frontend/gryphon/gryphon_theme/json/graph-data.json">
      </div>

      <div id="tea-matrix-combination-graph-container-another-one">
        <div id="tea-matrix-combination-graph" class="monogram-combination-graph" data-id="cherry-japonais">
          <div class="graph-svg"></div>                
          <div class="graph-name-overlay">
            <div class="graph-name-item floral-version"></div>
            <div class="graph-name-item creamy-version"></div>
            <div class="graph-name-item marine-version"></div>
            <div class="graph-name-item mineral-version"></div>
            <div class="graph-name-item citrus-version"></div>
            <div class="graph-name-item fruity-version"></div>
            <div class="graph-name-item sweet-version"></div>
            <div class="graph-name-item wood-version"></div>
            <div class="graph-name-item herbaceous-version"></div>
          </div>
          <div class="graph-overlay"></div>
        </div>
      </div>


      

  </div>


  <ul id="page-indicator">
    <?php $count = 1; ?>
    <?php foreach ($_productCollection as $key => $_product):            
        $product_name = $_product->getName();
    ?>
    <li id="page-indicator-<?php echo $count; ?>" data-menuanchor="<?php echo $count; ?>" class="<?php echo ($count==1) ? 'active' : ''; ?> page-indicator"><a href="#<?php echo $count; ?>" class="anchor" id="anchor-<?php echo $count; ?>"><?php echo ($_product->getData('product_name_in_color')) ? $_product->getData('product_name_in_color') : $product_name ; ?></a></li>
    <?php $count++; ?>
    <?php endforeach; ?>
  </ul>

</article>



<footer id="desktop-footer" class="visible-md visible-lg" style="position: absolute;bottom: 0;width: 100%;background-color: #6b615b;">
  <div id="desktop-footer-logo-tnc-container">
    <div class="container-fluid">
      <div class="col-md-4">
        <a href="<?php echo $this->getUrl('') ?>">
          <span id="desktop-footer-logo"></span>
          <h5 id="monogram-name">monogram by gryphon tea company</h5>
        </a>
      </div>
      <div class="col-md-3 col-md-offset-5">
        <ul>
          <li><a href="<?php echo $this->getUrl('privacy-policy'); ?>">Privacy Policy</a></li>
          <li><a href="<?php echo $this->getUrl('terms-and-conditions'); ?>">Terms & Condition</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<script>
  $j(document).ready(function($){

    $(".page-indicator").each(function(index, el){
      $(el).find("span").each(function(i, sel){
        var color = $(sel).attr("style").substring(6);
        $(sel).data('color', color);
        $(sel).attr('style', 'color: #fff');
      });
    });

    function changeIndicatorsColor($selector) {

      $(".active").find('span').removeAttr('style');
      $(".active").removeClass("active");
      $selector.parent().addClass("active");

      var $firstAnchor = $selector.find("span").first();
      var $lastAnchor = $selector.find("span").last();

      var firstColor = $firstAnchor.data('color');
      var lastColor = $lastAnchor.data('color');

      $firstAnchor.attr("style", "color: "+firstColor);
      $lastAnchor.attr("style", "color: "+lastColor);      
    }

    // $('#tea-matrix-content').fullpage({
    //   anchors: ['page1', 'page2', 'page3', 'page4', 'page5', 'page6', 'page7', 'page8', 'page9', 'page10', 'page11', 'page12'],
    //   menu: '#page-indicator',
    //   animateAnchor: false,
    //   fadingEffect: true,
    //   fitToSection: true,
    //   fitToSectionDelay: 50000,
    //   onLeave: function(index, nextIndex, direction){

    //     var loadedSection = $(this);
    //     $animate_content = $(loadedSection).find(".tea-matrix-content-text-cta").find('.tea-matrix-content-animate');

    //     TweenMax.staggerFromTo($animate_content, 0.1, { 'y': 0, opacity: 1, ease: Sine.easeOutQuad }, { 'y': 100, opacity: 0, ease: Sine.easeOutQuad }, 0.1);

    //     changeIndicatorsColor($("#anchor-"+nextIndex));

    //   },
    //   afterLoad: function(anchorLink, index){

    //       var loadedSection = $(this);          
    //       $animate_content = $(loadedSection).find(".tea-matrix-content-text-cta").find('.tea-matrix-content-animate');

    //       TweenMax.staggerFromTo($animate_content, 0.5, { 'y': 100, opacity: 0, ease: Sine.easeOutQuad }, { 'y': 0, opacity: 1, ease: Sine.easeOutQuad }, 0.1);
    //   }
    // });    

    var currentSection = 1;
    var animating = false;
    // var tl2 = new TimelineLite();

    function updateStatus() {
      animating = false;
    }

    function onceSectionHidden(showSectionNo) {

      showSection(showSectionNo);

    }

    function hideSection(sectionNo, showSectionNo) {

      var $hideSection = $('#tea-matrix-content-section-'+sectionNo);

      $hideSection.removeClass('active-section');

      $animate_content = $hideSection.find(".tea-matrix-content-text-cta").find('.tea-matrix-content-animate');
      // $animate_content.attr('style', 'opacity:0;');

      $animate_content = $hideSection.find(".tea-matrix-content-text-cta").find('.tea-matrix-content-animate');

      TweenMax.killTweensOf($animate_content);

      // var tl2 = new TimelineLite({ onComplete: onceSectionHidden, onCompleteParams: [showSectionNo] });
      // tl2.add(
        TweenMax.staggerFromTo($animate_content, 0.1, { 'y': 0, opacity: 1, ease: Sine.easeOutQuad }, { 'y': 10, opacity: 0, ease: Sine.easeOutQuad, onComplete: onceSectionHidden, onCompleteParams: [showSectionNo] })
      // );

    }

    function showSection(sectionNo) {

      var $showSection = $('#tea-matrix-content-section-'+sectionNo);

      $showSection.addClass('active-section');
      $animate_content = $showSection.find(".tea-matrix-content-text-cta").find('.tea-matrix-content-animate');      

      TweenMax.killTweensOf($animate_content);

      // var tl = new TimelineLite({ onComplete:updateStatus });      
      // tl.add(
        TweenMax.staggerFromTo($animate_content, 0.3, { 'y': 10, opacity: 0, ease: Sine.easeOutQuad }, { 'y': 0, opacity: 1, ease: Sine.easeOutQuad, onComplete:updateStatus }, 0.1)
      // );

      changeIndicatorsColor($("#anchor-"+sectionNo));


      var single_graph = $('#tea-matrix-combination-graph').data('monogram.graph.SingleGraph');

      console.log(single_graph);

      if(single_graph != null){
        
        // the order was changed....
        
        var id_array = [
            'cherry-japonais',
            'uji-sencha',            
            'jasmine-silk-pearls',
            'milky-oolong',
            'lapsang-florale',
            'kashmere',
            'earl-grey-neroli',
            'morning-english',
            'provencal-herbs',
            'saffronais',
            'rose-of-ariana',
            'shiso-mint'
          ];
        var target_id = id_array[parseFloat(sectionNo)-1]; //Math.floor(Math.random() * id_array.length)
        
        single_graph.set_data_by_id(target_id);
      }
                  
      console.log(sectionNo)
    }


    function init() {
      animating = true;
      if(window.location.hash) {
        var hash = window.location.hash.replace('#', '');        

        showSection(hash);
        currentSection = parseInt(hash);

      } else {        
        showSection(1); // init
      }
      // changeIndicatorsColor($("#page-indicator li.active a"));
    }

    init();

    // events
    

    $('body').on('tea-matrix-mouse-down', function(event){
      if (animating == false) {
        animating = true;
        var totalSection = $('#tea-matrix-content').find(".section").length;

        if(currentSection>=1 && currentSection<totalSection) {            

          animating = true;

          hideSection(currentSection, currentSection+1);
          currentSection++;

        }
      }
    });
    $('body').on('tea-matrix-mouse-up', function(event){
      if (animating == false) {
        var totalSection = $('#tea-matrix-content').find(".section").length;
        
        if(currentSection>1) {

          animating = true;

          hideSection(currentSection, currentSection-1);
          currentSection--;

        }  
      }
    });

    /*
    $('body').on('mousewheel', function(event) {

        var totalSection = $('#tea-matrix-content').find(".section").length;

        console.log(currentSection)

        if(event.deltaY < 0 && animating == false) {     

          if(currentSection>=1 && currentSection<totalSection) {            

            animating = true;

            hideSection(currentSection, currentSection+1);
            currentSection++;

          }

        }else if(event.deltaY > 0  && animating == false) {                  

          if(currentSection>1) {

            animating = true;

            hideSection(currentSection, currentSection-1);
            currentSection--;

          }      

        }
    });
    */

    $("#page-indicator .anchor").on("click", function(e){
      e.preventDefault();
      e.stopPropagation();

      // if(animating == false) {
        animating = true;

        var currentIndex = $(".active-section").index() + 1;
        console.log('currentIndex:'+currentIndex)
        activeSection = currentIndex;
        //console.log('current: '+activeSection)        
        currentSection = $(this).parent().data('menuanchor');
        console.log('destination: '+currentSection)
        hideSection(activeSection, currentSection);
        
      // }
      
    });    

    function do_update($el) {

      jQuery("#desktop-header-cart").find(".cart-count-update").removeClass('animated fadeIn').addClass('animated fadeOutDown');

      $.ajax({
          url: '/discovertea/index/cartpreview',
          dataType: 'json',
          type : 'get',
          success: function(data){
            // $el.parent().find('span.ajax_msg_product').html('Added to cart!').show().delay(5000).fadeOut();
            $("#desktop-header-cart").find(".count").text("("+data.cart_qty+")");
            $el.parent().find('#ajax_loader_product').hide();

            jQuery("#desktop-header-cart").find(".cart-count-update").removeClass('animated fadeOutDown').addClass('animated fadeIn');
          }
      });                     
    }

    $(".tea-matrix-add-to-cart").on("click", function(e){
      e.preventDefault();
      $(this).parent().find('#ajax_loader_product').show();

      var $el = $(this);

      var add_to_cart_url = $(this).attr("href");
      $.get( add_to_cart_url, function( data ) {
         do_update($el);
      });
    });

  });
</script>

















<!--
   __  __  ___  ____ ___ _     _____
  |  \/  |/ _ \| __ )_ _| |   | ____|
  | |\/| | | | |  _ \| || |   |  _|
  | |  | | |_| | |_) | || |___| |___
  |_|  |_|\___/|____/___|_____|_____|

-->





<article id="tea-layering-detail-graph-section" class="visible-sm visible-xs">

  <div id="tea-matrix-combination-graph-mobile" class="monogram-combination-graph" data-id="cherry-japonais">
    <div class="graph-svg"></div>                
    <div class="graph-name-overlay">
      <div class="graph-name-item floral-version"></div>
      <div class="graph-name-item creamy-version"></div>
      <div class="graph-name-item marine-version"></div>
      <div class="graph-name-item mineral-version"></div>
      <div class="graph-name-item citrus-version"></div>
      <div class="graph-name-item fruity-version"></div>
      <div class="graph-name-item sweet-version"></div>
      <div class="graph-name-item wood-version"></div>
      <div class="graph-name-item herbaceous-version"></div>
    </div>
    <div class="graph-overlay"></div>
  </div>


  <!--
  <div id="tea-layering-graph-mobile" class="monogram-combination-graph">
    <div class="graph-svg"></div>                
    <div class="graph-name-overlay">
      <div class="graph-name-item floral-version"></div>
      <div class="graph-name-item creamy-version"></div>
      <div class="graph-name-item marine-version"></div>
      <div class="graph-name-item mineral-version"></div>
      <div class="graph-name-item citrus-version"></div>
      <div class="graph-name-item fruity-version"></div>
      <div class="graph-name-item sweet-version"></div>
      <div class="graph-name-item wood-version"></div>
      <div class="graph-name-item herbaceous-version"></div>
    </div>
    <div class="graph-overlay"></div>
  </div>
  -->

</article>







<!--
    ____ ___  ______   __
   / ___/ _ \|  _ \ \ / /
  | |  | | | | |_) \ V /
  | |__| |_| |  __/ | |
   \____\___/|_|    |_|

 -->


<article id="tea-layering-detail-copy-section" class="visible-sm visible-xs animate-in">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">

        <script type="text/javascript">

          var arr = $j('.graph-selection-tea-mobile-item');
          var item = null;

          for (var i = 0, l=arr.length; i < l; i++) {
            item = $j(arr[i]);
            console.log(item.find('h2').html())
            console.log(item.attr('data-product-id'))
          }

        </script>


        <div class="graph-selection-tea-mobile">

          <?php 
            $count = 1;
            $custom_extra_class = '';
            foreach ($_productCollection as $key => $_product):
                $product_name = $_product->getName();

                $custom_extra_class = '';
                if($count==1) {
                  $custom_extra_class = ' visible-version';
                }

          ?>

            <div class="graph-selection-tea-mobile-item <?php echo $custom_extra_class; ?>" data-product-id="<?php echo $_product->getId(); ?>">

              <div class="graph-selection-name">
                <h2><?php echo ($_product->getData('product_name_in_color')) ? $_product->getData('product_name_in_color') : $product_name ; ?></h2>
              </div>

              <div class="tea-copy-content">
                <p><?php echo $_product->getDescription(); ?></p>
              </div>

              <div class="tea-custom-matrix-content-mobile">
                <hr>
                  <?php echo $_product->getData('tea_matrix_content'); ?>
                <hr>
              </div> <!-- .tea-custom-matrix-content-mobile -->

              <div class="tea-custom-suggestion-content-mobile">
                <h4>layering suggestions</h4>

                <?php 
                $object = Mage::getModel('catalog/product');
                $upsell_product = $_product->getUpSellProductCollection()->addAttributeToSort('position', Varien_Db_Select::SQL_ASC)->addStoreFilter();
                  //if result is not empty then get  upsell product detail using foreach loop      
                  foreach($upsell_product as $_upsell):
                    //get detail of single upsell prdocut using upsell product id
                    $upsp = $object->load($_upsell->getId());        
                  ?>    
                  
                  <h2><?php echo $upsp->getData('product_name_in_color') ?></h2>
                <?php endforeach; ?>

              </div> <!-- .tea-custom-suggestion-content-mobile -->



              <div class="cta-container">
                <a href="<?php echo $_product->getProductUrl() ?>" class="square-cta tea-matrix-content-animate">View Product</a>
                <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="square-cta tea-matrix-content-animate tea-matrix-add-to-cart">add to cart</a>

                <div class="cta-notification-contianer">
                  <span id='ajax_loader_product' style='display:none'><img src='<?php echo $this->getSkinUrl('images/icons/spin.svg')?>'/></span>
                  <span class="ajax_msg_product italic"></span>
                </div>
              </div>



            </div> <!-- .graph-selection-tea-mobile-item -->



          <?php 
              $count++;
            endforeach; 
          ?>



          

          


          <div id="page-tea-layering-detail-next-arrow"></div>
          <div id="page-tea-layering-detail-prev-arrow"></div>

        </div> <!-- graph-selection-tea-mobile -->




        <!--
        <div class="button-container button-container-01">
          <a href="javascript:void(0);" class="square-cta square-cta-01">save layering</a>
          <a href="#selection" class="square-cta square-cta-02">choose another layering</a>
        </div>

        <div class="button-container button-container-02">
          <a href="" class="square-cta square-cta-03" id="tea-layering-detail-copy-tea-detail-01-cta">see earl grey neroli</a>
          <a href="" class="square-cta square-cta-04"  id="tea-layering-detail-copy-tea-detail-02-cta">see shiso mint</a>
        </div>
        -->

        
        

      </div>
    </div>
  </div>
</article>











<!--
   _____ ___   ___ _____ _____ ____
  |  ___/ _ \ / _ \_   _| ____|  _ \
  | |_ | | | | | | || | |  _| | |_) |
  |  _|| |_| | |_| || | | |___|  _ <
  |_|   \___/ \___/ |_| |_____|_| \_\

-->


<footer id="tea-layering-detail-footer-mobile-fixed" class="visible-sm visible-xs">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">

        <div class="page-tea-layering-detail-select-hidden-container">
          
          <div class="select-display">
            <span class="fa fa-th"></span><h4>Choose Other Teas</h4>
          </div>

          <select id="page-tea-layering-detail-select-hidden-01">
            <option value="0">Cherry Japonais</option>
            <option value="1">Uji Sencha</option>
            <option value="2">Jasmine Silk Pearls</option>
            <option value="3">Milky Oolong</option>
            <option value="4">Lapsang Florale</option>
            <option value="5">Kashmere</option>
            <option value="6">Earl Grey Neroli</option>
            <option value="7">Morning English</option>
            <option value="8">Provencal Herbs</option>
            <option value="9">Saffronais</option>
            <option value="10">Rose of Ariana</option>
            <option value="11">Shiso Mint</option>
          </select>
        </div>
                
      </div>

    </div>
  </div>
</footer>



<div id="tea-layering-detail-footer-mobile-spacer" class="visible-sm visible-xs">
  <div class="step-01"></div>
  <div class="step-02"></div>
  <div class="step-03"></div>
  <div class="step-04"></div>
  <div class="step-05"></div>
  <div class="step-06"></div>
</div>


<footer id="tea-layering-detail-footer-mobile" class="visible-sm visible-xs">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">

        <div class="page-tea-layering-detail-select-hidden-container">
          
          <div class="select-display">
            <span class="fa fa-th"></span><h4>Choose Other Teas</h4>
          </div>
          <select id="page-tea-layering-detail-select-hidden-02">
            <option value="0">Cherry Japonais</option>
            <option value="1">Uji Sencha</option>
            <option value="2">Jasmine Silk Pearls</option>
            <option value="3">Milky Oolong</option>
            <option value="4">Lapsang Florale</option>
            <option value="5">Kashmere</option>
            <option value="6">Earl Grey Neroli</option>
            <option value="7">Morning English</option>
            <option value="8">Provencal Herbs</option>
            <option value="9">Saffronais</option>
            <option value="10">Rose of Ariana</option>
            <option value="11">Shiso Mint</option>
          </select>
        </div>
                
      </div>

    </div>
  </div>
</footer>




<!--
   __  __  ___  ____ ___ _     _____   _____ ___   ___ _____ _____ ____
  |  \/  |/ _ \| __ )_ _| |   | ____| |  ___/ _ \ / _ \_   _| ____|  _ \
  | |\/| | | | |  _ \| || |   |  _|   | |_ | | | | | | || | |  _| | |_) |
  | |  | | |_| | |_) | || |___| |___  |  _|| |_| | |_| || | | |___|  _ <
  |_|  |_|\___/|____/___|_____|_____| |_|   \___/ \___/ |_| |_____|_| \_\

-->

<!-- not sure why it's not available in the home page... -->

<footer id="mobile-footer" class="visible-sm visible-xs">

  <div id="mobile-footer-copy-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">


            
          <div id="mobile-footer-copy">
            <h4>Newsletter</h4>
            <p>Get the latest news, product, announcments, promotions, and more!</p>
          </div> <!-- mobile-footer-copy -->

          <form id="mobile-newsletter-subscribe-form" class="simple-form-check">
            <div class="form-group">
              <input type="text" class="required only-email" placeholder="Enter Your Email Address">
              <input type="submit">
            </div>
          </form>

          <div id="mobile-footer-links">
            <ul>
              <li><a href="<?php echo $this->getUrl('privacy-policy'); ?>">Privacy Policy</a></li>
              <li><a href="<?php echo $this->getUrl('terms-and-conditions'); ?>">Terms & Conditions</a></li>
            </ul>
          </div>

        </div>
      </div>



    </div>
  </div> <!-- mobile-footer-copy-section -->

  <div id="mobile-footer-copyright-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">

          <div id="mobile-footer-copyright">
            <a href="<?php echo $this->getUrl('') ?>" id="mobile-footer-logo"></a>
            <h4>Monogram by Gryphon Tea Company</h4>
          </div>

        </div>
      </div>
    </div>
  </div> <!-- mobile-footer-copywrite-section -->

</footer>
