<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<div class="post post-list-item">
	<?php echo $this->getBeforePostContentHtml() ?>
		<div class="post-content">
			<?php if ($post->isViewableForVisitor()): ?>
				<h1><?php echo $this->escapeHtml($post->getPostTitle()) ?></h1>
				<span><?php echo $post_date = $post->getPostDate(); ?></span>
				<hr class="small">

				<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
					<?php echo $post->getPostExcerpt() ?>
				<?php else: ?>
					<?php echo $post->getPostContent() ?>
				<?php endif; ?>

				<?php if ($featuredImage = $post->getFeaturedImage()): ?>					
						<img src="<?php echo $featuredImage->getFullSizeImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/>
				<?php endif; ?>
			<?php else: ?>
				<?php echo $this->getPasswordProtectHtml($post) ?>
			<?php endif; ?>
		</div>		
	<?php echo $this->getAfterPostContentHtml() ?>
</div>
<hr class="big">