<?php
	/**
	 * Cart total template
	*/
?>
<?php $total = $this->getTotal() ?>
<?php $codesArray = explode(',',$total->getGiftCodes()) ?>
<?php if (count($codesArray)): ?>

<?php $codesDiscountArray = explode(',',$total->getCodesDiscount()) ?>
<?php $discounts = array_combine($codesArray,$codesDiscountArray) ?>

	<?php foreach($discounts as $code=>$value): ?>
		<div class="row">
		  <div class="col-md-6 col-xs-6">
		    <div class="column-01">
		    	<p>GIFT CERTIFICATE:</p>
		    	<span class="discount_desc"><?php echo Mage::helper('giftvoucher')->getHiddenCode($code) ?></span>
		    	<a href="#" id="cancel_gift_cert" class="cancel-btn"><i class="fa fa-times-circle" aria-hidden="true"></i></a>
		    </div>
		  </div>
		  <div class="col-md-6 col-xs-6">
		    <div class="column-02">
		    	<p class="applied_discount_code minus"><?php echo $this->helper('checkout')->formatPrice(-$value) ?></p>
		    </div>
		  </div>
		</div>
	<?php endforeach ?>
	<script>
		jQuery("#cancel_gift_cert").click(function(e){
			e.preventDefault();
			jQuery(".cancel_giftcard").trigger("click");
		});
	</script>

<?php else: ?>
		<div class="each-details">
			<tr class="giftvoucher-total" onclick="toggleTotalCode()">
			    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $total->getStyle() ?>" class="a-right">
			        <?php echo $total->getTitle() ?>
			    </td>
			    <td style="<?php echo $total->getStyle() ?>" class="a-right">
			        <?php echo $this->helper('checkout')->formatPrice($total->getValue()) ?>
			    </td>
			</tr>
		</div>
<?php endif ?>
