<!--
               _____ ___  ____  __  __
              |  ___/ _ \|  _ \|  \/  |
              | |_ | | | | |_) | |\/| |
              |  _|| |_| |  _ <| |  | |
              |_|   \___/|_| \_\_|  |_|

            -->

            <div id="page-contact-form-container">
              <form action="<?php echo $this->getUrl('contacts/index/post') ?>" id="page-contact-form" class="checkout-form" method="post">

                <div id="page-contact-form-title">
                  <h2>Contact us</h2>
                  <p>For any feedback or enquiries, please feel free to drop us an email with the contact form below. We will be in touch as soon as we can to assist you.</p>
                </div>

                <?php echo $this->getMessagesBlock()->toHtml() ?>                

                <div class="form-group">
                  <div class="row">
                    <div class="col-md-4">
                      <label>First name*</label>
                    </div>
                    <div class="col-md-8">
                      <input name="first_name" id="first_name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="" class="input-class required-entry" type="text" />
                    <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="hidden" />
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <div class="row">
                    <div class="col-md-4">
                      <label>Last name*</label>
                    </div>
                    <div class="col-md-8">
                      <input name="last_name" id="last_name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="" class="input-text input-class required-entry" type="text" />        
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <div class="row">
                    <div class="col-md-4">
                      <label>Email address*</label>
                    </div>
                    <div class="col-md-8">
                      <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text input-class required-entry validate-email" type="text" />
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <div class="row">
                    <div class="col-md-4">
                      <label>Mobile*</label>
                    </div>
                    <div class="col-md-8">
                      <div class="roji-intltelinput-container">       
                        <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="roji-intltelinput remove-input-selection required-entry input-text input-class phone_no_input required-entry" type="text" unselectable="on" onselectstart="return false;" />
                      </div>
                    </div>
                  </div>
                </div>

                <div class="form-group dropdown-version">
                  <div class="row">
                    <div class="col-md-4">
                      <label>Type of enquiry*</label>
                    </div>
                    <div class="col-md-8">
                      <div class="dropdown">
                        <select name="role_within_organization" id="role_within_organization" class="required-entry">
                          <option value="">Please choose one</option>
                          <option value="General Enquiry">General Enquiry</option>
                          <option value="Online Order Enquiry">Online Order Enquiry</option>
                          <option value="Business Enquiry">Business Enquiry</option>
                          <option value="Media Enquiry">Media Enquiry</option>
                        </select>
                      </div> <!-- dropdown -->
                      
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <div class="row">
                    <div class="col-md-4">
                      <label>Message*</label>
                    </div>
                    <div class="col-md-8">
                      <textarea name="comment" id="comment" placeholder="Write your message here." title="<?php echo Mage::helper('contacts')->__('Message') ?>" class="required-entry input-text"></textarea>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-12 col-md-push-0 col-sm-10 col-sm-push-1 col-xs-10 col-xs-push-1">

                    <div class="cta-container">
                      <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                      <button type="submit" class="cta square-cta" id="contact-us-send-btn" title="<?php echo Mage::helper('contacts')->__('Send message') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Send message') ?></span></span></button>
                    </div>

                  </div>
                </div>

              </form> <!-- page-contact-form -->
              <script type="text/javascript">
              //<![CDATA[
                  var contactForm = new VarienForm('page-contact-form', true);
              //]]>
              </script>
              <script type="text/javascript">
                  jQuery(document).ready(function($) {

                    if($(".success-msg").length > 0) {
                      $(".form-group").hide();
                      $(".cta-container").hide();

                      setTimeout(function() {
                        window.location.href = "<?php echo $this->getUrl('') ?>";
                      }, 5000);

                    }

                    $(".phone_no_input, .mobile_no_input").intlTelInput({
                      initialCountry: 'sg',
                      nationalMode: false,
                      autoHideDialCode: false,
                      autoPlaceholder: false,
                      preferredCountries: []
                    });

                    $(".phone_no_input, .mobile_no_input").on("countrychange", function(e, countryData) {
                      console.log(countryData)
                      if(countryData.name=="Singapore") {
                        console.log('its singapore')
                        $(".phone_no_input").addClass("validate-mobile-singapore");
                      } else {
                        console.log('its not singapore')
                        $(".phone_no_input").removeClass("validate-mobile-singapore");
                      }
                    });

                    $(".phone_no_input").addClass("validate-mobile-singapore");

                    var currentCountryCode  = "";
                    $(document).keydown(function(e) {
                        var aEl = $(document.activeElement);

                        if(aEl.attr('name') == "telephone") {
                            var currentInputLength = aEl.val().length;       
                            var dialCode = aEl.intlTelInput("getSelectedCountryData").dialCode;         
                            
                            if(typeof dialCode !== "undefined") {
                                currentCountryCode = aEl.intlTelInput("getSelectedCountryData").dialCode;
                            }                      

                            var currentCountryCodeCount = currentCountryCode.toString().length + 3;

                            if ((e.keyCode === 8 || e.keyCode ===46) && currentInputLength < currentCountryCodeCount) 
                                return false;
                        }                
                    });

                    $('#first_name').on('change', function(e){
                      $('#name').val($(this).val() + ' ' + $('#last_name').val());
                    });

                    $('#last_name').on('change', function(e){
                      $('#name').val($('#first_name').val() + ' ' + $(this).val());
                    });

                    // var $phone_no = $("input[name='phone_no']");
                    // var $phone_no_2 = $("input[name='phone_no_2']");
                    // var $telephone = $("#telephone");
                    // $phone_no.on('change', function() {
                    //       var finalNo = $(this).val() + ' ' + $phone_no_2.val();
                    //       $telephone.val(finalNo);
                    // });

                    // $phone_no_2.keyup(function() {
                    //       var finalNo = $phone_no.val() + ' ' + $(this).val();
                    //       $telephone.val(finalNo);
                    // });

                    // $phone_no_2.on('change', function() {
                    //       var finalNo = $phone_no.val() + ' ' + $(this).val();
                    //       $telephone.val(finalNo);
                    // });

                  });
              </script>
            </div> <!-- page-contact-form-container -->