<?php
$_model = $this->getModel();
$args = $_model->getArgs();
?>
<script>
    function autoResize(id){
        var newheight;
        var newwidth;

        if(document.getElementById){
            newheight=document.getElementById(id).contentWindow.document.body.scrollHeight;
            newwidth=document.getElementById(id).contentWindow.document.body.scrollWidth;
        }

        document.getElementById(id).height= (newheight) + "px";
        document.getElementById(id).width= (newwidth) + "px";
    }
</script>
<div class="content-header">
    <h3 class="icon-head head-adminhtml-queue-view"><?php echo $this->getHeaderText() ?></h3>
    <p class="form-buttons"><button title="Back" type="button" class="scalable back" onclick="setLocation('<?php echo $this->getBackUrl() ?>')" style=""><span><span><span>Back</span></span></span></button></p>
</div>
<table width="100%">
    <tr>
        <td width="50%">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend">General Information</h4>
                    <div class="form-buttons"></div>
                </div>
                <div class="fieldset">
                    <table class="form-list">
                        <tr>
                            <td class="label"><?php echo Mage::helper('email')->__('Trigger') ?></td>
                            <td class="value">
                                <a href="<?php echo $this->getUrl('*/email_trigger/edit', array('id' => $_model->getTriggerId())) ?>">
                                    <?php echo $_model->getTrigger()->getTitle() ?>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('email')->__('Scheduled At') ?></td>
                            <td class="value">
                                <?php echo $this->formatDate($_model->getScheduledAt(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM, true) ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('email')->__('Sent At') ?></td>
                            <td class="value">
                                <?php echo $_model->getSentAt() ? $this->formatDate($_model->getSentAt(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM, true) : '-' ?>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('email')->__('Subject') ?></td>
                            <td class="value"><?php echo $_model->getSubject() ?></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('email')->__('Recipient Email') ?></td>
                            <td class="value"><?php echo $_model->getRecipientEmail() ?></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('email')->__('Recipient Name') ?></td>
                            <td class="value"><?php echo $_model->getRecipientName() ?></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('email')->__('Sender Email') ?></td>
                            <td class="value"><?php echo $_model->getSenderEmail() ?></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('email')->__('Sender Name') ?></td>
                            <td class="value"><?php echo $_model->getSenderName() ?></td>
                        </tr>
                    </table>
                </div>

                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend">History</h4>
                    <div class="form-buttons"></div>
                </div>
                <div class="fieldset">
                    <table class="form-list">
                        <?php foreach (explode(PHP_EOL, $_model->getHistory()) as $_message): ?>
                            <tr>
                                <td colspan="2"><?php echo $_message ?></td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                </div>

                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend">Variables</h4>
                    <div class="form-buttons"></div>
                </div>
                <div class="fieldset">
                    <table class="form-list">
                        <tr>
                            <td class="label"><?php echo Mage::helper('email')->__('Unique Key') ?></td>
                            <td class="value"><?php echo $_model->getUniqKey() ?></td>
                        </tr>
                        <?php foreach ($args as $_key => $_value): ?>
                            <tr>
                                <td class="label">
                                    <?php echo is_object($_value)
                                        ? $_key . '_id'
                                        : $_key ?>
                                </td>
                                <td class="value">
                                    <?php echo $this->getArgumentValue($_key, $_value, $args) ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                </div>
            </div>
        </td>
        <td width="50%">
            <iframe width="100%" height="100%" src="<?php echo $this->getPreviewUrl() ?>" style="border: 1px solid #d6d6d6; margin: 0px 5px 0px 5px;" id="iframe1" onLoad="autoResize('iframe1');">
            </iframe>
        </td>
    </tr>
</table>